/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import ArithmeticHeights.Extension
public import Mathlib.NumberTheory.Height.Projectivization

/-!
# The absolute height of a tuple of algebraic numbers

Mathlib's `Height.mulHeight` is the height **relative** to the field it is computed over: over a
number field `K` it is the `[K : ℚ]`-th power of the classical absolute height. This file defines
the absolute height of a tuple of algebraic numbers,

`absMulHeight x = mulHeight_F x ^ (1 / [F : ℚ])` with `F = ℚ(x₀, x₁, …)`,

and proves that the field of definition does not matter: any number field containing the
coordinates computes the same number. It is the tuple analogue of Mathlib's
`NumberField.absMulHeight₁`, which handles a single element through `ℚ⟮x⟯`, and restricts to it.

## Main definitions

* `NumberField.absMulHeight x` for `x : ι → K` over a field `K` of characteristic zero, and
  `NumberField.absLogHeight x`, its logarithm. A tuple with a coordinate that is not algebraic
  gets the junk value `1`, as `NumberField.absMulHeight₁` does.
* `Projectivization.absMulHeight` and `Projectivization.absLogHeight`: the descent to
  `Projectivization K (ι → K)` over a field all of whose elements are algebraic.

## Main results

* `NumberField.absMulHeight_eq`: over a number field `K`, `absMulHeight x` is
  `mulHeight x ^ (finrank ℚ K)⁻¹`. With `NumberField.mulHeight_pow_finrank` of Layer 0.3 this is
  the classical statement that the absolute height does not depend on the field of definition.
* `NumberField.absMulHeight_eq_of_mem`: the same, computed in an intermediate field containing
  the coordinates rather than in `K` itself. This is the form the other results consume.
* `NumberField.absMulHeight_comp`: invariance under an embedding of fields of characteristic
  zero — the absolute height belongs to the algebraic numbers themselves, not to any field
  holding them. It is what lets a value computed over `ℚ` be read off in `ℝ` or `ℂ`.
* `NumberField.absMulHeight_eq_absMulHeight₁`: the absolute height of `![x, 1]` is Mathlib's
  absolute height of `x`, so the tuple definition extends the one-variable one. With it,
  `NumberField.absMulHeight₁_comp` transports Mathlib's `absMulHeight₁` along an embedding —
  an algebraic number and each of its conjugates have the same absolute height.
* `NumberField.absMulHeight_smul_eq`: scaling invariance, for an **algebraic** scalar.
* `NumberField.absMulHeight_comp_le`: reindexing does not raise the height, and
  `NumberField.absMulHeight₁_le_absMulHeight`, the bound on the coordinates of an affine chart
  that Northcott's theorem on projective space runs on.
* `NumberField.absMulHeight_pow` and `NumberField.absMulHeight₁_pow`: the height of a
  coordinatewise power, together with `NumberField.absMulHeight₁_zero` and
  `NumberField.absMulHeight₁_one`. Kronecker's theorem of Layer 1.4 runs on these.

## Implementation notes

⚠ The algebraicity hypothesis on the scalar in `absMulHeight_smul_eq` is not decorative. For `c`
transcendental and `x` a nonzero algebraic tuple, `c • x` has a transcendental coordinate, so its
absolute height is the junk value `1` while that of `x` need not be; `absMulHeight` is then not
constant on the line through `x`. This is refuted among the examples at the end of the file. The
descent to `Projectivization K (ι → K)` is therefore stated over a field with
`[Algebra.IsAlgebraic ℚ K]` — a number field, or `AlgebraicClosure ℚ` — and not over a general
field of characteristic zero, even though `absMulHeight` itself is defined there.

Two facts about `Height.mulHeight` do the work. Passing from the field `ℚ(x₀, x₁, …)` generated by
the coordinates to a larger number field is `NumberField.mulHeight_pow_finrank` of Layer 0.3, and
the normalizing exponent is what cancels the degree it introduces. Passing between two *isomorphic*
number fields is the degree-one case of the same theorem, recorded here as
`NumberField.mulHeight_comp_ringEquiv`; it is what `absMulHeight_comp` needs, since an embedding
carries `ℚ(x₀, x₁, …)` to the field generated by the image coordinates, not into a fixed field.

The index type carries `Finite`, as `Height.mulHeight` does, where the roadmap's pinned signature
has `Fintype`; nothing here sums over `ι`.

## References

E. Bombieri and W. Gubler, *Heights in Diophantine Geometry*, Cambridge University Press (2006),
§1.5. Their `h(P)` is Definition 1.5.4, the absolute *logarithmic* height; the independence of the
field of definition is Lemma 1.5.2, the invariance under coordinate scaling that makes the height
projective is Lemma 1.5.3, and the affine case — the height of `(x₁, …, xₙ)` read as the height of
`(1 : x₁ : ⋯ : xₙ)` — is 1.5.6. `NumberField.absMulHeight_comp` generalizes their Proposition
1.5.17, which states the same invariance for an element of the absolute Galois group of `ℚ`.

This is Layer 0.4 of the `ArithmeticHeights` roadmap.
-/

public section

namespace NumberField

open Function IntermediateField Module

/-!
### The definition

The absolute height is computed over `IntermediateField.adjoin ℚ (Set.range x)`, the field the
coordinates generate, and normalized by the inverse of its degree.
-/

section Def

variable {K : Type*} [Field K] [CharZero K] {ι : Type*} [Finite ι]

/-- The field a tuple of algebraic numbers generates is a number field. Every proof below enters
through this; the definition itself repeats it inline, its exposed body being public. -/
private lemma numberField_adjoin_range {x : ι → K} (hx : ∀ i, IsIntegral ℚ (x i)) :
    NumberField (adjoin ℚ (Set.range x)) :=
  have : FiniteDimensional ℚ (adjoin ℚ (Set.range x)) :=
    finiteDimensional_adjoin fun y hy ↦ by obtain ⟨i, rfl⟩ := hy; exact hx i
  {}

open scoped Classical in
/-- The **absolute multiplicative height** of a tuple of algebraic numbers: the height relative to
the field the coordinates generate, taken to the power `1 / [ℚ(x₀, x₁, …) : ℚ]`. A tuple with a
coordinate that is not algebraic gets the junk value `1`.

This is the tuple analogue of Mathlib's `NumberField.absMulHeight₁`, which takes this route
through `ℚ⟮x⟯`; `absMulHeight_eq_absMulHeight₁` says the two agree where both apply. -/
@[expose] noncomputable def absMulHeight (x : ι → K) : ℝ :=
  if hx : ∀ i, IsIntegral ℚ (x i) then
    haveI : FiniteDimensional ℚ (adjoin ℚ (Set.range x)) :=
      finiteDimensional_adjoin fun y hy ↦ by obtain ⟨i, rfl⟩ := hy; exact hx i
    haveI : NumberField (adjoin ℚ (Set.range x)) := {}
    Height.mulHeight (fun i ↦ (⟨x i, subset_adjoin ℚ _ ⟨i, rfl⟩⟩ : adjoin ℚ (Set.range x)))
      ^ ((finrank ℚ (adjoin ℚ (Set.range x)) : ℝ))⁻¹
  else 1

/-- The **absolute logarithmic height** of a tuple of algebraic numbers. -/
@[expose] noncomputable def absLogHeight (x : ι → K) : ℝ := Real.log (absMulHeight x)

lemma absLogHeight_eq_log_absMulHeight (x : ι → K) :
    absLogHeight x = Real.log (absMulHeight x) :=
  rfl

/-- The definition, with the `NumberField` instance on the generated field taken from the context
instead of rebuilt; every proof below enters through this. -/
private lemma absMulHeight_def {x : ι → K} (hx : ∀ i, IsIntegral ℚ (x i))
    [NumberField (adjoin ℚ (Set.range x))] :
    absMulHeight x =
      Height.mulHeight (fun i ↦ (⟨x i, subset_adjoin ℚ _ ⟨i, rfl⟩⟩ : adjoin ℚ (Set.range x)))
        ^ ((finrank ℚ (adjoin ℚ (Set.range x)) : ℝ))⁻¹ := by
  rw [absMulHeight, dite_eq_left_of_eq_true (eq_true hx)]

open scoped Classical in
/-- The junk value: a tuple with a coordinate that is not algebraic has absolute height `1`. -/
lemma absMulHeight_eq_one_of_not_isIntegral {x : ι → K} (hx : ¬ ∀ i, IsIntegral ℚ (x i)) :
    absMulHeight x = 1 := by
  rw [absMulHeight, dite_eq_right_of_eq_false (eq_false hx)]

lemma absLogHeight_eq_zero_of_not_isIntegral {x : ι → K} (hx : ¬ ∀ i, IsIntegral ℚ (x i)) :
    absLogHeight x = 0 := by
  rw [absLogHeight, absMulHeight_eq_one_of_not_isIntegral hx, Real.log_one]

end Def

/-!
### Heights of isomorphic number fields

`NumberField.mulHeight_pow_finrank` at degree one: an isomorphism of number fields preserves the
relative height. This is the second ingredient of `absMulHeight_comp`, where the two fields
generated by a tuple and by its image are isomorphic but not equal.
-/

section RingEquiv

variable {K L : Type*} [Field K] [Field L] [NumberField K] [NumberField L] {ι : Type*} [Finite ι]

/-- The relative height is invariant under an isomorphism of number fields, being the degree-one
case of `NumberField.mulHeight_pow_finrank`. -/
theorem mulHeight_comp_ringEquiv (e : K ≃+* L) (x : ι → K) :
    Height.mulHeight (e ∘ x) = Height.mulHeight x := by
  let : Algebra K L := e.toRingHom.toAlgebra
  have hb : Function.Bijective (Algebra.linearMap K L) := e.bijective
  have h1 : finrank K L = 1 := by
    rw [← (LinearEquiv.ofBijective (Algebra.linearMap K L) hb).finrank_eq, finrank_self]
  simpa [h1, RingHom.algebraMap_toAlgebra] using (mulHeight_pow_finrank (K := K) (L := L) x).symm

end RingEquiv

/-!
### The field of definition does not matter

The two statements of the layer. Both come from `NumberField.mulHeight_pow_finrank`: passing from
`ℚ(x₀, x₁, …)` to a larger field raises the relative height to the degree of the step, which the
normalizing exponent divides out again.
-/

section FieldOfDefinition

variable {K : Type*} [Field K] [CharZero K] {ι : Type*} [Finite ι]

/-- The arithmetic behind the normalization: raising to the `n`-th power and normalizing by
`1 / (m * n)` is normalizing by `1 / m`. -/
private lemma rpow_inv_natCast_mul {a : ℝ} (ha : 0 ≤ a) {m n : ℕ} (hm : m ≠ 0) (hn : n ≠ 0) :
    (a ^ n) ^ (((m * n : ℕ) : ℝ))⁻¹ = a ^ ((m : ℝ))⁻¹ := by
  rw [← Real.rpow_natCast a n, ← Real.rpow_mul ha]
  congr 1
  have hm' : (m : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hm
  have hn' : (n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hn
  push_cast
  field_simp

/-- **The absolute height computed in a field of definition.** Any number field between
`ℚ(x₀, x₁, …)` and `K` gives the same value. -/
theorem absMulHeight_eq_of_mem {E : IntermediateField ℚ K} [NumberField E] {x : ι → K}
    (hx : ∀ i, x i ∈ E) :
    absMulHeight x = Height.mulHeight (fun i ↦ (⟨x i, hx i⟩ : E)) ^ ((finrank ℚ E : ℝ))⁻¹ := by
  have hint : ∀ i, IsIntegral ℚ (x i) := fun i ↦
    (Algebra.IsIntegral.isIntegral (⟨x i, hx i⟩ : E)).map E.val
  have hFE : adjoin ℚ (Set.range x) ≤ E := adjoin_le_iff.mpr (by rintro _ ⟨i, rfl⟩; exact hx i)
  have := numberField_adjoin_range hint
  let : Algebra (adjoin ℚ (Set.range x)) E := (inclusion hFE).toAlgebra
  have : IsScalarTower ℚ (adjoin ℚ (Set.range x)) E :=
    IsScalarTower.of_algebraMap_eq fun r ↦ ((inclusion hFE).commutes r).symm
  have : Module.Finite (adjoin ℚ (Set.range x)) E :=
    Module.Finite.of_restrictScalars_finite ℚ _ E
  have hcomp : (algebraMap (adjoin ℚ (Set.range x)) E) ∘
      (fun i ↦ (⟨x i, subset_adjoin ℚ _ ⟨i, rfl⟩⟩ : adjoin ℚ (Set.range x)))
      = fun i ↦ (⟨x i, hx i⟩ : E) := rfl
  rw [absMulHeight_def hint, ← hcomp, ← mulHeight_pow_finrank,
    ← Module.finrank_mul_finrank ℚ (adjoin ℚ (Set.range x)) E,
    rpow_inv_natCast_mul (Height.mulHeight_pos _).le
      (Module.finrank_pos (R := ℚ) (M := adjoin ℚ (Set.range x))).ne'
      (Module.finrank_pos (R := adjoin ℚ (Set.range x)) (M := E)).ne']

end FieldOfDefinition

section NumberFieldBase

variable {K : Type*} [Field K] [NumberField K] {ι : Type*} [Finite ι]

/-- **The absolute height over a number field is the relative height normalized by the degree.**
With `NumberField.mulHeight_pow_finrank`, this says that the absolute height does not depend on
the field the coordinates are read in. -/
theorem absMulHeight_eq (x : ι → K) :
    absMulHeight x = Height.mulHeight x ^ ((finrank ℚ K : ℝ))⁻¹ := by
  have hint : ∀ i, IsIntegral ℚ (x i) := fun i ↦ Algebra.IsIntegral.isIntegral _
  have := numberField_adjoin_range hint
  have : Module.Finite (adjoin ℚ (Set.range x)) K :=
    Module.Finite.of_restrictScalars_finite ℚ _ K
  have hcomp : (algebraMap (adjoin ℚ (Set.range x)) K) ∘
      (fun i ↦ (⟨x i, subset_adjoin ℚ _ ⟨i, rfl⟩⟩ : adjoin ℚ (Set.range x))) = x := rfl
  rw [absMulHeight_def hint]
  conv_rhs => rw [← hcomp]
  rw [← mulHeight_pow_finrank, ← Module.finrank_mul_finrank ℚ (adjoin ℚ (Set.range x)) K,
    rpow_inv_natCast_mul (Height.mulHeight_pos _).le
      (Module.finrank_pos (R := ℚ) (M := adjoin ℚ (Set.range x))).ne'
      (Module.finrank_pos (R := adjoin ℚ (Set.range x)) (M := K)).ne']

/-- The logarithmic form: the absolute logarithmic height is the relative one divided by the
degree. -/
theorem absLogHeight_eq (x : ι → K) :
    absLogHeight x = ((finrank ℚ K : ℝ))⁻¹ * Height.logHeight x := by
  rw [absLogHeight, absMulHeight_eq, Real.log_rpow (Height.mulHeight_pos x),
    Height.logHeight_eq_log_mulHeight]

end NumberFieldBase

/-!
### Invariance under an embedding

The absolute height is attached to the algebraic numbers themselves: an embedding of fields of
characteristic zero leaves it unchanged. This is what makes a value computed over `ℚ` readable
inside `ℝ` or `ℂ`, where `absMulHeight_eq` does not apply because the ambient field is not a
number field.
-/

section Comp

variable {K L : Type*} [Field K] [CharZero K] [Field L] [CharZero L] {ι : Type*} [Finite ι]

/-- **The absolute height is invariant under an embedding.** The height of `x` is a property of
the algebraic numbers `x i`, not of the field they are read in. -/
theorem absMulHeight_comp (f : K →ₐ[ℚ] L) (x : ι → K) :
    absMulHeight (f ∘ x) = absMulHeight x := by
  by_cases hx : ∀ i, IsIntegral ℚ (x i)
  · have hfx : ∀ i, IsIntegral ℚ ((f ∘ x) i) := fun i ↦ (hx i).map f
    have := numberField_adjoin_range hx
    have := numberField_adjoin_range hfx
    have hmap : (adjoin ℚ (Set.range x)).map f = adjoin ℚ (Set.range (f ∘ x)) := by
      rw [adjoin_map, Set.range_comp]
    let e : adjoin ℚ (Set.range x) ≃ₐ[ℚ] adjoin ℚ (Set.range (f ∘ x)) :=
      ((adjoin ℚ (Set.range x)).equivMap f).trans (equivOfEq hmap)
    have hcomp : (e.toRingEquiv : _ → _) ∘
        (fun i ↦ (⟨x i, subset_adjoin ℚ _ ⟨i, rfl⟩⟩ : adjoin ℚ (Set.range x)))
        = fun i ↦ (⟨(f ∘ x) i, subset_adjoin ℚ _ ⟨i, rfl⟩⟩ : adjoin ℚ (Set.range (f ∘ x))) := by
      funext i
      exact Subtype.ext rfl
    rw [absMulHeight_def hfx, absMulHeight_def hx, ← hcomp, mulHeight_comp_ringEquiv,
      e.toLinearEquiv.finrank_eq]
  · rw [absMulHeight_eq_one_of_not_isIntegral hx, absMulHeight_eq_one_of_not_isIntegral]
    intro h
    exact hx fun i ↦
      ((isAlgebraic_algHom_iff f f.injective).mp (h i).isAlgebraic).isIntegral

/-- The logarithmic form of `NumberField.absMulHeight_comp`. -/
theorem absLogHeight_comp (f : K →ₐ[ℚ] L) (x : ι → K) :
    absLogHeight (f ∘ x) = absLogHeight x :=
  congrArg Real.log (absMulHeight_comp f x)

end Comp

/-!
### The absolute Arakelov height is invariant under an embedding

The Arakelov normalization has no absolute form of its own in this development — it is written
`arakelovMulHeight x ^ (finrank ℚ K : ℝ)⁻¹` wherever it is needed — so the statement is that that
expression does not change along a homomorphism of number fields. It is
`NumberField.arakelovMulHeight_pow_finrank` of Layer 0.3 read through the degree, and it is what
lets a conjugate of a tuple be compared with the tuple itself.
-/

section ArakelovComp

variable {F L : Type*} [Field F] [NumberField F] [Field L] [NumberField L]
variable {κ : Type*} [Fintype κ]

/-- **The absolute Arakelov height is invariant under an embedding of number fields.** Every ring
homomorphism between fields of characteristic zero is a `ℚ`-algebra map, so no compatibility
hypothesis is needed; the degree of the extension it exhibits is exactly what the normalizing
exponent divides out. -/
theorem arakelovMulHeight_rpow_comp (f : F →+* L) (x : κ → F) :
    arakelovMulHeight (f ∘ x) ^ ((finrank ℚ L : ℝ))⁻¹
      = arakelovMulHeight x ^ ((finrank ℚ F : ℝ))⁻¹ := by
  let : Algebra F L := f.toAlgebra
  have : IsScalarTower ℚ F L :=
    IsScalarTower.of_algebraMap_eq' (Subsingleton.elim _ _)
  have : Module.Finite F L := Module.Finite.of_restrictScalars_finite ℚ F L
  have hmul : finrank ℚ F * finrank F L = finrank ℚ L := Module.finrank_mul_finrank ℚ F L
  have hkey : arakelovMulHeight x ^ finrank F L = arakelovMulHeight (f ∘ x) := by
    simpa [RingHom.algebraMap_toAlgebra] using
      arakelovMulHeight_pow_finrank (K := F) (L := L) x
  rw [← hkey, ← hmul, rpow_inv_natCast_mul (arakelovMulHeight_pos x).le
    (Module.finrank_pos (R := ℚ) (M := F)).ne' (Module.finrank_pos (R := F) (M := L)).ne']

end ArakelovComp

/-!
### Basic API, the affine case, and scaling
-/

section Basic

variable {K : Type*} [Field K] [CharZero K] {ι : Type*} [Finite ι]

lemma one_le_absMulHeight (x : ι → K) : 1 ≤ absMulHeight x := by
  by_cases hx : ∀ i, IsIntegral ℚ (x i)
  · have := numberField_adjoin_range hx
    rw [absMulHeight_def hx]
    exact Real.one_le_rpow (Height.one_le_mulHeight _) (by positivity)
  · rw [absMulHeight_eq_one_of_not_isIntegral hx]

lemma absMulHeight_pos (x : ι → K) : 0 < absMulHeight x :=
  zero_lt_one.trans_le <| one_le_absMulHeight x

lemma absMulHeight_ne_zero (x : ι → K) : absMulHeight x ≠ 0 :=
  (absMulHeight_pos x).ne'

lemma absLogHeight_nonneg (x : ι → K) : 0 ≤ absLogHeight x :=
  Real.log_nonneg <| one_le_absMulHeight x
/-- On a subsingleton index type every tuple has absolute height `1`: the height is computed in
the field the single coordinate generates, where `Height.mulHeight_eq_one_of_subsingleton` is the
product formula. -/
@[simp]
lemma absMulHeight_eq_one_of_subsingleton [Subsingleton ι] (x : ι → K) : absMulHeight x = 1 := by
  by_cases hx : ∀ i, IsIntegral ℚ (x i)
  · have := numberField_adjoin_range hx
    rw [absMulHeight_def hx, Height.mulHeight_eq_one_of_subsingleton, Real.one_rpow]
  · rw [absMulHeight_eq_one_of_not_isIntegral hx]

@[simp]
lemma absLogHeight_eq_zero_of_subsingleton [Subsingleton ι] (x : ι → K) : absLogHeight x = 0 := by
  simp [absLogHeight_eq_log_absMulHeight]

/-- **The absolute height does not increase under reindexing.** Dropping or repeating coordinates
of an algebraic tuple cannot raise its height; this is `Height.mulHeight_comp_le` read in the
field the coordinates generate.

⚠ The algebraicity hypothesis is not decorative. Without it the statement is false: if some
coordinate of `x` is transcendental then `absMulHeight x` is the junk value `1`, while `x ∘ f`
may omit that coordinate and have a larger height. -/
theorem absMulHeight_comp_le {ι' : Type*} [Finite ι'] (f : ι → ι') {x : ι' → K}
    (hx : ∀ i, IsIntegral ℚ (x i)) : absMulHeight (x ∘ f) ≤ absMulHeight x := by
  have := numberField_adjoin_range hx
  have hmem : ∀ i, x i ∈ adjoin ℚ (Set.range x) := fun i ↦ subset_adjoin ℚ _ ⟨i, rfl⟩
  rw [absMulHeight_eq_of_mem hmem, absMulHeight_eq_of_mem (x := x ∘ f) fun i ↦ hmem (f i)]
  exact Real.rpow_le_rpow (Height.mulHeight_pos _).le
    (Height.mulHeight_comp_le f fun i ↦ (⟨x i, hmem i⟩ : adjoin ℚ (Set.range x)))
    (by positivity)

/-- The logarithmic form of `NumberField.absMulHeight_comp_le`. -/
theorem absLogHeight_comp_le {ι' : Type*} [Finite ι'] (f : ι → ι') {x : ι' → K}
    (hx : ∀ i, IsIntegral ℚ (x i)) : absLogHeight (x ∘ f) ≤ absLogHeight x :=
  Real.log_le_log (absMulHeight_pos _) (absMulHeight_comp_le f hx)
/-- **The absolute height is invariant under re-indexing.** Unlike
`NumberField.absMulHeight_comp_le`, of which it is the two-sided form, this needs no algebraicity
hypothesis: an equivalence permutes the transcendental coordinates rather than dropping them, so
the two sides take the junk value together. -/
theorem absMulHeight_comp_equiv {ι' : Type*} [Finite ι'] (e : ι ≃ ι') (x : ι' → K) :
    absMulHeight (x ∘ e) = absMulHeight x := by
  by_cases hx : ∀ i, IsIntegral ℚ (x i)
  · refine le_antisymm (absMulHeight_comp_le e hx) ?_
    have hcomp : (x ∘ e) ∘ e.symm = x := by
      funext i
      simp
    simpa [hcomp] using absMulHeight_comp_le e.symm (x := x ∘ e) fun i ↦ hx (e i)
  · rw [absMulHeight_eq_one_of_not_isIntegral hx,
      absMulHeight_eq_one_of_not_isIntegral fun h ↦ hx fun i ↦ by simpa using h (e.symm i)]

/-- The logarithmic form of `NumberField.absMulHeight_comp_equiv`. -/
theorem absLogHeight_comp_equiv {ι' : Type*} [Finite ι'] (e : ι ≃ ι') (x : ι' → K) :
    absLogHeight (x ∘ e) = absLogHeight x :=
  congrArg Real.log (absMulHeight_comp_equiv e x)

/-- **The absolute height of a coordinatewise power.** Raising every coordinate of an algebraic
tuple to the `n`-th power raises the height to the `n`-th power. This is `Height.mulHeight_pow`
read in the field the coordinates generate, which the power does not enlarge, so the normalizing
exponent is the same on both sides. -/
theorem absMulHeight_pow {x : ι → K} (hx : ∀ i, IsIntegral ℚ (x i)) (n : ℕ) :
    absMulHeight (x ^ n) = absMulHeight x ^ n := by
  have hmem : ∀ i, x i ∈ adjoin ℚ (Set.range x) := fun i ↦ subset_adjoin ℚ _ ⟨i, rfl⟩
  have hmem' : ∀ i, (x ^ n) i ∈ adjoin ℚ (Set.range x) := fun i ↦ pow_mem (hmem i) n
  have := numberField_adjoin_range hx
  rw [absMulHeight_eq_of_mem hmem, absMulHeight_eq_of_mem hmem',
    show (fun i ↦ (⟨(x ^ n) i, hmem' i⟩ : adjoin ℚ (Set.range x)))
      = (fun i ↦ (⟨x i, hmem i⟩ : adjoin ℚ (Set.range x))) ^ n from funext fun i ↦ Subtype.ext rfl,
    Height.mulHeight_pow, Real.rpow_pow_comm (Height.mulHeight_pos _).le]

/-- The logarithmic form of `NumberField.absMulHeight_pow`. -/
theorem absLogHeight_pow {x : ι → K} (hx : ∀ i, IsIntegral ℚ (x i)) (n : ℕ) :
    absLogHeight (x ^ n) = n * absLogHeight x := by
  rw [absLogHeight, absMulHeight_pow hx, Real.log_pow, absLogHeight]

open scoped Classical in
/-- **The tuple definition extends Mathlib's one-variable one.** Both sides take the junk value
`1` when `x` is not algebraic. -/
theorem absMulHeight_eq_absMulHeight₁ (x : K) : absMulHeight ![x, 1] = absMulHeight₁ x := by
  by_cases hx : IsIntegral ℚ x
  · have : FiniteDimensional ℚ ℚ⟮x⟯ := adjoin.finiteDimensional hx
    have : NumberField ℚ⟮x⟯ := {}
    have hmem : ∀ i, (![x, 1] : Fin 2 → K) i ∈ ℚ⟮x⟯ := by
      intro i
      fin_cases i
      · exact mem_adjoin_simple_self ℚ x
      · exact one_mem _
    have heq : (fun i ↦ (⟨(![x, 1] : Fin 2 → K) i, hmem i⟩ : ℚ⟮x⟯))
        = ![AdjoinSimple.gen ℚ x, 1] := by
      funext i
      fin_cases i <;> exact Subtype.ext rfl
    rw [absMulHeight_eq_of_mem hmem, heq, absMulHeight₁, dite_eq_left_of_eq_true (eq_true hx),
      Height.mulHeight₁_eq_mulHeight]
  · have hne : ¬ ∀ i, IsIntegral ℚ ((![x, 1] : Fin 2 → K) i) := fun h ↦ hx (by simpa using h 0)
    rw [absMulHeight_eq_one_of_not_isIntegral hne, absMulHeight₁,
      dite_eq_right_of_eq_false (eq_false hx)]

/-- The logarithmic form of `NumberField.absMulHeight_eq_absMulHeight₁`. -/
theorem absLogHeight_eq_absLogHeight₁ (x : K) : absLogHeight ![x, 1] = absLogHeight₁ x :=
  congrArg Real.log (absMulHeight_eq_absMulHeight₁ x)

/-- Mathlib's absolute height of an element is at least `1`, the junk value included. -/
lemma one_le_absMulHeight₁ (x : K) : 1 ≤ absMulHeight₁ x :=
  absMulHeight_eq_absMulHeight₁ x ▸ one_le_absMulHeight ![x, 1]

/-- The logarithmic form of `NumberField.one_le_absMulHeight₁`. -/
lemma absLogHeight₁_nonneg (x : K) : 0 ≤ absLogHeight₁ x :=
  Real.log_nonneg (one_le_absMulHeight₁ x)

/-- **Mathlib's absolute height of a power**: the one-variable form of
`NumberField.absMulHeight_pow`. It is what makes the easy half of Kronecker's theorem immediate —
a root of unity has a power of height `1`, hence height `1`. -/
theorem absMulHeight₁_pow {x : K} (hx : IsIntegral ℚ x) (n : ℕ) :
    absMulHeight₁ (x ^ n) = absMulHeight₁ x ^ n := by
  rw [← absMulHeight_eq_absMulHeight₁, ← absMulHeight_eq_absMulHeight₁,
    show (![x ^ n, 1] : Fin 2 → K) = ![x, 1] ^ n from by funext i; fin_cases i <;> simp,
    absMulHeight_pow (fun i ↦ by fin_cases i; exacts [hx, isIntegral_one])]

/-- The logarithmic form of `NumberField.absMulHeight₁_pow`. -/
theorem absLogHeight₁_pow {x : K} (hx : IsIntegral ℚ x) (n : ℕ) :
    absLogHeight₁ (x ^ n) = n * absLogHeight₁ x := by
  rw [absLogHeight₁, absMulHeight₁_pow hx, Real.log_pow, absLogHeight₁]

/-- **Zero has absolute height `1`**, the value Mathlib's `Height.mulHeight₁_zero` gives for the
relative height. Both this and `NumberField.absMulHeight₁_one` come from `absMulHeight₁_pow`:
`0` and `1` are the idempotents of `K`, and a real number at least `1` that is its own square
is `1`. -/
lemma absMulHeight₁_zero : absMulHeight₁ (0 : K) = 1 := by
  have ha : (0 : ℝ) < absMulHeight₁ (0 : K) := zero_lt_one.trans_le (one_le_absMulHeight₁ _)
  have h := absMulHeight₁_pow (isIntegral_zero (R := ℚ) (B := K)) 2
  rw [zero_pow two_ne_zero, pow_two] at h
  exact (mul_left_cancel₀ ha.ne' ((mul_one _).trans h)).symm

/-- The logarithmic form of `NumberField.absMulHeight₁_zero`. -/
lemma absLogHeight₁_zero : absLogHeight₁ (0 : K) = 0 := by
  rw [absLogHeight₁, absMulHeight₁_zero, Real.log_one]

/-- **One has absolute height `1`**; see `NumberField.absMulHeight₁_zero`. -/
lemma absMulHeight₁_one : absMulHeight₁ (1 : K) = 1 := by
  have ha : (0 : ℝ) < absMulHeight₁ (1 : K) := zero_lt_one.trans_le (one_le_absMulHeight₁ _)
  have h := absMulHeight₁_pow (isIntegral_one (R := ℚ) (B := K)) 2
  rw [one_pow, pow_two] at h
  exact (mul_left_cancel₀ ha.ne' ((mul_one _).trans h)).symm

/-- The logarithmic form of `NumberField.absMulHeight₁_one`. -/
lemma absLogHeight₁_one : absLogHeight₁ (1 : K) = 0 := by
  rw [absLogHeight₁, absMulHeight₁_one, Real.log_one]

/-- **In an affine chart, every coordinate has absolute height at most that of the tuple.** A
tuple with a coordinate equal to `1` is the affine normalization of the projective point it
represents, and this is the bound its coordinates then satisfy.

It is the absolute counterpart of `Height.mulHeight₁_div_le_mulHeight`, and the one arithmetic
step in Northcott's theorem on projective space. -/
theorem absMulHeight₁_le_absMulHeight {x : ι → K} (hx : ∀ i, IsIntegral ℚ (x i)) {j : ι}
    (hj : x j = 1) (i : ι) : absMulHeight₁ (x i) ≤ absMulHeight x := by
  rw [← absMulHeight_eq_absMulHeight₁, show ![x i, 1] = x ∘ ![i, j] from by
    funext k; fin_cases k <;> simp [hj]]
  exact absMulHeight_comp_le _ hx

/-- The logarithmic form of `NumberField.absMulHeight₁_le_absMulHeight`. -/
theorem absLogHeight₁_le_absLogHeight {x : ι → K} (hx : ∀ i, IsIntegral ℚ (x i)) {j : ι}
    (hj : x j = 1) (i : ι) : absLogHeight₁ (x i) ≤ absLogHeight x :=
  Real.log_le_log (zero_lt_one.trans_le (one_le_absMulHeight₁ (x i)))
    (absMulHeight₁_le_absMulHeight hx hj i)

/-- **Mathlib's absolute height of an element is invariant under an embedding.** This is the
one-variable form of `NumberField.absMulHeight_comp`, obtained from it through
`absMulHeight_eq_absMulHeight₁`; it is the statement that an algebraic number and each of its
conjugates have the same absolute height. -/
theorem absMulHeight₁_comp {L : Type*} [Field L] [CharZero L] (f : K →ₐ[ℚ] L) (x : K) :
    absMulHeight₁ (f x) = absMulHeight₁ x := by
  rw [← absMulHeight_eq_absMulHeight₁, ← absMulHeight_eq_absMulHeight₁,
    show ![f x, 1] = ⇑f ∘ ![x, 1] from by funext i; fin_cases i <;> simp, absMulHeight_comp]

/-- The logarithmic form of `NumberField.absMulHeight₁_comp`. -/
theorem absLogHeight₁_comp {L : Type*} [Field L] [CharZero L] (f : K →ₐ[ℚ] L) (x : K) :
    absLogHeight₁ (f x) = absLogHeight₁ x :=
  congrArg Real.log (absMulHeight₁_comp f x)

/-- **Scaling invariance, for an algebraic scalar.** ⚠ The algebraicity hypothesis is not
decorative: for `c` transcendental and `x` a nonzero algebraic tuple, `c • x` has a transcendental
coordinate and `absMulHeight (c • x)` is the junk value `1`. See the examples at the end of the
file. -/
theorem absMulHeight_smul_eq (x : ι → K) {c : K} (hc : c ≠ 0) (hc' : IsAlgebraic ℚ c) :
    absMulHeight (c • x) = absMulHeight x := by
  by_cases hx : ∀ i, IsIntegral ℚ (x i)
  · have hfin : (insert c (Set.range x)).Finite := (Set.finite_range x).insert c
    have := hfin.to_subtype
    have hfd : FiniteDimensional ℚ (adjoin ℚ (insert c (Set.range x))) :=
      finiteDimensional_adjoin fun y hy ↦ by
        rcases hy with rfl | ⟨i, rfl⟩
        · exact hc'.isIntegral
        · exact hx i
    have : NumberField (adjoin ℚ (insert c (Set.range x))) := {}
    have hcE : c ∈ adjoin ℚ (insert c (Set.range x)) := subset_adjoin ℚ _ (Set.mem_insert _ _)
    have hxE : ∀ i, x i ∈ adjoin ℚ (insert c (Set.range x)) := fun i ↦
      subset_adjoin ℚ _ (Set.mem_insert_of_mem _ ⟨i, rfl⟩)
    have hcxE : ∀ i, (c • x) i ∈ adjoin ℚ (insert c (Set.range x)) := fun i ↦ mul_mem hcE (hxE i)
    have hsmul : (fun i ↦ (⟨(c • x) i, hcxE i⟩ : adjoin ℚ (insert c (Set.range x))))
        = (⟨c, hcE⟩ : adjoin ℚ (insert c (Set.range x))) •
          fun i ↦ (⟨x i, hxE i⟩ : adjoin ℚ (insert c (Set.range x))) := by
      funext i
      exact Subtype.ext rfl
    rw [absMulHeight_eq_of_mem hcxE, absMulHeight_eq_of_mem hxE, hsmul,
      Height.mulHeight_smul_eq_mulHeight _ (fun h ↦ hc (congrArg Subtype.val h))]
  · rw [absMulHeight_eq_one_of_not_isIntegral hx, absMulHeight_eq_one_of_not_isIntegral]
    intro h
    refine hx fun i ↦ ?_
    have hxi : x i = c⁻¹ * (c * x i) := by field_simp
    rw [hxi]
    exact hc'.inv.isIntegral.mul (h i)

/-- The logarithmic form of `NumberField.absMulHeight_smul_eq`. -/
theorem absLogHeight_smul_eq (x : ι → K) {c : K} (hc : c ≠ 0) (hc' : IsAlgebraic ℚ c) :
    absLogHeight (c • x) = absLogHeight x :=
  congrArg Real.log (absMulHeight_smul_eq x hc hc')

end Basic

end NumberField

/-!
### The descent to projective space

Scaling invariance makes the absolute height a well-defined function on
`Projectivization K (ι → K)` — but only over a field all of whose elements are algebraic, since
that is where `NumberField.absMulHeight_smul_eq` applies to every scalar.
-/

namespace Projectivization

open NumberField Real

variable {K : Type*} [Field K] [CharZero K] [Algebra.IsAlgebraic ℚ K] {ι : Type*} [Finite ι]

private lemma absMulHeight_aux (a b : { v : ι → K // v ≠ 0 }) (t : K) (h : a.val = t • b.val) :
    NumberField.absMulHeight a.val = NumberField.absMulHeight b.val :=
  have ht : t ≠ 0 := by
    contrapose! h
    simpa [h] using a.prop
  h ▸ absMulHeight_smul_eq _ ht (Algebra.IsAlgebraic.isAlgebraic t)

private lemma absLogHeight_aux (a b : { v : ι → K // v ≠ 0 }) (t : K) (h : a.val = t • b.val) :
    NumberField.absLogHeight a.val = NumberField.absLogHeight b.val := by
  simp only [absLogHeight_eq_log_absMulHeight, absMulHeight_aux a b t h]

-- We do not expose the bodies of these definitions so that we can keep the "_aux" lemmas
-- above private.

/-- The absolute multiplicative height of a point of projective space over a field of algebraic
numbers. -/
noncomputable def absMulHeight (x : Projectivization K (ι → K)) : ℝ :=
  x.lift (fun r ↦ NumberField.absMulHeight r.val) absMulHeight_aux

/-- The absolute logarithmic height of a point of projective space over a field of algebraic
numbers. -/
noncomputable def absLogHeight (x : Projectivization K (ι → K)) : ℝ :=
  x.lift (fun r ↦ NumberField.absLogHeight r.val) absLogHeight_aux

lemma absMulHeight_mk {x : ι → K} (hx : x ≠ 0) :
    absMulHeight (mk K x hx) = NumberField.absMulHeight x := by
  rfl

lemma absLogHeight_mk {x : ι → K} (hx : x ≠ 0) :
    absLogHeight (mk K x hx) = NumberField.absLogHeight x := by
  rfl

lemma absLogHeight_eq_log_absMulHeight (x : Projectivization K (ι → K)) :
    absLogHeight x = log (absMulHeight x) := by
  rw [← x.mk_rep, absMulHeight_mk, absLogHeight_mk,
    NumberField.absLogHeight_eq_log_absMulHeight]

lemma one_le_absMulHeight (x : Projectivization K (ι → K)) : 1 ≤ absMulHeight x := by
  rw [← x.mk_rep, absMulHeight_mk]
  exact NumberField.one_le_absMulHeight _

lemma absMulHeight_pos (x : Projectivization K (ι → K)) : 0 < absMulHeight x :=
  zero_lt_one.trans_le <| one_le_absMulHeight x

lemma absMulHeight_ne_zero (x : Projectivization K (ι → K)) : absMulHeight x ≠ 0 :=
  (absMulHeight_pos x).ne'

lemma absLogHeight_nonneg (x : Projectivization K (ι → K)) : 0 ≤ absLogHeight x := by
  rw [absLogHeight_eq_log_absMulHeight]
  exact log_nonneg x.one_le_absMulHeight
/-- On a subsingleton index type every point of projective space has absolute height `1`;
the projective form of `NumberField.absMulHeight_eq_one_of_subsingleton`. -/
@[simp]
lemma absMulHeight_eq_one_of_subsingleton [Subsingleton ι] (x : Projectivization K (ι → K)) :
    absMulHeight x = 1 := by
  rw [← x.mk_rep, absMulHeight_mk]
  exact NumberField.absMulHeight_eq_one_of_subsingleton _

@[simp]
lemma absLogHeight_eq_zero_of_subsingleton [Subsingleton ι] (x : Projectivization K (ι → K)) :
    absLogHeight x = 0 := by
  simp [absLogHeight_eq_log_absMulHeight]

/-- Over a number field the projective absolute height is the projective relative height
normalized by the degree, as it is for tuples. -/
lemma absMulHeight_eq [NumberField K] (x : Projectivization K (ι → K)) :
    absMulHeight x = Projectivization.mulHeight x ^ ((Module.finrank ℚ K : ℝ))⁻¹ := by
  rw [← x.mk_rep, absMulHeight_mk, mulHeight_mk, NumberField.absMulHeight_eq]

end Projectivization

/-!
### `positivity` extensions

The absolute heights are positive (multiplicative) resp. nonnegative (logarithmic), exactly as
their relative counterparts in `Mathlib.NumberTheory.Height.Basic`.
-/

namespace Mathlib.Meta.Positivity

open Lean.Meta Qq

/-- Extension for the `positivity` tactic: `NumberField.absMulHeight` is always positive. -/
@[positivity NumberField.absMulHeight _]
meta def evalAbsMulHeight : PositivityExt where eval {u α} _ pα? e :=
  match pα? with | none => pure .none | some _ => do
  match u, α, e with
  | 0, ~q(ℝ), ~q(@NumberField.absMulHeight $K $KF $KCZ $ι $ιF $a) =>
    assertInstancesCommute
    pure (.positive q(NumberField.absMulHeight_pos $a))
  | _, _, _ => throwError "not NumberField.absMulHeight"

/-- Extension for the `positivity` tactic: `NumberField.absLogHeight` is always nonnegative. -/
@[positivity NumberField.absLogHeight _]
meta def evalAbsLogHeight : PositivityExt where eval {u α} _ pα? e :=
  match pα? with | none => pure .none | some _ => do
  match u, α, e with
  | 0, ~q(ℝ), ~q(@NumberField.absLogHeight $K $KF $KCZ $ι $ιF $a) =>
    assertInstancesCommute
    pure (.nonnegative q(NumberField.absLogHeight_nonneg $a))
  | _, _, _ => throwError "not NumberField.absLogHeight"

/-- Extension for the `positivity` tactic: `Projectivization.absMulHeight` is always positive. -/
@[positivity Projectivization.absMulHeight _]
meta def evalProjAbsMulHeight : PositivityExt where eval {u α} _ pα? e :=
  match pα? with | none => pure .none | some _ => do
  match u, α, e with
  | 0, ~q(ℝ), ~q(@Projectivization.absMulHeight $K $KF $KCZ $KA $ι $ιF $a) =>
    assertInstancesCommute
    pure (.positive q(Projectivization.absMulHeight_pos $a))
  | _, _, _ => throwError "not Projectivization.absMulHeight"

/-- Extension for the `positivity` tactic: `Projectivization.absLogHeight` is always
nonnegative. -/
@[positivity Projectivization.absLogHeight _]
meta def evalProjAbsLogHeight : PositivityExt where eval {u α} _ pα? e :=
  match pα? with | none => pure .none | some _ => do
  match u, α, e with
  | 0, ~q(ℝ), ~q(@Projectivization.absLogHeight $K $KF $KCZ $KA $ι $ιF $a) =>
    assertInstancesCommute
    pure (.nonnegative q(Projectivization.absLogHeight_nonneg $a))
  | _, _, _ => throwError "not Projectivization.absLogHeight"

end Mathlib.Meta.Positivity

/-!
### Worked examples

The layer's acceptance test is that one number has one absolute height, whichever field it is
read in; the rejection test is that the scaling invariance really does need its algebraicity
hypothesis.
-/

namespace NumberField

section Examples

open Function IntermediateField Module

/-- Over `ℚ` the absolute height is the relative one, the degree being `1`. The values below
consume it. -/
private lemma absMulHeight_rat {ι : Type*} [Finite ι] (x : ι → ℚ) :
    absMulHeight x = Height.mulHeight x := by
  rw [absMulHeight_eq, Module.finrank_self, Nat.cast_one, inv_one, Real.rpow_one]

/-- `H(3/4) = 4`, from Mathlib's `Rat.mulHeight₁_eq_max`. A definition that does not give `4` here
has the numerator and the denominator confused. -/
private lemma absMulHeight_fin_two_rat : absMulHeight ![(3 / 4 : ℚ), 1] = 4 := by
  rw [absMulHeight_rat, ← Height.mulHeight₁_eq_mulHeight, Rat.mulHeight₁_eq_max]
  norm_num

/-- **Acceptance test.** The same rational tuple has the same absolute height over `ℚ` and over
any number field containing it: this is Layer 0.3's `mulHeight_pow_finrank` and the normalizing
exponent cancelling. -/
example {K : Type*} [Field K] [NumberField K] {ι : Type*} [Finite ι] (x : ι → ℚ) :
    absMulHeight (algebraMap ℚ K ∘ x) = absMulHeight x :=
  absMulHeight_comp (Algebra.ofId ℚ K) x

/-- The same number in `ℝ`, where `absMulHeight_eq` does not apply because `ℝ` is not a number
field: `absMulHeight_comp` is what carries the value across. The rejection test below consumes it
as a value. -/
private lemma absMulHeight_fin_two_real : absMulHeight ![(3 / 4 : ℝ), 1] = 4 := by
  rw [show ![(3 / 4 : ℝ), 1] = ⇑(Algebra.ofId ℚ ℝ) ∘ ![(3 / 4 : ℚ), 1] from by
    funext i
    fin_cases i <;> simp, absMulHeight_comp, absMulHeight_fin_two_rat]

/-- **Rejection test.** Scaling invariance fails for a transcendental scalar: `c • ![3/4, 1]` has
transcendental coordinates, so its absolute height is the junk value `1`, while the height of
`![3/4, 1]` is `4`. A statement of `absMulHeight_smul_eq` without the algebraicity hypothesis is
refuted here, and with it the descent to `Projectivization K (ι → K)` over a general field of
characteristic zero. -/
example {c : ℝ} (hc : Transcendental ℚ c) :
    absMulHeight (c • ![(3 / 4 : ℝ), 1]) ≠ absMulHeight ![(3 / 4 : ℝ), 1] := by
  have hjunk : absMulHeight (c • ![(3 / 4 : ℝ), 1]) = 1 := by
    refine absMulHeight_eq_one_of_not_isIntegral fun h ↦ hc ?_
    have h1 : IsIntegral ℚ (c * 1) := h 1
    rw [mul_one] at h1
    exact h1.isAlgebraic
  rw [hjunk, absMulHeight_fin_two_real]
  norm_num

end Examples

end NumberField

end
