/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import Mathlib.NumberTheory.NumberField.ProductFormula
public import Mathlib.RingTheory.Ideal.Norm.AbsNorm

/-!
# The finite part of a height is the inverse norm of an ideal

For a tuple `x` of algebraic integers of a number field `K`, not all zero,

```text
∏ᶠ_{v ∤ ∞} ⨆ i, v (x i)  =  (N 𝔞)⁻¹,   𝔞 = the ideal generated by the x i.
```

This is the tuple form of Mathlib's `NumberField.FinitePlace.prod_eq_inv_abs_norm_int`, which is
the case of a single generator, and it is what turns the finite local factor of a height into an
ideal-theoretic invariant. In the covolume identity of Layer 4.3 it is the whole finite half: the
covolume of the lattice of integral points of a subspace acquires the index of a free sublattice,
and that index is the norm of the ideal generated by the Plücker coordinates.

## Main results

* `NumberField.FinitePlace.finprod_iSup_eq_inv_absNorm`: the display above.
* `NumberField.FinitePlace.apply_le_one`: an algebraic integer has all finite absolute values at
  most `1`. Mathlib has this as `FinitePlace.norm_le_one`, stated for the embedding into the
  completion rather than for the place.

## Implementation notes

Over `ℚ` the same statement is `Rat.iSup_finitePlace_apply_eq_one_of_gcd_eq_one`: a coprime tuple
has *every* finite factor equal to `1`, because `ℤ` is a principal ideal domain and the ideal
generated by a coprime tuple is the unit ideal. Over a number field the ideal need not be
principal, and the content of the proof is exactly that the local factor at `v` reads the
`𝔭`-multiplicity of the ideal rather than of any one generator: with `i₀` an index at which the
supremum is attained, `𝔭`-multiplicity of the ideal equals that of `span {x i₀}`, because the
tuple's entries all lie in `𝔭 ^ e` precisely when their absolute values are at most `v (x i₀)`.

## References

E. Bombieri and W. Gubler, *Heights in Diophantine Geometry*, Cambridge University Press (2006),
§1.4 and §1.5, where the finite local factors of a height are described by the fractional ideal
generated by the coordinates.

This is Layer 4.3 of the `ArithmeticHeights` roadmap, the finite half of the number-field case.
-/

public section

open Ideal IsDedekindDomain

namespace NumberField.FinitePlace

variable {K : Type*} [Field K] [NumberField K] {σ : Type*} [Finite σ]

private theorem one_lt_absNorm_real (v : FinitePlace K) :
    (1 : ℝ) < (absNorm v.maximalIdeal.asIdeal : ℝ) := by
  exact_mod_cast HeightOneSpectrum.one_lt_absNorm v.maximalIdeal

private theorem apply_eq_inv_pow (v : FinitePlace K) {x : 𝓞 K} (hx : x ≠ 0) :
    v (x : K) = (((absNorm v.maximalIdeal.asIdeal : ℝ))
      ^ (multiplicity v.maximalIdeal.asIdeal (span {x})))⁻¹ :=
  eq_inv_of_mul_eq_one_left (FinitePlace.apply_mul_absNorm_pow_eq_one v hx)

/-- **An algebraic integer has finite absolute values at most `1`.** -/
theorem apply_le_one (v : FinitePlace K) (z : 𝓞 K) : v ((z : K)) ≤ 1 := by
  rcases eq_or_ne z 0 with h | h
  · simp [h]
  · rw [apply_eq_inv_pow v h,
      inv_le_one₀ (pow_pos (lt_trans zero_lt_one (one_lt_absNorm_real v)) _)]
    exact one_le_pow₀ (one_lt_absNorm_real v).le

omit [Finite σ] in
private theorem mem_pow_of_le (v : FinitePlace K) {x y : 𝓞 K} (hx : x ≠ 0) (hy : y ≠ 0)
    (h : v ((x : K)) ≤ v ((y : K))) :
    x ∈ v.maximalIdeal.asIdeal ^ (multiplicity v.maximalIdeal.asIdeal (span {y})) := by
  set 𝔭 := v.maximalIdeal.asIdeal
  set n := multiplicity 𝔭 (span {y})
  set m := multiplicity 𝔭 (span {x})
  have hN := one_lt_absNorm_real v
  rw [apply_eq_inv_pow v hx, apply_eq_inv_pow v hy] at h
  have hnm : n ≤ m := by
    have h2 : ((absNorm 𝔭 : ℝ)) ^ n ≤ ((absNorm 𝔭 : ℝ)) ^ m := by
      have hp : (0 : ℝ) < ((absNorm 𝔭 : ℝ)) ^ n := by positivity
      have hq : (0 : ℝ) < ((absNorm 𝔭 : ℝ)) ^ m := by positivity
      rwa [inv_le_inv₀ hq hp] at h
    exact (pow_le_pow_iff_right₀ hN).1 h2
  have hdvd : 𝔭 ^ n ∣ span {x} := dvd_trans (pow_dvd_pow _ hnm) (pow_multiplicity_dvd _ _)
  exact (Ideal.span_singleton_le_iff_mem _).1 (Ideal.dvd_iff_le.1 hdvd)

omit [Finite σ] in
/-- At a finite place, the multiplicity of `𝔭` in the ideal generated by a tuple is its
multiplicity in the entry at which the supremum of the local absolute values is attained. -/
private theorem multiplicity_span_range (v : FinitePlace K) {x : σ → 𝓞 K} {i₀ : σ}
    (hi₀ : x i₀ ≠ 0) (hmax : ∀ i, v ((x i : K)) ≤ v ((x i₀ : K))) :
    multiplicity v.maximalIdeal.asIdeal (span (Set.range x))
      = multiplicity v.maximalIdeal.asIdeal (span {x i₀}) := by
  set 𝔭 := v.maximalIdeal.asIdeal with h𝔭
  have hprime : Prime 𝔭 := v.maximalIdeal.prime
  have hI0 : span (Set.range x) ≠ (⊥ : Ideal (𝓞 K)) := fun h ↦
    hi₀ (by simpa using (Ideal.span_eq_bot.1 h) (x i₀) ⟨i₀, rfl⟩)
  have hs0 : span {x i₀} ≠ (⊥ : Ideal (𝓞 K)) := by
    simpa using mt Ideal.span_singleton_eq_bot.mp hi₀
  have hfI : FiniteMultiplicity 𝔭 (span (Set.range x)) :=
    FiniteMultiplicity.of_prime_left hprime hI0
  have hf0 : FiniteMultiplicity 𝔭 (span {x i₀}) := FiniteMultiplicity.of_prime_left hprime hs0
  refine le_antisymm (hf0.pow_dvd_iff_le_multiplicity.1 ?_) (hfI.pow_dvd_iff_le_multiplicity.1 ?_)
  · exact dvd_trans (pow_multiplicity_dvd _ _) (Ideal.dvd_iff_le.2
      (Ideal.span_le.2 (Set.singleton_subset_iff.2 (Ideal.subset_span ⟨i₀, rfl⟩))))
  · refine Ideal.dvd_iff_le.2 (Ideal.span_le.2 ?_)
    rintro _ ⟨i, rfl⟩
    rcases eq_or_ne (x i) 0 with h | h
    · simp [h]
    · exact mem_pow_of_le v h hi₀ (hmax i)

private theorem iSup_mul_absNorm_pow_eq_one (v : FinitePlace K) {x : σ → 𝓞 K}
    (hx : ∃ i, x i ≠ 0) :
    (⨆ i, v ((x i : K))) * ((absNorm v.maximalIdeal.asIdeal : ℝ)
      ^ (multiplicity v.maximalIdeal.asIdeal (span (Set.range x)))) = 1 := by
  have : Nonempty σ := ⟨hx.choose⟩
  obtain ⟨i₀, hmax⟩ := Finite.exists_max (fun i ↦ v ((x i : K)))
  have hi₀ : x i₀ ≠ 0 := by
    obtain ⟨j, hj⟩ := hx
    intro h
    have hle : v ((x j : K)) ≤ v ((x i₀ : K)) := hmax j
    rw [h] at hle
    have hpos : 0 < v ((x j : K)) := FinitePlace.pos_iff.2 (by simpa using hj)
    simp only [map_zero] at hle
    linarith
  have hsup : (⨆ i, v ((x i : K))) = v ((x i₀ : K)) :=
    le_antisymm (ciSup_le hmax)
      (le_ciSup (f := fun i ↦ v ((x i : K))) (Finite.bddAbove_range _) i₀)
  rw [hsup, multiplicity_span_range v hi₀ hmax]
  exact FinitePlace.apply_mul_absNorm_pow_eq_one v hi₀

/-- **The finite part of a height is the inverse norm of the ideal generated by the tuple.** For a
tuple of algebraic integers, not all zero, the product over the finite places of the supremum of
the local absolute values is `(N 𝔞)⁻¹`, with `𝔞` the ideal they generate. -/
theorem finprod_iSup_eq_inv_absNorm {x : σ → 𝓞 K} (hx : ∃ i, x i ≠ 0) :
    ∏ᶠ v : FinitePlace K, (⨆ i, v ((x i : K))) = ((absNorm (span (Set.range x)) : ℝ))⁻¹ := by
  have : Nonempty σ := ⟨hx.choose⟩
  obtain ⟨i₁, hi₁⟩ := hx
  have hI : span (Set.range x) ≠ (⊥ : Ideal (𝓞 K)) := fun h ↦
    hi₁ (by simpa using (Ideal.span_eq_bot.1 h) (x i₁) ⟨i₁, rfl⟩)
  have h1 : (Function.mulSupport fun v : FinitePlace K ↦ ⨆ i, v ((x i : K))).Finite := by
    refine Set.Finite.subset (FinitePlace.hasFiniteMulSupport_int hi₁) ?_
    intro v hv
    simp only [Function.mem_mulSupport] at hv ⊢
    intro hcon
    exact hv (le_antisymm (ciSup_le fun i ↦ apply_le_one v (x i))
      (hcon ▸ le_ciSup (f := fun i ↦ v ((x i : K))) (Finite.bddAbove_range _) i₁))
  have h2 : (Function.mulSupport fun v : FinitePlace K ↦
      ((absNorm v.maximalIdeal.asIdeal : ℝ) ^
        multiplicity v.maximalIdeal.asIdeal (span (Set.range x)))).Finite :=
    FinitePlace.hasFiniteMulSupport_fun_pow_multiplicity hI (fun J ↦ ((absNorm J : ℝ)))
  refine eq_inv_of_mul_eq_one_left ?_
  have habs : ((absNorm (span (Set.range x)) : ℕ) : ℝ) = ∏ᶠ v : FinitePlace K,
      ((absNorm v.maximalIdeal.asIdeal : ℝ) ^
        multiplicity v.maximalIdeal.asIdeal (span (Set.range x))) := by
    have key := ((Nat.castRingHom ℝ).toMonoidHom.comp
        absNorm.toMonoidHom).map_finprod_of_preimage_one (by simp)
      (fun v : FinitePlace K ↦
        v.maximalIdeal.asIdeal ^ multiplicity v.maximalIdeal.asIdeal (span (Set.range x)))
    rw [FinitePlace.finprod_finitePlace_pow_multiplicity hI] at key
    simpa using key
  rw [habs, ← finprod_mul_distrib h1 h2]
  exact finprod_eq_one_of_forall_eq_one fun v ↦ iSup_mul_absNorm_pow_eq_one v ⟨i₁, hi₁⟩

end NumberField.FinitePlace

end
