/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import ArithmeticHeights.MixedLattice
public import ArithmeticHeights.PseudoBasis
public import ArithmeticHeights.FinitePlaceIdeal
public import ArithmeticHeights.GramCovolume
public import ArithmeticHeights.Subspace
public import Mathlib.NumberTheory.NumberField.Discriminant.Basic

/-!
# The lattice of integral points of a subspace of a number field

For a subspace `V ⊆ Kⁱ` of dimension `k` over a number field `K`, the integral points
`V ∩ (𝓞 K)ⁱ` form a lattice of rank `[K : ℚ] · k` in the real span of `V` inside the euclidean
mixed space of `ι`-tuples, and its covolume is

```text
covol (V ∩ (𝓞 K)ⁱ)  =  (2^{−r₂} |discr K|^{1/2}) ^ k · H_Ar(V)
                    =  2^{−r₂ k} · |discr K|^{k/2} · H_Ar(V),
```

with `H_Ar` the Arakelov subspace height of Layer 3.2 relative to `K` — so the *absolute* height
enters with the exponent `[K : ℚ]`. This is **W. M. Schmidt 1967, §3, Theorem 1**, and it is the
computation that converts the lattice statement of Minkowski's second theorem into a height
statement. Over `ℚ` every constant is `1` and the identity is
`Submodule.covolume_intLattice` of `ArithmeticHeights/RationalLattice.lean`.

## Main definitions

* `NumberField.integralTuples`: the tuples of algebraic integers, inside `Kⁱ`.
* `Submodule.integerPoints`: the integral points `V ∩ (𝓞 K)ⁱ` of a subspace, an `𝓞 K`-submodule.
* `NumberField.mixedPiEmb`: the embedding of `Kⁱ` into the euclidean mixed space of tuples.
* `Submodule.mixedSpan`: the real span of `V` there.
* `Submodule.mixedLattice`: the integral points read inside that span — the object whose covolume
  the milestone computes.

## Main results

* `Submodule.covolume_mixedLattice`: the covolume identity displayed above.
* `Submodule.prod_mul_plucker_eq_one`: **primitivity** — for a pseudo-basis `(𝔞ᵢ, yᵢ)` of the
  integral points, `(∏ᵢ 𝔞ᵢ) · (p) = 𝓞 K`, with `(p)` the ideal generated by the Plücker
  coordinates of `y`. This is the finite half, and the only place saturation is used.
* `Submodule.exists_pseudoBasis_integerPoints`: the integral points have a pseudo-basis whose
  vectors are themselves integral points, so that the Plücker coordinates are integral.
* `NumberField.exists_idealBasis`: a nonzero fractional ideal is a lattice of covolume
  `N(𝔞) · 2^{−r₂} |discr K|^{1/2}` in the euclidean mixed space, with a `ℤ`-basis indexed by
  `Fin [K : ℚ]`.
* `NumberField.det_gram_pi`: the Gram determinant of a basis of `(K ⊗ ℝ)^k` assembled from bases of
  the factors is the product of theirs — the euclidean space of `k`-tuples is an orthogonal sum.
* `Submodule.finrank_mixedSpan`: the real span has dimension `[K : ℚ] · dim V`, and the
  `DiscreteTopology` and `IsZLattice` instances that make the covolume meaningful.

## Implementation notes

⚠ **Schmidt's Lemmas 5 and 6 — the local counting behind `[σ(Λ) : Λ₀] = N(𝔞)` — are not needed.**
They exist in his proof to compare the possibly non-free module `Λ = V ∩ (𝓞 K)ⁱ` with the free
`Λ₀ = ⊕ 𝓞 K yᵢ` generated by a `K`-basis inside it. A **pseudo-basis** `Λ = ⊕ 𝔞ᵢ yᵢ` removes the
comparison: the covolume of `⊕ 𝔞ᵢ` is `∏ᵢ N(𝔞ᵢ)` times that of `(𝓞 K)^k` by an orthogonal
block-diagonal Gram determinant, and what remains of the finite half is the single statement
`(∏ᵢ 𝔞ᵢ) · (p) = 𝓞 K`. No index of lattices is ever computed.

⚠ **Primitivity needs no localization and no uniformizer.** Suppose the Plücker ideal `𝔠` were
contained in a maximal `𝔮`. Choose `aᵢ ∈ 𝔞ᵢ ∖ 𝔮𝔞ᵢ`; then all the maximal minors of the integral
family `aᵢ yᵢ` lie in `𝔮`, so their reductions are dependent over the residue field —
`exteriorPower.plucker_eq_zero_iff` of Layer 3.1 read over `𝓞 K ⧸ 𝔮` — and some combination
`u = ∑ cᵢ aᵢ yᵢ` has all coordinates in `𝔮`. Multiplying `u` by any `t ∈ 𝔮⁻¹` therefore lands in
`(𝓞 K)ⁱ`, hence in `V ∩ (𝓞 K)ⁱ` by **saturation**; reading off coefficients gives
`𝔮⁻¹ cᵢaᵢ ⊆ 𝔞ᵢ`, so `cᵢaᵢ ∈ 𝔮𝔞ᵢ` and `cᵢ ∈ 𝔮` for every `i` — a contradiction. The only
arithmetic used is `𝔮 𝔮⁻¹ = 𝓞 K`. Over `ℚ` this argument degenerates to the division by a prime
`q` of `Submodule.gcd_plucker_eq_one`.

⚠ **The integrality of the Plücker point is a normalization of the pseudo-basis, not a lemma.**
Scaling `yᵢ` by a nonzero `a ∈ 𝔞ᵢ` and `𝔞ᵢ` by `a⁻¹` changes neither the module nor the span and
puts every `yᵢ` inside `V ∩ (𝓞 K)ⁱ`; the minors are then algebraic integers, which is what lets
the finite places read them through `NumberField.FinitePlace.finprod_iSup_eq_inv_absNorm`.

⚠ **Instances are declared, not searched.** `MeasureSpace`, `BorelSpace`, `FiniteDimensional` and
`IsAddHaarMeasure` for the real span are given once each; the nested `WithLp` structure of the
mixed space otherwise makes every use site re-derive them and exceed the heartbeat budget.

## References

W. M. Schmidt, "On heights of algebraic subspaces and diophantine approximations", *Annals of
Mathematics* **85** (1967), 430–472, §3, Theorem 1 (`H'(S) = H(S)`), whose normalization this is:
his `ρ` is the `(Re, Im)` embedding and his `Δ = 2^{−r₂} |𝔡|^{1/2}` the covolume of `𝓞 K`.

J. L. Thunder, "An adelic Minkowski–Hlawka theorem and an application to Siegel's lemma",
*Journal für die reine und angewandte Mathematik* **475** (1996), 167–185, and
"Siegel's lemma for function fields", where the same identity is stated in a conjugate-pairs
embedding, which is why no `2^{−r₂}` appears there.

E. Steinitz, "Rechteckige Systeme und Moduln in algebraischen Zahlkörpern", *Mathematische
Annalen* **71** (1911), 328–354, for the pseudo-basis that replaces Schmidt's free sublattice.

This is Layer 4.3 of the `ArithmeticHeights` roadmap, over a number field.
-/

public section

noncomputable section

open Module NumberField NumberField.mixedEmbedding

variable {K : Type*} [Field K] [NumberField K] {ι : Type*}

/-- The tuples of algebraic integers, as an `𝓞 K`-submodule of `ι → K`. -/
@[expose] def NumberField.integralTuples (K : Type*) [Field K] (ι : Type*) :
    Submodule (𝓞 K) (ι → K) :=
  Submodule.pi Set.univ fun _ ↦ (1 : Submodule (𝓞 K) K)

omit [NumberField K] in
theorem NumberField.mem_integralTuples {x : ι → K} :
    x ∈ integralTuples K ι ↔ ∀ l, ∃ z : 𝓞 K, (z : K) = x l := by
  simp [integralTuples, Submodule.mem_pi, Submodule.one_eq_range]

/-- The **integral points** `V ∩ (𝓞 K)ⁱ` of a subspace of `Kⁱ`. -/
@[expose] def Submodule.integerPoints (V : Submodule K (ι → K)) : Submodule (𝓞 K) (ι → K) :=
  V.restrictScalars (𝓞 K) ⊓ integralTuples K ι

omit [NumberField K] in
theorem Submodule.mem_integerPoints {V : Submodule K (ι → K)} {x : ι → K} :
    x ∈ V.integerPoints ↔ x ∈ V ∧ ∀ l, ∃ z : 𝓞 K, (z : K) = x l := by
  rw [Submodule.integerPoints, Submodule.mem_inf, NumberField.mem_integralTuples]
  exact Iff.rfl

/-!
### The integral points are a finitely generated module spanning the subspace
-/

section Data

open scoped nonZeroDivisors

variable [Finite ι]

variable (K ι) in
/-- Entrywise inclusion of integral tuples. -/
@[expose] def NumberField.piIntCast : (ι → 𝓞 K) →ₗ[𝓞 K] (ι → K) :=
  LinearMap.pi fun l ↦ (Algebra.linearMap (𝓞 K) K).comp (LinearMap.proj l)

omit [Finite ι] [NumberField K] in
theorem NumberField.range_piIntCast :
    LinearMap.range (piIntCast K ι) = integralTuples K ι := by
  ext x
  rw [LinearMap.mem_range, NumberField.mem_integralTuples]
  constructor
  · rintro ⟨z, rfl⟩ l
    exact ⟨z l, rfl⟩
  · intro h
    choose z hz using h
    exact ⟨z, funext fun l ↦ hz l⟩

omit [NumberField K] in
theorem NumberField.fg_integralTuples : (integralTuples K ι).FG := by
  rw [← NumberField.range_piIntCast, LinearMap.range_eq_map]
  exact Submodule.FG.map _ (Module.Finite.fg_top)

theorem Submodule.fg_integerPoints (V : Submodule K (ι → K)) : V.integerPoints.FG := by
  have hle : V.integerPoints ≤ integralTuples K ι := inf_le_right
  have hN : IsNoetherian (𝓞 K) ↥(integralTuples K ι) :=
    isNoetherian_of_fg_of_noetherian _ NumberField.fg_integralTuples
  have h1 : (V.integerPoints.comap (integralTuples K ι).subtype).FG := IsNoetherian.noetherian _
  have h2 : V.integerPoints
      = Submodule.map (integralTuples K ι).subtype
          (V.integerPoints.comap (integralTuples K ι).subtype) :=
    (Submodule.map_comap_eq_self (by simpa using hle)).symm
  rw [h2]
  exact h1.map _

theorem Submodule.span_integerPoints (V : Submodule K (ι → K)) :
    Submodule.span K (V.integerPoints : Set (ι → K)) = V := by
  refine le_antisymm (Submodule.span_le.2 fun x hx ↦ hx.1) fun v hv ↦ ?_
  have : Fintype ι := Fintype.ofFinite ι
  obtain ⟨d, hd⟩ := IsLocalization.exist_integer_multiples (𝓞 K)⁰ (Finset.univ : Finset ι) v
  have hdv : ((d : 𝓞 K) : K) • v ∈ V.integerPoints := by
    refine ⟨V.smul_mem _ hv, NumberField.mem_integralTuples.2 fun l ↦ ?_⟩
    obtain ⟨z, hz⟩ := hd l (Finset.mem_univ l)
    exact ⟨z, by simpa [Algebra.smul_def] using hz⟩
  have hdK : ((d : 𝓞 K) : K) ≠ 0 := by
    simp [IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors (K := K) d.2]
  have : v = (((d : 𝓞 K) : K))⁻¹ • (((d : 𝓞 K) : K) • v) := by
    rw [inv_smul_smul₀ hdK]
  rw [this]
  exact Submodule.smul_mem _ _ (Submodule.subset_span hdv)

/-- **The pseudo-basis of the integral points of a subspace.** -/
theorem Submodule.exists_pseudoBasis_integerPoints (V : Submodule K (ι → K)) :
    ∃ (y : Fin (finrank K V) → (ι → K)) (𝔞 : Fin (finrank K V) → FractionalIdeal (𝓞 K)⁰ K),
      LinearIndependent K y ∧ (∀ i, 𝔞 i ≠ 0) ∧ (∀ i, y i ∈ V.integerPoints) ∧
      (∀ x, x ∈ V.integerPoints ↔
        ∃ c : Fin (finrank K V) → K, (∀ i, c i ∈ 𝔞 i) ∧ x = ∑ i, c i • y i) :=
  Submodule.exists_pseudoBasis_mem _ V.integerPoints V.fg_integerPoints
    (by rw [V.span_integerPoints])

end Data

section Defs

variable [Finite ι]

open scoped Classical in
/-- The embedding of `Kⁱ` into the euclidean mixed space of `ι`-tuples. -/
@[expose] def mixedPiEmb (K : Type*) [Field K] [NumberField K] (ι : Type*) :
    (ι → K) →ₗ[ℤ] mixedPi K ι :=
  (LinearMap.restrictScalars ℤ (toMixedPi K ι).toLinearMap) ∘ₗ
    AddMonoidHom.toIntLinearMap (AddMonoidHom.pi fun l ↦
      (mixedEmbedding K).toAddMonoidHom.comp (Pi.evalAddMonoidHom (fun _ : ι ↦ K) l))

omit [Finite ι] in
open scoped Classical in
@[simp] theorem mixedPiEmb_apply (x : ι → K) :
    mixedPiEmb K ι x = toMixedPi K ι (fun l ↦ mixedEmbedding K (x l)) := rfl

open scoped Classical in
/-- The **real span** of a subspace of `Kⁱ` in the euclidean mixed space of tuples. -/
@[expose] def Submodule.mixedSpan (V : Submodule K (ι → K)) : Submodule ℝ (mixedPi K ι) :=
  Submodule.span ℝ (mixedPiEmb K ι '' (V : Set (ι → K)))

open scoped Classical in
/-- The Borel structure on the real span of a subspace. Declaring it once keeps instance search
off the nested `WithLp` structure of the mixed space at every use site. -/
instance instBorelSpaceMixedSpan (V : Submodule K (ι → K)) :
    BorelSpace ↥V.mixedSpan :=
  Subtype.borelSpace _

open scoped Classical in
/-- The real span of a subspace is finite-dimensional. -/
instance instFiniteDimensionalMixedSpan (V : Submodule K (ι → K)) :
    FiniteDimensional ℝ ↥V.mixedSpan :=
  inferInstance

open scoped Classical in
/-- The **lattice of integral points** of a subspace, inside its real span: the object whose
covolume the milestone computes. -/
@[expose] def Submodule.mixedLattice (V : Submodule K (ι → K)) : Submodule ℤ ↥V.mixedSpan :=
  Submodule.comap ((V.mixedSpan.subtype).restrictScalars ℤ)
    (Submodule.map (mixedPiEmb K ι) (V.integerPoints.restrictScalars ℤ))

end Defs

variable [Fintype ι]

open scoped Classical in
/-- The euclidean measure on the real span of a subspace. Declaring it once keeps instance search
off the nested `WithLp` structure of the mixed space at every use site. -/
noncomputable instance instMeasureSpaceMixedSpan (V : Submodule K (ι → K)) :
    MeasureTheory.MeasureSpace ↥V.mixedSpan :=
  measureSpaceOfInnerProductSpace

open scoped Classical in
/-- The euclidean measure on the real span of a subspace is a Haar measure. -/
instance instIsAddHaarMeasureMixedSpan (V : Submodule K (ι → K)) :
    (MeasureTheory.volume : MeasureTheory.Measure ↥V.mixedSpan).IsAddHaarMeasure :=
  inferInstance

/-!
### The lattice of a fractional ideal in the euclidean mixed space
-/

section IdealBasis

open scoped nonZeroDivisors

open Real NumberField.InfinitePlace

open scoped Classical in
/-- **A fractional ideal is a lattice in the euclidean mixed space, with a known covolume.**
This is Mathlib's `fractionalIdealLatticeBasis` read in the euclidean mixed space and reindexed by
`Fin d`, `d = [K : ℚ]`, so that the `k` factors of a pseudo-basis can be assembled into one
`ℝ`-basis of the euclidean space of `k`-tuples. -/
theorem NumberField.exists_idealBasis (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
    ∃ (a : Fin (finrank ℚ K) → K) (b : Basis (Fin (finrank ℚ K)) ℝ (euclidean.mixedSpace K)),
      (∀ j, euclidean.toMixed K (b j) = mixedEmbedding K (a j)) ∧
      (∀ x : K, x ∈ Submodule.span ℤ (Set.range a) ↔ x ∈ (I : FractionalIdeal (𝓞 K)⁰ K)) ∧
      ZLattice.covolume (Submodule.span ℤ (Set.range b))
        = (FractionalIdeal.absNorm (I : FractionalIdeal (𝓞 K)⁰ K) : ℝ)
          * (2 : ℝ)⁻¹ ^ nrComplexPlaces K * √|NumberField.discr K| := by
  classical
  have hcard : Fintype.card (Module.Free.ChooseBasisIndex ℤ I) = finrank ℚ K := by
    rw [← Module.finrank_eq_card_chooseBasisIndex, fractionalIdeal_rank, RingOfIntegers.rank]
  set e := Fintype.equivFinOfCardEq hcard with he
  set b : Basis (Fin (finrank ℚ K)) ℝ (euclidean.mixedSpace K) :=
    ((fractionalIdealLatticeBasis K I).map (euclidean.toMixed K).symm.toLinearEquiv).reindex e
    with hb
  set φ : mixedSpace K →ₗ[ℤ] euclidean.mixedSpace K :=
    (euclidean.toMixed K).symm.toLinearMap.restrictScalars ℤ with hφ
  have hbj : ∀ j, b j = φ (fractionalIdealLatticeBasis K I (e.symm j)) := fun j ↦ by
    rw [hb]; simp [hφ]
  refine ⟨basisOfFractionalIdeal K I ∘ e.symm, b, fun j ↦ ?_, fun x ↦ ?_, ?_⟩
  · rw [hbj j]
    simp [hφ]
  · rw [show Set.range (basisOfFractionalIdeal K I ∘ e.symm)
        = Set.range (basisOfFractionalIdeal K I) by
      rw [Set.range_comp, e.symm.range_eq_univ, Set.image_univ]]
    exact mem_span_basisOfFractionalIdeal K
  · have hrange : Set.range b
        = (euclidean.toMixed K).symm '' Set.range (fractionalIdealLatticeBasis K I) := by
      rw [show (b : Fin (finrank ℚ K) → euclidean.mixedSpace K)
          = (fun x ↦ (euclidean.toMixed K).symm x) ∘ ((fractionalIdealLatticeBasis K I) ∘ e.symm)
          from funext hbj, Set.range_comp, Set.range_comp, e.symm.range_eq_univ, Set.image_univ]
    have hspan : Submodule.span ℤ (Set.range b)
        = ZLattice.comap ℝ (idealLattice K I) (euclidean.toMixed K).toLinearMap := by
      have hmap : Submodule.span ℤ (Set.range b)
          = Submodule.map φ
            (Submodule.span ℤ (Set.range (fractionalIdealLatticeBasis K I))) := by
        rw [← Submodule.span_image]
        exact congrArg (Submodule.span ℤ) hrange
      rw [hmap, span_idealLatticeBasis]
      ext x
      simp only [Submodule.mem_map, hφ, LinearMap.coe_restrictScalars,
        ZLattice.comap, Submodule.mem_comap]
      constructor
      · rintro ⟨y, hy, rfl⟩
        simpa using hy
      · intro h
        exact ⟨euclidean.toMixed K x, h, by simp⟩
    rw [hspan, ZLattice.covolume_comap _ _ _ (euclidean.volumePreserving_toMixed K),
      covolume_idealLattice]

end IdealBasis

/-!
### The Gram determinant of a product basis
-/

section Product

open Matrix

open scoped Classical in
/-- **The Gram determinant of a product basis is the product of the Gram determinants.** The
euclidean space of `k`-tuples is the orthogonal sum of `k` copies of the euclidean mixed space, so
a basis whose members are supported in a single coordinate has block diagonal Gram matrix. -/
theorem NumberField.det_gram_pi {k d : ℕ} (c : Fin k → Basis (Fin d) ℝ (euclidean.mixedSpace K))
    (bE : Fin d × Fin k → mixedPi K (Fin k))
    (hbE : ∀ (j : Fin d) (i : Fin k),
      bE (j, i) = toMixedPi K (Fin k) (Pi.single i ((euclidean.toMixed K) (c i j)))) :
    (Matrix.of fun p q : Fin d × Fin k ↦ inner ℝ (bE p) (bE q)).det
      = ∏ i, (Matrix.of fun j j' : Fin d ↦ inner ℝ (c i j) (c i j')).det := by
  classical
  have key : (Matrix.of fun p q : Fin d × Fin k ↦ inner ℝ (bE p) (bE q))
      = Matrix.blockDiagonal
        (fun i ↦ Matrix.of fun j j' : Fin d ↦ (inner ℝ (c i j) (c i j') : ℝ)) := by
    ext ⟨j, i⟩ ⟨j', i'⟩
    simp only [Matrix.of_apply]
    rw [hbE j i, hbE j' i', inner_toMixedPi]
    by_cases h : i = i'
    · subst h
      rw [Matrix.blockDiagonal_apply_eq, Finset.sum_eq_single i]
      · rw [Pi.single_eq_same, Pi.single_eq_same, ← inner_euclidean]
        rfl
      · intro l _ hl
        rw [Pi.single_eq_of_ne hl]
        simp
      · simp
    · rw [Matrix.blockDiagonal_apply_ne _ _ _ h]
      refine Finset.sum_eq_zero fun l _ ↦ ?_
      rcases eq_or_ne l i with rfl | hl
      · rw [Pi.single_eq_of_ne h]
        simp
      · rw [Pi.single_eq_of_ne hl]
        simp
  rw [key, Matrix.det_blockDiagonal]

end Product

/-!
### Primitivity of the Plücker point
-/

section Primitive

open exteriorPower

open scoped nonZeroDivisors

omit [Fintype ι] in
/-- If every product of elements of the `I i` lies in `J`, then the product of the `I i` does. -/
private theorem prod_le_of_forall {R A : Type*} [CommRing R] [CommRing A] [Algebra R A] :
    ∀ (n : ℕ) (I : Fin n → Submodule R A) (J : Submodule R A),
    (∀ a : Fin n → A, (∀ i, a i ∈ I i) → (∏ i, a i) ∈ J) → (∏ i, I i) ≤ J := by
  intro n
  induction n with
  | zero =>
    intro I J h
    simp only [Finset.univ_eq_empty, Finset.prod_empty]
    have h1 := h (fun i ↦ i.elim0) (fun i ↦ i.elim0)
    simp only [Finset.univ_eq_empty, Finset.prod_empty] at h1
    rw [Submodule.one_eq_span, Submodule.span_le, Set.singleton_subset_iff]
    exact h1
  | succ n ih =>
    intro I J h
    rw [Fin.prod_univ_succ]
    refine Submodule.mul_le.2 fun x hx y hy ↦ ?_
    have hy' := ih (fun i ↦ I i.succ) (Submodule.comap (LinearMap.mulLeft R x) J) ?_ hy
    · simpa using hy'
    · intro a ha
      have h2 := h (Fin.cons x a) (Fin.cases hx ha)
      rw [Fin.prod_cons] at h2
      simpa using h2

variable [LinearOrder ι]

omit [NumberField K] in
/-- The Plücker coordinates of a family of integral tuples are integral. -/
theorem NumberField.exists_plucker_int {k : ℕ} {y : Fin k → (ι → K)}
    (hy : ∀ i, y i ∈ integralTuples K ι) (s : Set.powersetCard ι k) :
    ∃ z : 𝓞 K, (z : K) = plucker k y s := by
  choose w hw using fun i ↦ NumberField.mem_integralTuples.1 (hy i)
  refine ⟨plucker k w s, ?_⟩
  have hy' : y = fun i ↦ (algebraMap (𝓞 K) K) ∘ (w i) := by
    funext i l
    exact (hw i l).symm
  rw [hy', plucker_map (algebraMap (𝓞 K) K) k w s]

omit [Fintype ι] [LinearOrder ι] [NumberField K] in
private theorem coe_prod_fractionalIdeal : ∀ (n : ℕ) (I : Fin n → FractionalIdeal (𝓞 K)⁰ K),
    ((∏ i, I i : FractionalIdeal (𝓞 K)⁰ K) : Submodule (𝓞 K) K)
      = ∏ i, ((I i : Submodule (𝓞 K) K)) := by
  intro n
  induction n with
  | zero => intro I; simp
  | succ n ih =>
    intro I
    rw [Fin.prod_univ_succ, Fin.prod_univ_succ, FractionalIdeal.coe_mul, ih]

variable (V : Submodule K (ι → K)) {k : ℕ} {y : Fin k → (ι → K)}
  {𝔞 : Fin k → FractionalIdeal (𝓞 K)⁰ K} {p : Set.powersetCard ι k → 𝓞 K}

omit [Fintype ι] [LinearOrder ι] in
/-- A scalar from `𝔞 i` times `y i` is an integral point. -/
private theorem smul_mem_integerPoints
    (hchar : ∀ x, x ∈ V.integerPoints ↔
      ∃ c : Fin k → K, (∀ i, c i ∈ 𝔞 i) ∧ x = ∑ i, c i • y i)
    {i : Fin k} {a : K} (ha : a ∈ 𝔞 i) : a • y i ∈ V.integerPoints := by
  classical
  refine (hchar _).2 ⟨Pi.single i a, fun j ↦ ?_, ?_⟩
  · rcases eq_or_ne j i with rfl | hj
    · simpa using ha
    · simp [hj, (𝔞 j).zero_mem]
  · rw [Finset.sum_eq_single i]
    · simp
    · intro j _ hj; simp [hj]
    · simp

/-- **The Plücker ideal of a saturated module is integral.** -/
theorem Submodule.prod_mul_plucker_le_one
    (hchar : ∀ x, x ∈ V.integerPoints ↔
      ∃ c : Fin k → K, (∀ i, c i ∈ 𝔞 i) ∧ x = ∑ i, c i • y i)
    (hp : ∀ s, (p s : K) = plucker k y s) :
    (∏ i, 𝔞 i) * (Ideal.span (Set.range p) : FractionalIdeal (𝓞 K)⁰ K) ≤ 1 := by
  classical
  set P : Submodule (𝓞 K) K :=
    ((Ideal.span (Set.range p) : FractionalIdeal (𝓞 K)⁰ K) : Submodule (𝓞 K) K) with hP
  set Q : Submodule (𝓞 K) K :=
    { carrier := {x | ∀ z ∈ P, x * z ∈ (1 : Submodule (𝓞 K) K)}
      add_mem' := fun hx hy z hz ↦ by
        rw [add_mul]; exact Submodule.add_mem _ (hx z hz) (hy z hz)
      zero_mem' := fun z _ ↦ by rw [zero_mul]; exact Submodule.zero_mem _
      smul_mem' := fun r x hx z hz ↦ by
        rw [smul_mul_assoc]; exact Submodule.smul_mem _ _ (hx z hz) } with hQ
  have hgen : ∀ (a : Fin k → K), (∀ i, a i ∈ 𝔞 i) → ∀ s,
      (∏ i, a i) * ((p s : K)) ∈ (1 : Submodule (𝓞 K) K) := by
    intro a ha s
    have hint : ∀ i, a i • y i ∈ integralTuples K ι := fun i ↦
      (smul_mem_integerPoints V hchar (ha i)).2
    obtain ⟨z, hz⟩ := NumberField.exists_plucker_int hint s
    refine Submodule.mem_one.2 ⟨z, ?_⟩
    rw [show (algebraMap (𝓞 K) K) z = (z : K) from rfl, hz, hp s, exteriorPower.plucker_smul]
  have hQle : (∏ i, ((𝔞 i : Submodule (𝓞 K) K))) ≤ Q := by
    refine prod_le_of_forall k _ _ fun a ha ↦ ?_
    intro z hz
    obtain ⟨z', hz', rfl⟩ := (FractionalIdeal.mem_coeIdeal _).1 hz
    clear hz
    induction hz' using Submodule.span_induction with
    | mem x hx => obtain ⟨s, rfl⟩ := hx; exact hgen a ha s
    | zero => simp
    | add u v _ _ hu hv => rw [map_add, mul_add]; exact Submodule.add_mem _ hu hv
    | smul r u _ hu =>
      rw [smul_eq_mul, map_mul, ← mul_assoc, mul_comm ((∏ i, a i)) _, mul_assoc]
      exact Submodule.smul_mem _ r hu
  rw [← FractionalIdeal.coe_le_coe, FractionalIdeal.coe_mul, coe_prod_fractionalIdeal,
    FractionalIdeal.coe_one]
  exact Submodule.mul_le.2 fun x hx z hz ↦ hQle hx z hz

omit [Fintype ι] [LinearOrder ι] [NumberField K] in
private theorem prod_mem_prod_fractionalIdeal : ∀ (n : ℕ) (I : Fin n → FractionalIdeal (𝓞 K)⁰ K)
    (a : Fin n → K), (∀ i, a i ∈ I i) → (∏ i, a i) ∈ (∏ i, I i) := by
  intro n
  induction n with
  | zero =>
    intro I a _
    simp only [Finset.univ_eq_empty, Finset.prod_empty]
    exact (FractionalIdeal.mem_one_iff _).2 ⟨1, by simp⟩
  | succ n ih =>
    intro I a ha
    rw [Fin.prod_univ_succ, Fin.prod_univ_succ]
    exact FractionalIdeal.mul_mem_mul (ha 0) (ih _ _ fun i ↦ ha i.succ)

/-- **Primitivity: the Plücker ideal of the integral points of a subspace is the unit ideal.**
This is Schmidt's Lemmas 5 and 6 over a number field, and the only place the saturation of
`V ∩ (𝓞 K)ⁱ` is used. -/
theorem Submodule.prod_mul_plucker_eq_one
    (hy : LinearIndependent K y) (h𝔞 : ∀ i, 𝔞 i ≠ 0)
    (hchar : ∀ x, x ∈ V.integerPoints ↔
      ∃ c : Fin k → K, (∀ i, c i ∈ 𝔞 i) ∧ x = ∑ i, c i • y i)
    (hp : ∀ s, (p s : K) = plucker k y s) :
    (∏ i, 𝔞 i) * (Ideal.span (Set.range p) : FractionalIdeal (𝓞 K)⁰ K) = 1 := by
  classical
  have hle := Submodule.prod_mul_plucker_le_one V hchar hp
  obtain ⟨𝔠₀, h𝔠₀⟩ := FractionalIdeal.le_one_iff_exists_coeIdeal.1 hle
  suffices h : 𝔠₀ = ⊤ by rw [← h𝔠₀, h]; simp
  by_contra hne
  obtain ⟨𝔮, h𝔮max, h𝔮le⟩ := Ideal.exists_le_maximal 𝔠₀ hne
  have h𝔮inst : 𝔮.IsMaximal := h𝔮max
  have hsm : ∀ (J : FractionalIdeal (𝓞 K)⁰ K) (r : 𝓞 K) (x : K), x ∈ J → (r : K) * x ∈ J :=
    fun J r x hx ↦ by
      have h := Submodule.smul_mem ((J : Submodule (𝓞 K) K)) r hx
      rwa [Algebra.smul_def] at h
  have h𝔮bot : 𝔮 ≠ ⊥ :=
    Ring.ne_bot_of_isMaximal_of_not_isField h𝔮max (NumberField.RingOfIntegers.not_isField K)
  have h𝔮ne : (𝔮 : FractionalIdeal (𝓞 K)⁰ K) ≠ 0 := by
    simp [h𝔮bot]
  -- choose `a i ∈ 𝔞 i` outside `𝔮 𝔞 i`
  have hstep : ∀ i, ∃ a ∈ 𝔞 i, a ∉ (𝔮 : FractionalIdeal (𝓞 K)⁰ K) * 𝔞 i := by
    intro i
    by_contra hcon
    push Not at hcon
    have hle2 : 𝔞 i ≤ (𝔮 : FractionalIdeal (𝓞 K)⁰ K) * 𝔞 i := hcon
    have hone : (1 : FractionalIdeal (𝓞 K)⁰ K) ≤ (𝔮 : FractionalIdeal (𝓞 K)⁰ K) := by
      calc (1 : FractionalIdeal (𝓞 K)⁰ K) = 𝔞 i * (𝔞 i)⁻¹ := (mul_inv_cancel₀ (h𝔞 i)).symm
        _ ≤ ((𝔮 : FractionalIdeal (𝓞 K)⁰ K) * 𝔞 i) * (𝔞 i)⁻¹ := by
            gcongr
        _ = (𝔮 : FractionalIdeal (𝓞 K)⁰ K) := by
            rw [mul_assoc, mul_inv_cancel₀ (h𝔞 i), mul_one]
    rw [show (1 : FractionalIdeal (𝓞 K)⁰ K) = ((⊤ : Ideal (𝓞 K)) : FractionalIdeal (𝓞 K)⁰ K)
      by simp, FractionalIdeal.coeIdeal_le_coeIdeal] at hone
    exact h𝔮max.ne_top (top_le_iff.1 hone)
  choose a ha hanot using hstep
  have hint : ∀ i, a i • y i ∈ integralTuples K ι := fun i ↦
    (smul_mem_integerPoints V hchar (ha i)).2
  choose w hw using fun i ↦ NumberField.mem_integralTuples.1 (hint i)
  have hwy : (fun i ↦ (algebraMap (𝓞 K) K) ∘ (w i)) = fun i ↦ a i • y i := by
    funext i l; exact hw i l
  have hplk : ∀ s, ((plucker k w s : 𝓞 K) : K) = (∏ i, a i) * ((p s : K)) := by
    intro s
    have h1 := plucker_map (algebraMap (𝓞 K) K) k w s
    rw [hwy, exteriorPower.plucker_smul, ← hp s] at h1
    exact h1.symm
  have hq𝔮 : ∀ s, plucker k w s ∈ 𝔮 := by
    intro s
    have h1 : ((plucker k w s : 𝓞 K) : K) ∈
        ((∏ i, 𝔞 i) * (Ideal.span (Set.range p) : FractionalIdeal (𝓞 K)⁰ K)) := by
      rw [hplk s]
      exact FractionalIdeal.mul_mem_mul (prod_mem_prod_fractionalIdeal k 𝔞 a ha)
        ((FractionalIdeal.mem_coeIdeal _).2 ⟨p s, Ideal.subset_span ⟨s, rfl⟩, rfl⟩)
    rw [← h𝔠₀] at h1
    obtain ⟨q', hq', hq'eq⟩ := (FractionalIdeal.mem_coeIdeal _).1 h1
    have : q' = plucker k w s := by
      exact_mod_cast hq'eq
    exact h𝔮le (this ▸ hq')
  -- the reductions of the `a i • y i` are dependent over the residue field
  have hzero : plucker k (fun i ↦ (Ideal.Quotient.mk 𝔮) ∘ (w i)) = 0 := by
    funext s
    rw [plucker_map (Ideal.Quotient.mk 𝔮) k w s]
    exact Ideal.Quotient.eq_zero_iff_mem.2 (hq𝔮 s)
  let _ : Field (𝓞 K ⧸ 𝔮) := Ideal.Quotient.field 𝔮
  obtain ⟨cq, hcqsum, i₀, hi₀⟩ := Fintype.not_linearIndependent_iff.1
    ((exteriorPower.plucker_eq_zero_iff (K := 𝓞 K ⧸ 𝔮) k _).1 hzero)
  choose c hc using fun i ↦ Ideal.Quotient.mk_surjective (cq i)
  set u : ι → K := fun l ↦ ∑ i, ((c i : K) * a i) * (y i l) with hu
  have huV : u ∈ V.integerPoints := by
    refine (hchar u).2 ⟨fun i ↦ (c i : K) * a i, fun i ↦ ?_, ?_⟩
    · exact hsm (𝔞 i) (c i) _ (ha i)
    · funext l
      simp [hu, Finset.sum_apply]
  have huq : ∀ l, u l ∈ ((𝔮 : FractionalIdeal (𝓞 K)⁰ K)) := by
    intro l
    have h1 : (∑ i, c i * w i l : 𝓞 K) ∈ 𝔮 := by
      rw [← Ideal.Quotient.eq_zero_iff_mem, map_sum]
      have h2 := congrFun hcqsum l
      simp only [Finset.sum_apply, Pi.smul_apply, Function.comp_apply, smul_eq_mul,
        Pi.zero_apply] at h2
      rw [← h2]
      exact Finset.sum_congr rfl fun i _ ↦ by rw [map_mul, hc i]
    refine (FractionalIdeal.mem_coeIdeal _).2 ⟨∑ i, c i * w i l, h1, ?_⟩
    rw [hu, map_sum]
    exact Finset.sum_congr rfl fun i _ ↦ by
      rw [map_mul, show (algebraMap (𝓞 K) K) (w i l) = ((w i l : 𝓞 K) : K) from rfl, hw i l]
      simp [mul_assoc]
  have hmul : ∀ t ∈ ((𝔮 : FractionalIdeal (𝓞 K)⁰ K))⁻¹, ∀ i, t * ((c i : K) * a i) ∈ 𝔞 i := by
    intro t ht
    have htu : t • u ∈ V.integerPoints := by
      refine ⟨V.smul_mem t huV.1, NumberField.mem_integralTuples.2 fun l ↦ ?_⟩
      have h3 : t * u l ∈ (1 : FractionalIdeal (𝓞 K)⁰ K) := by
        rw [← inv_mul_cancel₀ h𝔮ne]
        exact FractionalIdeal.mul_mem_mul ht (huq l)
      obtain ⟨z, hz⟩ := (FractionalIdeal.mem_one_iff _).1 h3
      exact ⟨z, by simpa using hz⟩
    obtain ⟨d, hd, hdeq⟩ := (hchar _).1 htu
    have heq : ∀ i, d i - t * ((c i : K) * a i) = 0 := by
      refine Fintype.linearIndependent_iff.1 hy _ ?_
      have h4 : ∑ i, (t * ((c i : K) * a i)) • y i = t • u := by
        rw [hu]
        funext l
        simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, Finset.mul_sum]
        exact Finset.sum_congr rfl fun i _ ↦ by ring
      simp only [sub_smul, Finset.sum_sub_distrib, h4, ← hdeq, sub_self]
    intro i
    rw [← sub_eq_zero.1 (heq i)]
    exact hd i
  have hcq : ∀ i, c i ∈ 𝔮 := by
    intro i
    by_contra hci
    have hsub : ((𝔮 : FractionalIdeal (𝓞 K)⁰ K))⁻¹ *
        FractionalIdeal.spanSingleton (𝓞 K)⁰ ((c i : K) * a i) ≤ 𝔞 i := by
      refine FractionalIdeal.mul_le.2 fun t ht z hz ↦ ?_
      obtain ⟨r, rfl⟩ := (FractionalIdeal.mem_spanSingleton _).1 hz
      rw [Algebra.smul_def, ← mul_assoc, mul_comm t _, mul_assoc]
      exact hsm (𝔞 i) r _ (hmul t ht i)
    have hmem : ((c i : K) * a i) ∈ ((𝔮 : FractionalIdeal (𝓞 K)⁰ K)) * 𝔞 i := by
      have h5 : FractionalIdeal.spanSingleton (𝓞 K)⁰ ((c i : K) * a i)
          ≤ (𝔮 : FractionalIdeal (𝓞 K)⁰ K) * 𝔞 i := by
        calc FractionalIdeal.spanSingleton (𝓞 K)⁰ ((c i : K) * a i)
            = (𝔮 : FractionalIdeal (𝓞 K)⁰ K) * (((𝔮 : FractionalIdeal (𝓞 K)⁰ K))⁻¹ *
                FractionalIdeal.spanSingleton (𝓞 K)⁰ ((c i : K) * a i)) := by
              rw [← mul_assoc, mul_inv_cancel₀ h𝔮ne, one_mul]
          _ ≤ (𝔮 : FractionalIdeal (𝓞 K)⁰ K) * 𝔞 i := by gcongr
      exact h5 (FractionalIdeal.mem_spanSingleton_self _ _)
    obtain ⟨r, m, hm, hrm⟩ := Ideal.IsMaximal.exists_inv h𝔮max hci
    refine hanot i ?_
    have hai : a i = (r : K) * ((c i : K) * a i) + (m : K) * a i := by
      have : ((r * c i + m : 𝓞 K) : K) = 1 := by rw [hrm]; simp
      push_cast at this
      calc a i = (((r : K) * (c i : K) + (m : K))) * a i := by rw [this]; ring
        _ = (r : K) * ((c i : K) * a i) + (m : K) * a i := by ring
    rw [hai]
    refine Submodule.add_mem _ ?_ ?_
    · exact hsm ((𝔮 : FractionalIdeal (𝓞 K)⁰ K) * 𝔞 i) r _ hmem
    · exact FractionalIdeal.mul_mem_mul ((FractionalIdeal.mem_coeIdeal _).2 ⟨m, hm, rfl⟩) (ha i)
  exact hi₀ (by rw [← hc i₀, Ideal.Quotient.eq_zero_iff_mem]; exact hcq i₀)

end Primitive

/-!
### The map attached to a `K`-basis of the subspace
-/

section Assembly

open exteriorPower Matrix

variable [LinearOrder ι]

omit [LinearOrder ι] [Fintype ι] in
open scoped Classical in
/-- The map of euclidean tuple spaces attached to a family `y` sends the mixed embedding of a
coefficient tuple to the mixed embedding of the corresponding combination. -/
theorem NumberField.mixedPiMap_emb {k : ℕ} (y : Fin k → (ι → K)) (c : Fin k → K) :
    mixedPiMap ((Matrix.of y).map (mixedEmbedding K))
        (toMixedPi K (Fin k) (fun i ↦ mixedEmbedding K (c i)))
      = mixedPiEmb K ι (∑ i, c i • y i) := by
  rw [mixedPiMap]
  simp only [LinearMap.coe_comp, Function.comp_apply, LinearEquiv.coe_coe,
    LinearMap.coe_restrictScalars, LinearEquiv.symm_apply_apply, Matrix.toLin'_apply,
    mixedPiEmb_apply]
  congr 1
  funext l
  simp only [Matrix.mulVec, dotProduct, Matrix.transpose_apply, Matrix.map_apply, Matrix.of_apply,
    Finset.sum_apply, Pi.smul_apply, smul_eq_mul, map_sum, map_mul]
  exact Finset.sum_congr rfl fun i _ ↦ by ring

open scoped Classical in
/-- **The Gram endomorphism of an independent family has positive determinant.** -/
theorem NumberField.det_mixedPiEnd_pos {k : ℕ} {y : Fin k → (ι → K)} (hy : LinearIndependent K y) :
    0 < LinearMap.det (mixedPiEnd ((Matrix.of y).map (mixedEmbedding K))) := by
  rw [det_mixedPiEnd, norm_det_gram]
  obtain ⟨s₀, hs₀⟩ : ∃ s, plucker k ((Matrix.of y).row) s ≠ 0 := by
    by_contra hcon
    push Not at hcon
    exact exteriorPower.plucker_ne_zero hy (funext hcon)
  refine Finset.prod_pos fun w _ ↦ pow_pos ?_ _
  refine Finset.sum_pos' (fun s _ ↦ by positivity) ⟨s₀, Finset.mem_univ s₀, ?_⟩
  exact pow_pos (w.1.pos hs₀) 2

omit [LinearOrder ι] in
open scoped Classical in
/-- **The map attached to a family with invertible Gram endomorphism is injective.** -/
theorem NumberField.mixedPiMap_injective {k : ℕ} (Y : Matrix (Fin k) ι (mixedSpace K))
    (hdet : LinearMap.det (mixedPiEnd Y) ≠ 0) : Function.Injective (mixedPiMap Y) := by
  have hA : Function.Injective (mixedPiEnd Y) := by
    have h1 : IsUnit (mixedPiEnd Y) :=
      (LinearMap.isUnit_iff_isUnit_det _).2 (isUnit_iff_ne_zero.2 hdet)
    exact LinearMap.ker_eq_bot.1 ((LinearMap.isUnit_iff_ker_eq_bot _).1 h1)
  rw [← LinearMap.ker_eq_bot, LinearMap.ker_eq_bot']
  intro x hx
  refine hA ?_
  rw [map_zero]
  refine ext_inner_right ℝ fun v ↦ ?_
  rw [inner_zero_left, ← inner_mixedPiMap Y x v, hx, inner_zero_left]

open Real NumberField.InfinitePlace in
open scoped Classical nonZeroDivisors in
/-- The covolume computation, with the pseudo-basis data supplied. -/
private theorem covolume_of_data {k : ℕ} {V : Submodule K (ι → K)}
    (y : Fin k → (ι → K)) (𝔞 : Fin k → FractionalIdeal (𝓞 K)⁰ K)
    (hy : LinearIndependent K y) (h𝔞 : ∀ i, 𝔞 i ≠ 0)
    (hchar : ∀ x, x ∈ V.integerPoints ↔
      ∃ c : Fin k → K, (∀ i, c i ∈ 𝔞 i) ∧ x = ∑ i, c i • y i)
    (hyM : ∀ i, y i ∈ V.integerPoints)
    (hspanY : Submodule.span K (Set.range y) = V) :
    ∃ b : Basis (Fin (finrank ℚ K) × Fin k) ℝ ↥V.mixedSpan,
      V.mixedLattice = Submodule.span ℤ (Set.range b) ∧
      ZLattice.covolume (Submodule.span ℤ (Set.range b))
        = ((2 : ℝ)⁻¹ ^ nrComplexPlaces K * √|NumberField.discr K|) ^ k
          * V.arakelovMulHeight := by
  classical
  -- the integral Plücker coordinates
  have hint : ∀ i, y i ∈ integralTuples K ι := fun i ↦ (hyM i).2
  choose p hp using fun s ↦ NumberField.exists_plucker_int hint s
  -- a `ℤ`-basis of each fractional ideal, read in the euclidean mixed space
  choose a bi hab hspan_a hcov0 using fun i ↦
    NumberField.exists_idealBasis (Units.mk0 (𝔞 i) (h𝔞 i))
  have hcov : ∀ i, ZLattice.covolume (Submodule.span ℤ (Set.range (bi i)))
      = (FractionalIdeal.absNorm (𝔞 i) : ℝ)
        * (2 : ℝ)⁻¹ ^ nrComplexPlaces K * √|NumberField.discr K| := fun i ↦ by
    simpa using hcov0 i
  have ha𝔞 : ∀ i j, a i j ∈ 𝔞 i := fun i j ↦
    (hspan_a i (a i j)).1 (Submodule.subset_span ⟨j, rfl⟩)
  -- the `ℝ`-basis of the euclidean space of `k`-tuples
  set bE : Basis (Fin (finrank ℚ K) × Fin k) ℝ (mixedPi K (Fin k)) :=
    (((Pi.basis (fun i ↦ bi i)).reindex
      ((Equiv.sigmaEquivProd (Fin k) (Fin (finrank ℚ K))).trans (Equiv.prodComm _ _))).map
      (WithLp.linearEquiv 2 ℝ (∀ _ : Fin k, euclidean.mixedSpace K)).symm) with hbEdef
  have hbE : ∀ (j : Fin (finrank ℚ K)) (i : Fin k),
      bE (j, i) = toMixedPi K (Fin k) (Pi.single i ((euclidean.toMixed K) (bi i j))) := by
    intro j i
    rw [hbEdef]
    simp only [Basis.map_apply, Basis.coe_reindex, Function.comp_apply, Equiv.symm_trans_apply,
      Equiv.prodComm_symm, Equiv.prodComm_apply, Prod.swap_prod_mk,
      Equiv.sigmaEquivProd_symm_apply, Pi.basis_apply, toMixedPi_apply]
    refine congrArg _ (funext fun i' ↦ ?_)
    rcases eq_or_ne i' i with rfl | hne
    · simp
    · simp [Pi.single_eq_of_ne hne]
  -- the integral points are the `ℤ`-span of the products `a i j • y i`
  have haM : ∀ (i : Fin k) (j : Fin (finrank ℚ K)), (a i j) • y i ∈ V.integerPoints :=
    fun i j ↦ smul_mem_integerPoints V hchar (ha𝔞 i j)
  have hZ : V.integerPoints.restrictScalars ℤ
      = Submodule.span ℤ (Set.range (fun q : Fin (finrank ℚ K) × Fin k ↦ (a q.2 q.1) • y q.2)) := by
    refine le_antisymm (fun z hz ↦ ?_) (Submodule.span_le.2 ?_)
    · obtain ⟨c, hc, rfl⟩ := (hchar z).1 hz
      have hcj : ∀ i, ∃ n : Fin (finrank ℚ K) → ℤ, ∑ j, n j • a i j = c i := fun i ↦
        (Submodule.mem_span_range_iff_exists_fun ℤ).1 ((hspan_a i (c i)).2 (hc i))
      choose n hn using hcj
      refine (Submodule.mem_span_range_iff_exists_fun ℤ).2 ⟨fun q ↦ n q.2 q.1, ?_⟩
      rw [Fintype.sum_prod_type_right]
      refine Finset.sum_congr rfl fun i _ ↦ ?_
      rw [← hn i, Finset.sum_smul]
      exact Finset.sum_congr rfl fun j _ ↦ by rw [smul_assoc]
    · rintro _ ⟨q, rfl⟩
      exact haM q.2 q.1
  -- the map attached to the family, and its image
  set Ym : Matrix (Fin k) ι (mixedSpace K) := (Matrix.of y).map (mixedEmbedding K) with hYm
  have hfbE : ∀ (j : Fin (finrank ℚ K)) (i : Fin k),
      mixedPiMap Ym (bE (j, i)) = mixedPiEmb K ι ((a i j) • y i) := by
    intro j i
    have h1 : (fun i' ↦ mixedEmbedding K ((Pi.single i (a i j) : Fin k → K) i'))
        = Pi.single i (mixedEmbedding K (a i j)) := by
      funext i'
      rcases eq_or_ne i' i with rfl | hne
      · simp
      · simp [Pi.single_eq_of_ne hne]
    have h2 : ∑ i', ((Pi.single i (a i j) : Fin k → K) i') • y i' = (a i j) • y i := by
      rw [Finset.sum_eq_single i]
      · simp
      · intro i' _ hne; simp [Pi.single_eq_of_ne hne]
      · simp
    rw [hbE j i, hab i j, hYm, ← h1, NumberField.mixedPiMap_emb y (Pi.single i (a i j)), h2]
  have hinj : Function.Injective (mixedPiMap Ym) :=
    NumberField.mixedPiMap_injective Ym (ne_of_gt (hYm ▸ NumberField.det_mixedPiEnd_pos hy))
  have hrange : LinearMap.range (mixedPiMap Ym) = V.mixedSpan := by
    refine le_antisymm ?_ ?_
    · rw [LinearMap.range_eq_map, ← bE.span_eq, Submodule.map_span, Submodule.span_le]
      rintro _ ⟨_, ⟨q, rfl⟩, rfl⟩
      obtain ⟨j, i⟩ := q
      rw [hfbE j i]
      exact Submodule.subset_span ⟨(a i j) • y i, V.smul_mem _ (hyM i).1, rfl⟩
    · rw [Submodule.mixedSpan, Submodule.span_le]
      rintro _ ⟨v, hv, rfl⟩
      obtain ⟨c, rfl⟩ := (Submodule.mem_span_range_iff_exists_fun K).1 (by rw [hspanY]; exact hv)
      exact ⟨toMixedPi K (Fin k) (fun i ↦ mixedEmbedding K (c i)),
        NumberField.mixedPiMap_emb y c⟩
  set e : mixedPi K (Fin k) ≃ₗ[ℝ] ↥V.mixedSpan :=
    (LinearEquiv.ofInjective (mixedPiMap Ym) hinj).trans (LinearEquiv.ofEq _ _ hrange) with he
  have hbWcoe : ∀ q, (((bE.map e) q : ↥V.mixedSpan) : mixedPi K ι) = mixedPiMap Ym (bE q) := by
    intro q
    rw [Basis.map_apply, he]
    rfl
  have hLmap : Submodule.map ((V.mixedSpan.subtype).restrictScalars ℤ) V.mixedLattice
      = Submodule.span ℤ (Set.range (fun q ↦ (((bE.map e) q : ↥V.mixedSpan) : mixedPi K ι))) := by
    rw [Submodule.mixedLattice, Submodule.map_comap_eq_self, hZ, Submodule.map_span,
      ← Set.range_comp]
    · refine congrArg _ (congrArg Set.range (funext fun q ↦ ?_))
      obtain ⟨j, i⟩ := q
      rw [Function.comp_apply, hbWcoe (j, i), hfbE j i]
    · rintro _ ⟨z, hz, rfl⟩
      exact ⟨⟨_, Submodule.subset_span ⟨z, hz.1, rfl⟩⟩, rfl⟩
  have hL : V.mixedLattice = Submodule.span ℤ (Set.range (bE.map e)) := by
    refine Submodule.map_injective_of_injective
      (f := (V.mixedSpan.subtype).restrictScalars ℤ) (Submodule.injective_subtype _) ?_
    rw [hLmap, Submodule.map_span, ← Set.range_comp]
    rfl
  refine ⟨bE.map e, hL, ?_⟩
  -- the squared covolume
  have hsq : ZLattice.covolume (Submodule.span ℤ (Set.range (bE.map e))) ^ 2
      = LinearMap.det (mixedPiEnd Ym)
        * (Matrix.of fun q q' ↦ inner ℝ (bE q) (bE q')).det :=
    ZLattice.covolume_sq_eq_det_gram_comp _ ((bE.map e).restrictScalars ℤ) (mixedPiMap Ym)
      (mixedPiEnd Ym) bE (inner_mixedPiMap Ym) (fun q ↦ by
        rw [Basis.restrictScalars_apply]; exact hbWcoe q)
  -- the Gram determinant of the product basis
  have hgram : (Matrix.of fun q q' ↦ inner ℝ (bE q) (bE q')).det
      = ∏ i, ((FractionalIdeal.absNorm (𝔞 i) : ℝ)
          * ((2 : ℝ)⁻¹ ^ nrComplexPlaces K * √|NumberField.discr K|)) ^ 2 := by
    rw [NumberField.det_gram_pi bi (fun q ↦ bE q) (fun j i ↦ hbE j i)]
    refine Finset.prod_congr rfl fun i _ ↦ ?_
    rw [← mul_assoc, ← hcov i, ZLattice.covolume_sq_eq_det_gram _ ((bi i).restrictScalars ℤ)]
    exact congrArg Matrix.det (Matrix.ext fun j j' ↦ by simp [Basis.restrictScalars_apply])
  -- the archimedean factor
  have hdet : LinearMap.det (mixedPiEnd Ym)
      = ∏ w : NumberField.InfinitePlace K,
        (∑ s : Set.powersetCard ι k, w (plucker k y s) ^ 2) ^ w.mult := by
    rw [hYm, det_mixedPiEnd, norm_det_gram (Matrix.of y)]
    rfl
  -- the finite factor
  have hplk0 : plucker k y ≠ 0 := exteriorPower.plucker_ne_zero hy
  have hpne : ∃ s, p s ≠ 0 := by
    by_contra hcon
    push Not at hcon
    refine hplk0 (funext fun s ↦ ?_)
    rw [← hp s, hcon s]
    simp
  have hnorm : (∏ i, (FractionalIdeal.absNorm (𝔞 i) : ℝ))
      = ((Ideal.absNorm (Ideal.span (Set.range p)) : ℝ))⁻¹ := by
    have h := congrArg FractionalIdeal.absNorm
      (Submodule.prod_mul_plucker_eq_one V hy h𝔞 hchar hp)
    rw [map_mul, map_prod, FractionalIdeal.coeIdeal_absNorm, map_one] at h
    have h2 : (∏ i, (FractionalIdeal.absNorm (𝔞 i) : ℝ))
        * ((Ideal.absNorm (Ideal.span (Set.range p)) : ℝ)) = 1 := by
      exact_mod_cast congrArg (fun q : ℚ ↦ (q : ℝ)) h
    have hne : ((Ideal.absNorm (Ideal.span (Set.range p)) : ℝ)) ≠ 0 := by
      intro hzero
      rw [hzero, mul_zero] at h2
      exact zero_ne_one h2
    field_simp at h2 ⊢
    linarith [h2]
  have hH : V.arakelovMulHeight
      = (∏ w : NumberField.InfinitePlace K,
          (∑ s : Set.powersetCard ι k, w (plucker k y s) ^ 2) ^ (w.mult / 2 : ℝ))
        * ((Ideal.absNorm (Ideal.span (Set.range p)) : ℝ))⁻¹ := by
    rw [← hspanY, Submodule.arakelovMulHeight_span_range hy,
      NumberField.arakelovMulHeight_eq hplk0]
    congr 1
    rw [← NumberField.FinitePlace.finprod_iSup_eq_inv_absNorm hpne]
    exact finprod_congr fun v ↦ by simp only [hp]
  -- squaring the archimedean factor
  have hA2 : (∏ w : NumberField.InfinitePlace K,
        (∑ s : Set.powersetCard ι k, w (plucker k y s) ^ 2) ^ (w.mult / 2 : ℝ)) ^ 2
      = ∏ w : NumberField.InfinitePlace K,
        (∑ s : Set.powersetCard ι k, w (plucker k y s) ^ 2) ^ w.mult := by
    rw [← Finset.prod_pow]
    refine Finset.prod_congr rfl fun w _ ↦ ?_
    have hx : (0 : ℝ) ≤ ∑ s : Set.powersetCard ι k, w (plucker k y s) ^ 2 :=
      Finset.sum_nonneg fun s _ ↦ sq_nonneg _
    rw [← Real.rpow_natCast ((∑ s : Set.powersetCard ι k, w (plucker k y s) ^ 2)
        ^ ((w.mult : ℝ) / 2)) 2, ← Real.rpow_mul hx, ← Real.rpow_natCast _ w.mult]
    congr 1
    push_cast
    ring
  -- the product of the ideal norms
  have hp2 : ∏ i : Fin k, ((FractionalIdeal.absNorm (𝔞 i) : ℝ)
        * ((2 : ℝ)⁻¹ ^ nrComplexPlaces K * √|NumberField.discr K|)) ^ 2
      = ((∏ i : Fin k, (FractionalIdeal.absNorm (𝔞 i) : ℝ))
          * ((2 : ℝ)⁻¹ ^ nrComplexPlaces K * √|NumberField.discr K|) ^ k) ^ 2 := by
    rw [Finset.prod_pow]
    congr 1
    rw [Finset.prod_mul_distrib, Finset.prod_const, Finset.card_univ, Fintype.card_fin]
  -- both sides have the same square
  have hsq2 : ZLattice.covolume (Submodule.span ℤ (Set.range (bE.map e))) ^ 2
      = (((2 : ℝ)⁻¹ ^ nrComplexPlaces K * √|NumberField.discr K|) ^ k
          * V.arakelovMulHeight) ^ 2 := by
    rw [hsq, hdet, hgram, hp2, hH, hnorm, ← hA2]
    ring
  have hnn : (0 : ℝ) ≤ ((2 : ℝ)⁻¹ ^ nrComplexPlaces K * √|NumberField.discr K|) ^ k
      * V.arakelovMulHeight := by
    exact mul_nonneg
      (pow_nonneg (mul_nonneg (pow_nonneg (by norm_num) _) (Real.sqrt_nonneg _)) _)
      V.arakelovMulHeight_pos.le
  have hcovnn : 0 ≤ ZLattice.covolume (Submodule.span ℤ (Set.range (bE.map e))) :=
    (ZLattice.covolume_pos _ MeasureTheory.volume).le
  rw [← Real.sqrt_sq hcovnn, hsq2, Real.sqrt_sq hnn]

open scoped Classical in
private theorem exists_lattice_basis (V : Submodule K (ι → K)) :
    ∃ b : Basis (Fin (finrank ℚ K) × Fin (finrank K V)) ℝ ↥V.mixedSpan,
      V.mixedLattice = Submodule.span ℤ (Set.range b) ∧
      ZLattice.covolume (Submodule.span ℤ (Set.range b))
        = ((2 : ℝ)⁻¹ ^ NumberField.InfinitePlace.nrComplexPlaces K
            * √|NumberField.discr K|) ^ finrank K V * V.arakelovMulHeight := by
  obtain ⟨y, 𝔞, hy, h𝔞, hyM, hchar⟩ := V.exists_pseudoBasis_integerPoints
  have hle : Submodule.span K (Set.range y) ≤ V :=
    Submodule.span_le.2 (by rintro _ ⟨i, rfl⟩; exact (hyM i).1)
  have hrk : finrank K ↥(Submodule.span K (Set.range y)) = finrank K V := by
    rw [finrank_span_eq_card hy, Fintype.card_fin]
  exact covolume_of_data y 𝔞 hy h𝔞 hchar hyM (Submodule.eq_of_le_of_finrank_eq hle hrk)

section Finiteness

omit [Fintype ι]

variable [Finite ι]

open scoped Classical in
theorem Submodule.mixedLattice_eq_span (V : Submodule K (ι → K)) :
    ∃ b : Basis (Fin (finrank ℚ K) × Fin (finrank K V)) ℝ ↥V.mixedSpan,
      V.mixedLattice = Submodule.span ℤ (Set.range b) := by
  let _ : Fintype ι := Fintype.ofFinite ι
  obtain ⟨b, hL, -⟩ := exists_lattice_basis V
  exact ⟨b, hL⟩

open scoped Classical in
instance instDiscreteTopologyMixedLattice (V : Submodule K (ι → K)) :
    DiscreteTopology V.mixedLattice := by
  let _ : Fintype ι := Fintype.ofFinite ι
  obtain ⟨b, hL⟩ := V.mixedLattice_eq_span
  rw [hL]
  infer_instance

open scoped Classical in
instance instIsZLatticeMixedLattice (V : Submodule K (ι → K)) :
    IsZLattice ℝ V.mixedLattice := by
  constructor
  let _ : Fintype ι := Fintype.ofFinite ι
  obtain ⟨b, hL⟩ := V.mixedLattice_eq_span
  rw [hL]
  exact ZSpan.span_top b

open scoped Classical in
/-- **The real span of a subspace of `Kⁱ` has dimension `[K : ℚ] · dim V`.** -/
theorem Submodule.finrank_mixedSpan (V : Submodule K (ι → K)) :
    finrank ℝ ↥V.mixedSpan = finrank ℚ K * finrank K V := by
  obtain ⟨b, -⟩ := V.mixedLattice_eq_span
  simpa using finrank_eq_card_basis b

end Finiteness

open scoped Classical in
/-- **The covolume identity over a number field** (Layer 4.3; W. M. Schmidt, "On heights of
algebraic subspaces and diophantine approximations", *Annals of Mathematics* **85** (1967),
§3, Theorem 1). The lattice of integral points of a subspace `V ⊆ Kⁱ` has covolume the covolume
of `𝓞 K` raised to the dimension of `V`, times the Arakelov height of `V`:

```text
covol (V ∩ (𝓞 K)ⁱ) = (2^{-r₂} |discr K|^{1/2}) ^ k · H_Ar(V),
```

with `H_Ar` the height relative to `K`, so that the absolute height enters with the exponent
`[K : ℚ]`. Over `ℚ` every constant is `1` and this is `Submodule.covolume_intLattice`. -/
theorem Submodule.covolume_mixedLattice (V : Submodule K (ι → K)) :
    ZLattice.covolume V.mixedLattice
      = ((2 : ℝ)⁻¹ ^ NumberField.InfinitePlace.nrComplexPlaces K
          * √|NumberField.discr K|) ^ finrank K V * V.arakelovMulHeight := by
  obtain ⟨b, hL, hcov⟩ := exists_lattice_basis V
  rw [hL, hcov]

end Assembly

/-!
### Two readings of integrality

The finite half of the height of an integral tuple, and the membership test for the lattice of
integral points. Both are consumed by the Bombieri–Vaaler milestones of Layer 5, which differ in
their convex body but not in how they read integrality.
-/

namespace NumberField.mixedEmbedding

open Module NumberField NumberField.InfinitePlace

variable {K : Type*} [Field K] [NumberField K] {ι : Type*} [Finite ι]

open scoped Classical in
/-- **The finite places cost nothing for an integral tuple.** The product over the finite places
of the sup norms is the inverse of the absolute norm of the ideal the coordinates generate, which
is a positive integer. -/
theorem finprod_finitePlace_le_one {x : ι → K} (hx : x ≠ 0)
    (hint : ∀ l, ∃ z : 𝓞 K, (z : K) = x l) :
    (∏ᶠ v : FinitePlace K, ⨆ i, v (x i)) ≤ 1 := by
  choose z hz using hint
  have hzne : ∃ i, z i ≠ 0 := by
    by_contra hcon
    push Not at hcon
    exact hx (funext fun i ↦ by rw [← hz i, hcon i]; simp)
  have heq : (∏ᶠ v : FinitePlace K, ⨆ i, v (x i))
      = ∏ᶠ v : FinitePlace K, ⨆ i, v ((z i : K)) :=
    finprod_congr fun v ↦ iSup_congr fun i ↦ by rw [hz i]
  rw [heq, NumberField.FinitePlace.finprod_iSup_eq_inv_absNorm hzne]
  have hI : Ideal.span (Set.range z) ≠ (⊥ : Ideal (𝓞 K)) := by
    obtain ⟨i, hi⟩ := hzne
    exact fun h ↦ hi ((Ideal.span_eq_bot.1 h) (z i) ⟨i, rfl⟩)
  have h1 : (1 : ℝ) ≤ (Ideal.absNorm (Ideal.span (Set.range z)) : ℝ) := by
    exact_mod_cast Nat.one_le_iff_ne_zero.2 (fun h ↦ hI (Ideal.absNorm_eq_zero_iff.1 h))
  rw [inv_le_one_iff₀]
  exact Or.inr h1

omit [Finite ι] in
open scoped Classical in
/-- **Membership in the lattice of integral points**, read in `Kⁱ` rather than in the real
span. -/
theorem mem_mixedLattice_iff (V : Submodule K (ι → K)) {y : ↥V.mixedSpan} :
    y ∈ V.mixedLattice ↔ ∃ z ∈ V.integerPoints, mixedPiEmb K ι z = (y : mixedPi K ι) := by
  rw [Submodule.mixedLattice, Submodule.mem_comap, Submodule.mem_map]
  simp

end NumberField.mixedEmbedding


end

end
