import CanonicalLpInterpolation
import OptimalCylinderPacking
import AdmissibleCylinderWords
import CylinderLowerBranch
import ArithmeticInverseBlocks
import GeometricWordTail
import ArithmeticInverseTuples
import ArithmeticWordFibers
import CylinderHeadBound
import CylinderExpansionBound
import ArithmeticCylinderLaw
import ArithmeticCylinderResidues
import ArithmeticCylinderCongruence
import ArithmeticCylinderLower
import FiniteCylinderResidueLaw
import FairEnergyWordCore
import FormalConjectures.Util.ProblemImports
import FormalConjectures.Wikipedia.CollatzConjecture
import Erdos1135.Basic
import Erdos1135.CollatzStep
import Erdos1135.Parity
import Erdos1135.Division
import Erdos1135.Terras.Core.Defs
import Erdos1135.Tao.Syracuse.Defs
import Erdos1135.Tao.Syracuse.Basic
import Erdos1135.Tao.Syracuse.Affine
import Erdos1135.Tao.Syracuse.OffsetInjectivity
import Erdos1135.Tao.Syracuse.AffineReverse
import FairEnergyWordReversal
import FairEnergyWordSeparation
import HarmonicFiberBounds
import FairEnergyFinite
import FairEnergyMoments
import FairEnergyLimit
import FiniteSyracuseSeries
import FiniteSyracuseSeriesClosedForm
import CompatibleSyracuseResidues
import PadicSyracuseVariable
import GeometricSequenceLaw
import SyracuseVariableMeasurable
import FiniteCylinderMaximum
import OptimalFiniteCylinderRate
import CanonicalSyracuseCylinderLaw
import FairEnergyBound
import QuotientFiberBounds
import FairEnergyQuadraticFinite
import FairEnergyQuadraticBound
import Erdos1135.Tao.Probability.Finite
import Erdos1135.Tao.Probability.Geom
import Erdos1135.Tao.Probability.Truncation
import Erdos1135.Terras.Parity.Word
import Erdos1135.Tao.Syracuse.ParityBridge
import Erdos1135.Residues
import Erdos1135.TwoAdic
import Erdos1135.Terras.Parity.Residue
import Erdos1135.Tao.Syracuse.Residue
import Erdos1135.Tao.Syracuse.ValuationCylinder
import Erdos1135.Tao.Syracuse.ValuationCylinderResidue
import Erdos1135.Tao.Syracuse.CylinderMass
import Erdos1135.Tao.Syracuse.ValuationDistribution
import Erdos1135.Tao.Syracuse.Syrac
import Erdos1135.Tao.Fourier.Basic
import Erdos1135.Tao.Fourier.TV
import Erdos1135.Tao.Fourier.DecayStatement
import Erdos1135.Tao.Probability.Pascal
import Erdos1135.Tao.Fourier.Section7Character
import Erdos1135.Tao.Fourier.Section7SourceLaw
import Erdos1135.Tao.Section6.ModulusProjection
import Erdos1135.Tao.Section6.ConductorProjectivity
import UnitSourceUniformSeed
import CanonicalSyracuseSeries
import CanonicalSyracuseRecursion
import GeometricSequenceSplit
import CanonicalSyracuseStationarity
import PadicCylinderDetermining
import SyracuseCylinderTransitions
import PadicHaarCylinder
import CanonicalSyracuseUnique
import WeightedKernelLimit
import CesaroAbelLimit
import EndpointTailBounds
import ArithmeticCylinderGrowth
import CanonicalCylinderAbel
import FinitePathInverseWords
import OrbitCorrectionProduct
import FirstHitWordWeights
import HittingTimeClassification
import ActualCycleWeights
import ActualInverseOperator
import CanonicalCylinderRecursion
import CanonicalPadicCylinderRecursion
import CanonicalHaarEnergy
import UnitHaarCylinder
import Erdos1135.Tao.Fourier.Section7ProductPenalty
import Erdos1135.Tao.Probability.PascalPrime
import Erdos1135.Tao.Fourier.Section7WhiteHitSplit
import Erdos1135.Tao.Renewal.HoldPoint
import Erdos1135.Tao.Renewal.QFinite
import Erdos1135.Tao.Renewal.SourceListBridge
import Erdos1135.Tao.Fourier.Section7Cancellation
import Erdos1135.Tao.Fourier.Section7SourceFThreeQFinite
import Erdos1135.Tao.Fourier.Section7SourcePairing
import Erdos1135.Tao.Fourier.Section7PairFiber
import Erdos1135.Tao.Fourier.Section7PairExpansion
import Erdos1135.Tao.Fourier.Section7PairExpectation
import UnitSourceTerminalPhase
import UnitSourcePairExpectation
import UnitSourceAffinePMF
import Erdos1135.Tao.Fourier.Section7Geometry
import Erdos1135.Tao.Fourier.Section7SourcePredicates
import Erdos1135.Tao.Fourier.Section7SourceDomain
import Erdos1135.Tao.Probability.PascalPrimeList
import Erdos1135.Tao.Renewal.HoldPMF
import Erdos1135.Tao.Renewal.HoldExpectation
import Erdos1135.Tao.Renewal.HoldIID
import Erdos1135.Tao.Renewal.QExpectation
import Erdos1135.Tao.Renewal.QFiniteApprox
import Erdos1135.Tao.Renewal.QActualRecursion
import Erdos1135.Tao.Renewal.QActualLimit
import Erdos1135.Tao.Renewal.SourceActualQ
import Erdos1135.Tao.Renewal.SourceCutoffStabilization
import Erdos1135.Tao.Renewal.SourceRegeneration
import UnitSourceEnvelopeActualQ
import Erdos1135.Tao.Fourier.Section7SChiActualQ
import Erdos1135.Tao.Renewal.Outer736SourceAlgebra
import Erdos1135.Tao.Renewal.Prop78Case1Scalar
import Erdos1135.Tao.Renewal.QmStatement
import Erdos1135.Tao.Renewal.Outer736HoldExpectation
import Erdos1135.Tao.Renewal.RenewalPathBasic
import Erdos1135.Tao.Renewal.VerticalFirstPassageBasic
import Erdos1135.Tao.Renewal.HoldFirstPassagePMF
import Erdos1135.Tao.Renewal.Lemma77PotentialCore
import Erdos1135.Tao.Renewal.CanonicalFirstPassageEndpoint
import Erdos1135.Tao.Renewal.HoldStoppedTail
import Erdos1135.Tao.Renewal.SeparatedWindowSum
import Erdos1135.Tao.Renewal.Lemma710KernelWindow
import Erdos1135.Tao.Renewal.Prop78Case3Event
import Erdos1135.Tao.Renewal.Prop78Case3TriangleExit
import Erdos1135.Tao.Renewal.GeometryBridge
import Erdos1135.Tao.Renewal.PathGrowth
import Erdos1135.Tao.Renewal.SourcePathData
import Erdos1135.Tao.Renewal.Prop78Case3ActiveTriangle
import Erdos1135.Tao.Renewal.Prop78Case3CutoffAlignment
import Erdos1135.Tao.Renewal.Prop78Case3Stopping
import Erdos1135.Tao.Renewal.Lemma710PostStoppedKernel
import Erdos1135.Tao.Renewal.Lemma77HighJ
import Erdos1135.Tao.Renewal.Lemma710EprimeProbability
import Erdos1135.Tao.Renewal.Lemma710Complementary
import Erdos1135.Tao.Section6.Corollary63
import Erdos1135.Tao.Renewal.Lemma77KernelTail
import Erdos1135.Tao.Renewal.Lemma77SourceFiber
import Erdos1135.Tao.Renewal.Lemma77HorizontalMarginal
import Erdos1135.Tao.Renewal.Lemma77LocalLimit
import Erdos1135.Tao.Renewal.Lemma77FirstPassageEndpoint
import Erdos1135.Tao.Renewal.Lemma77EndpointAssembly
import Erdos1135.Tao.Renewal.CanonicalFirstPassageTerminal
import Erdos1135.Tao.Renewal.Lemma77PascalPotential
import Erdos1135.Tao.Renewal.Lemma77PascalComposition
import Erdos1135.Tao.Renewal.Lemma77PascalFormula
import Erdos1135.Tao.Renewal.Lemma77PascalGaussian
import Erdos1135.Tao.Probability.HoldMass
import Erdos1135.Tao.Probability.HoldExpWeight
import Erdos1135.Tao.Renewal.Lemma77TerminalHoldMoment
import Erdos1135.Tao.Renewal.CanonicalFirstPassagePointwise
import Erdos1135.Tao.Renewal.CanonicalFirstPassageHorizontal
import Erdos1135.Tao.Renewal.CanonicalFirstPassageTails
import Erdos1135.Tao.Renewal.CanonicalFirstPassageLocalizedMass
import Erdos1135.Tao.Renewal.Prop78Boundary
import Erdos1135.Tao.Renewal.Prop78Threshold
import Erdos1135.Tao.Renewal.Prop78CaseAssembly
import Erdos1135.Tao.Fourier.Lemma74ThetaArithmetic
import Erdos1135.Tao.Fourier.Lemma74SoutheastTransport
import Erdos1135.Tao.Fourier.Lemma74PrimitiveStrip
import Erdos1135.Tao.Fourier.Lemma74ClaimStarScalars
import Erdos1135.Tao.Fourier.Lemma74CanonicalRaw
import Erdos1135.Tao.Fourier.Lemma74ClaimStarMetric
import Erdos1135.Tao.Fourier.Lemma74ClaimStarPropagation
import Erdos1135.Tao.Fourier.Lemma74CanonicalClaimStar
import Erdos1135.Tao.Fourier.Lemma74CanonicalSourceMem
import Erdos1135.Tao.Fourier.Lemma74CanonicalCoherence
import Erdos1135.Tao.Fourier.Lemma74CanonicalFamily
import Erdos1135.Tao.Renewal.Prop78ActiveCover
import Erdos1135.Tao.Renewal.Prop78Case2Geometry
import Erdos1135.Tao.Renewal.Prop78Case3EStarSupportProducer
import Erdos1135.Tao.Renewal.Prop78Case3BaseKcutFiniteSum
import Erdos1135.Tao.Renewal.Prop78Case3BaseKcutScheduleExistence
import Erdos1135.Tao.Renewal.Prop78Case2Discount
import Erdos1135.Tao.Renewal.Lemma79TailExpectationCore
import Erdos1135.Tao.Renewal.QPrefixFactor
import Erdos1135.Tao.Renewal.QStoppedApprox
import Erdos1135.Tao.Renewal.PMFExpectationThreeRegion
import Erdos1135.Tao.Renewal.Outer754HorizontalFactor
import Erdos1135.Tao.Renewal.Outer754SourceWeight
import Erdos1135.Tao.Renewal.Lemma79InclusiveTrace
import Erdos1135.Tao.Renewal.Lemma79CutoffLocality
import Erdos1135.Tao.Renewal.Lemma79FirstEntryCylinder
import Erdos1135.Tao.Renewal.Lemma79FirstEntryFiberLaw
import Erdos1135.Tao.Renewal.HoldListHorizontalMoment
import Erdos1135.Tao.Renewal.CanonicalFirstPassageExpMoment
import Erdos1135.Tao.Renewal.Lemma79FirstEntryEndpointLaw
import Erdos1135.Tao.Renewal.Lemma79CutoffStatistic
import Erdos1135.Tao.Renewal.Lemma79Restart
import Erdos1135.Tao.Renewal.Lemma79FirstExit
import Erdos1135.Tao.Renewal.Lemma79FirstEntryCount
import Erdos1135.Tao.Renewal.Lemma79Recurrence
import Erdos1135.Tao.Renewal.Lemma79R2Pointwise
import Erdos1135.Tao.Renewal.Lemma79ClockDeath
import Erdos1135.Tao.Renewal.Lemma79R2MasterAtom
import Erdos1135.Tao.Renewal.Lemma79R2Aggregation
import Erdos1135.Tao.Renewal.Lemma79PostExitFreshTail
import Erdos1135.Tao.Renewal.Lemma79R3MasterAtom
import Erdos1135.Tao.Renewal.Lemma79CanonicalExitWhite
import Erdos1135.Tao.Renewal.Lemma79R2Scalar
import Erdos1135.Tao.Renewal.Lemma79R2EndpointContraction
import Erdos1135.Tao.Renewal.Lemma79R2EndpointExpectation
import Erdos1135.Tao.Renewal.Lemma79R3Prefix
import Erdos1135.Tao.Renewal.Lemma79R2MasterTransport
import Erdos1135.Tao.Renewal.Lemma79R3Pointwise
import Erdos1135.Tao.Renewal.Lemma79R2PositiveKey
import Erdos1135.Tao.Renewal.Lemma79R3AtomBound
import Erdos1135.Tao.Renewal.Lemma79R2PositiveKeyBound
import Erdos1135.Tao.Renewal.Lemma79OneStepBound
import Erdos1135.Tao.Renewal.Lemma79AllRBound
import Erdos1135.Tao.Renewal.Lemma79EndpointFreshCoordinates
import Erdos1135.Tao.Renewal.Lemma79EndpointFreshLaw
import Erdos1135.Tao.Renewal.Prop78Case1White
import Erdos1135.Tao.Renewal.QmHorizontalNormalization
import Erdos1135.Tao.Renewal.QEndpointFreshDomain
import Erdos1135.Tao.Renewal.QEndpointFreshCount
import Erdos1135.Tao.Renewal.QStoppedEndpoint
import Erdos1135.Tao.Renewal.QFiniteIteration
import Erdos1135.Tao.Renewal.SourceActualQIteration
import Erdos1135.Tao.Renewal.QEndpointFreshTower
import Erdos1135.Tao.Renewal.QEndpointFreshCloseout
import Erdos1135.Tao.Renewal.QEndpointFreshPriorityPartition
import Erdos1135.Tao.Renewal.QEndpointFreshSupport
import Erdos1135.Tao.Renewal.Lemma79CanonicalTraceProjection
import Erdos1135.Tao.Renewal.Lemma79NativeMarkov
import Erdos1135.Tao.Renewal.Lemma79Case3EventAdapter
import Erdos1135.Tao.Renewal.QEndpointFreshSurvival
import Erdos1135.Tao.Renewal.Prop78Case3FixedParameters
import Erdos1135.Tao.Renewal.QEndpointFreshEStarMass
import Erdos1135.Tao.Renewal.QEndpointFreshEStarFiber
import Erdos1135.Tao.Renewal.QEndpointFreshEStarEprime
import Erdos1135.Tao.Renewal.QEndpointFreshMarginals
import Erdos1135.Tao.Renewal.QEndpointFreshEprimeFourTail
import Erdos1135.Tao.Renewal.HoldListVerticalTail
import Erdos1135.Tao.Renewal.Prop78Case2MomentScalar
import Erdos1135.Tao.Renewal.HoldListHorizontalTail
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeNearSigma
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeFiber
import Erdos1135.Tao.Renewal.PMFIntWindowUnion
import Erdos1135.Tao.Renewal.CanonicalFirstPassageSignedSparse
import Erdos1135.Tao.Renewal.SeparatedWindowGeometry
import Erdos1135.Tao.Renewal.CanonicalFirstPassageSignedAverage
import Erdos1135.Tao.Renewal.CanonicalFirstPassageSignedTotal
import Erdos1135.Tao.Renewal.SeparatedWindowFlattening
import Erdos1135.Tao.Renewal.CanonicalFirstPassageSignedCenterSum
import Erdos1135.Tao.Renewal.CanonicalFirstPassageSigmaCenters
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeWindow
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeHorizontal
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeMass
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeScalar
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeWidth
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeSourceWidth
import Erdos1135.Tao.Renewal.QEndpointFreshEprimeMasterWidth
import Erdos1135.Tao.Renewal.QEndpointFreshEprimeHorizontalTail
import Erdos1135.Tao.Renewal.QEndpointFreshEprimeMarginalMass
import Erdos1135.Tao.Renewal.QEndpointFreshEprimeLargeBranch
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeSourceMargin
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeSourceMarginCap
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeBudget
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeNative
import Erdos1135.Tao.Renewal.QEndpointFreshEStarFixedOffset
import Erdos1135.Tao.Renewal.QEndpointFreshEStarCountable
import Erdos1135.Tao.Renewal.QEndpointFreshEStarUniform
import Erdos1135.Tao.Renewal.Prop78AbsolutePacket
import Erdos1135.Tao.Renewal.Prop78Case2EndpointSplit
import Erdos1135.Tao.Renewal.Prop78Case2Pointwise
import Erdos1135.Tao.Renewal.Prop78Case2Expectation
import Erdos1135.Tao.Renewal.Prop78Case3EventualScale
import Erdos1135.Tao.Renewal.Prop78Case3PriorityScalar
import Erdos1135.Tao.Renewal.QEndpointFreshPairFSlack
import Erdos1135.Tao.Renewal.QEndpointFreshMiddleMass
import Erdos1135.Tao.Renewal.QEndpointFreshOuterBadJ
import Erdos1135.Tao.Renewal.QEndpointFreshOuterBadJAbsorption
import Erdos1135.Tao.Renewal.Prop78Case3ActiveCoverStopping
import Erdos1135.Tao.Renewal.QEndpointFreshOuterBadJBoundary
import Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeBoundary
import Erdos1135.Tao.Renewal.Prop78Case3CanonicalFarBelow
import Erdos1135.Tao.Renewal.Prop78CanonicalAssembly
import Erdos1135.Tao.Renewal.Prop78Pointwise737
import Erdos1135.Tao.Fourier.Prop71CanonicalAssembly
import UnitSourcePrimitiveFourier
import Erdos1135.Tao.Section6.ConductorDFT
import Erdos1135.Tao.Section6.ConductorIndex
import Erdos1135.Tao.Section6.ConductorFrequency
import Erdos1135.Tao.Section6.AmbientTailDFT
import Erdos1135.Tao.Section6.AmbientOffsetAppend
import UnitSourceProjection
import Erdos1135.Tao.Section6.AmbientTailDecay
import UnitSourceTailDecay
import UnitSourceAppend
import Erdos1135.Tao.Probability.GatedSubmass
import Erdos1135.Tao.Section6.FiniteFourierConvolution
import Erdos1135.Tao.Section6.OptionHeadTailConvolution
import Erdos1135.Tao.Section6.HeadGate
import Erdos1135.Tao.Section6.HeadGateLocalization
import Erdos1135.Tao.Section6.HeadSubmass
import Erdos1135.Tao.Section6.Cor63HeadPrefix
import Erdos1135.Tao.Fourier.MixingStatement
import Erdos1135.Tao.Section6.GatedSourceConvolution
import UnitSourceGatedConvolution
import Erdos1135.Tao.Section6.FiberAverageDFT
import Erdos1135.Tao.Section6.FiniteFourierParseval
import Erdos1135.Tao.Section6.FiniteFourierCollision
import Erdos1135.Tao.Section6.FixedSliceCollision
import Erdos1135.Tao.Section6.HeadGateIndex
import Erdos1135.Tao.Section6.FixedSliceSource
import Erdos1135.Tao.Section6.HeadEntropyScalar
import Erdos1135.Tao.Section6.FixedSlicePolynomial
import UnitSourceFixedSlice
import Erdos1135.Tao.Probability.GatedSubmassPartition
import Erdos1135.Tao.Probability.GatedSubmassComplement
import Erdos1135.Tao.Fourier.OscillationAlgebra
import Erdos1135.Tao.Section6.GlobalTypicalEvent
import Erdos1135.Tao.Section6.FirstCrossingPartition
import Erdos1135.Tao.Section6.FixedAmbientSlice
import Erdos1135.Tao.Section6.GatePartition
import Erdos1135.Tao.Section6.EventAggregation
import UnitSourceMappedAggregation
import Erdos1135.Tao.Probability.CountableMarkov
import Erdos1135.Tao.Probability.Geom2CenteredMoment
import Erdos1135.Tao.Probability.Geom2ListProjectivity
import Erdos1135.Tao.Section6.Geom2IntervalConcentration
import Erdos1135.Tao.Section6.HighRegimeMixing
import UnitSourceHighRegimeMixing
import Erdos1135.Tao.Section6.UniformLift
import Erdos1135.Tao.Section6.AdjacentOneStep
import UnitSourceNativeLawComparison
import UnitSourceAffineForward
import UnitSourceForwardDensity
import UnitSourceDensityComparison
import CanonicalSyracLawBridge
import UnitSourcePadicDensityComparison
import Erdos1135.Tao.Section6.AdjacentTelescope
import Erdos1135.Tao.Section6.InversePowerTail
import Erdos1135.Tao.Section6.HighRegimeAllScale
import Erdos1135.Tao.Section6.GlobalOscillationBound
import Erdos1135.Tao.Section6.Prop117ToProp114
import Erdos1135.Tao.Section6.Prop114Assembly
import Erdos1135.Tao.Fourier.Prop114CanonicalAssembly
import CanonicalHaarTwoScale
import CanonicalHaarDensity
import CanonicalHaarLimitIdentification
import CanonicalHaarLp
import PadicAffineBranch
import PadicAffineHaar
import PadicHaarLift
import CanonicalHaarStationarity
import StationarySupportOverlap
import CanonicalHaarNotL2
import Lean

set_option maxRecDepth 100000
set_option maxHeartbeats 0

open Lean Elab Command in
run_cmd do
  let env := (← getEnv).setExporting false
  let wanted : List String := ["CanonicalLpInterpolation", "OptimalCylinderPacking", "AdmissibleCylinderWords", "CylinderLowerBranch", "ArithmeticInverseBlocks", "GeometricWordTail", "ArithmeticInverseTuples", "ArithmeticWordFibers", "CylinderHeadBound", "CylinderExpansionBound", "ArithmeticCylinderLaw", "ArithmeticCylinderResidues", "ArithmeticCylinderCongruence", "ArithmeticCylinderLower", "FiniteCylinderResidueLaw", "FairEnergyWordCore", "FormalConjectures.Util.ProblemImports", "FormalConjectures.Wikipedia.CollatzConjecture", "Erdos1135.Basic", "Erdos1135.CollatzStep", "Erdos1135.Parity", "Erdos1135.Division", "Erdos1135.Terras.Core.Defs", "Erdos1135.Tao.Syracuse.Defs", "Erdos1135.Tao.Syracuse.Basic", "Erdos1135.Tao.Syracuse.Affine", "Erdos1135.Tao.Syracuse.OffsetInjectivity", "Erdos1135.Tao.Syracuse.AffineReverse", "FairEnergyWordReversal", "FairEnergyWordSeparation", "HarmonicFiberBounds", "FairEnergyFinite", "FairEnergyMoments", "FairEnergyLimit", "FiniteSyracuseSeries", "FiniteSyracuseSeriesClosedForm", "CompatibleSyracuseResidues", "PadicSyracuseVariable", "GeometricSequenceLaw", "SyracuseVariableMeasurable", "FiniteCylinderMaximum", "OptimalFiniteCylinderRate", "CanonicalSyracuseCylinderLaw", "FairEnergyBound", "QuotientFiberBounds", "FairEnergyQuadraticFinite", "FairEnergyQuadraticBound", "Erdos1135.Tao.Probability.Finite", "Erdos1135.Tao.Probability.Geom", "Erdos1135.Tao.Probability.Truncation", "Erdos1135.Terras.Parity.Word", "Erdos1135.Tao.Syracuse.ParityBridge", "Erdos1135.Residues", "Erdos1135.TwoAdic", "Erdos1135.Terras.Parity.Residue", "Erdos1135.Tao.Syracuse.Residue", "Erdos1135.Tao.Syracuse.ValuationCylinder", "Erdos1135.Tao.Syracuse.ValuationCylinderResidue", "Erdos1135.Tao.Syracuse.CylinderMass", "Erdos1135.Tao.Syracuse.ValuationDistribution", "Erdos1135.Tao.Syracuse.Syrac", "Erdos1135.Tao.Fourier.Basic", "Erdos1135.Tao.Fourier.TV", "Erdos1135.Tao.Fourier.DecayStatement", "Erdos1135.Tao.Probability.Pascal", "Erdos1135.Tao.Fourier.Section7Character", "Erdos1135.Tao.Fourier.Section7SourceLaw", "Erdos1135.Tao.Section6.ModulusProjection", "Erdos1135.Tao.Section6.ConductorProjectivity", "UnitSourceUniformSeed", "CanonicalSyracuseSeries", "CanonicalSyracuseRecursion", "GeometricSequenceSplit", "CanonicalSyracuseStationarity", "PadicCylinderDetermining", "SyracuseCylinderTransitions", "PadicHaarCylinder", "CanonicalSyracuseUnique", "WeightedKernelLimit", "CesaroAbelLimit", "EndpointTailBounds", "ArithmeticCylinderGrowth", "CanonicalCylinderAbel", "FinitePathInverseWords", "OrbitCorrectionProduct", "FirstHitWordWeights", "HittingTimeClassification", "ActualCycleWeights", "ActualInverseOperator", "CanonicalCylinderRecursion", "CanonicalPadicCylinderRecursion", "CanonicalHaarEnergy", "UnitHaarCylinder", "Erdos1135.Tao.Fourier.Section7ProductPenalty", "Erdos1135.Tao.Probability.PascalPrime", "Erdos1135.Tao.Fourier.Section7WhiteHitSplit", "Erdos1135.Tao.Renewal.HoldPoint", "Erdos1135.Tao.Renewal.QFinite", "Erdos1135.Tao.Renewal.SourceListBridge", "Erdos1135.Tao.Fourier.Section7Cancellation", "Erdos1135.Tao.Fourier.Section7SourceFThreeQFinite", "Erdos1135.Tao.Fourier.Section7SourcePairing", "Erdos1135.Tao.Fourier.Section7PairFiber", "Erdos1135.Tao.Fourier.Section7PairExpansion", "Erdos1135.Tao.Fourier.Section7PairExpectation", "UnitSourceTerminalPhase", "UnitSourcePairExpectation", "UnitSourceAffinePMF", "Erdos1135.Tao.Fourier.Section7Geometry", "Erdos1135.Tao.Fourier.Section7SourcePredicates", "Erdos1135.Tao.Fourier.Section7SourceDomain", "Erdos1135.Tao.Probability.PascalPrimeList", "Erdos1135.Tao.Renewal.HoldPMF", "Erdos1135.Tao.Renewal.HoldExpectation", "Erdos1135.Tao.Renewal.HoldIID", "Erdos1135.Tao.Renewal.QExpectation", "Erdos1135.Tao.Renewal.QFiniteApprox", "Erdos1135.Tao.Renewal.QActualRecursion", "Erdos1135.Tao.Renewal.QActualLimit", "Erdos1135.Tao.Renewal.SourceActualQ", "Erdos1135.Tao.Renewal.SourceCutoffStabilization", "Erdos1135.Tao.Renewal.SourceRegeneration", "UnitSourceEnvelopeActualQ", "Erdos1135.Tao.Fourier.Section7SChiActualQ", "Erdos1135.Tao.Renewal.Outer736SourceAlgebra", "Erdos1135.Tao.Renewal.Prop78Case1Scalar", "Erdos1135.Tao.Renewal.QmStatement", "Erdos1135.Tao.Renewal.Outer736HoldExpectation", "Erdos1135.Tao.Renewal.RenewalPathBasic", "Erdos1135.Tao.Renewal.VerticalFirstPassageBasic", "Erdos1135.Tao.Renewal.HoldFirstPassagePMF", "Erdos1135.Tao.Renewal.Lemma77PotentialCore", "Erdos1135.Tao.Renewal.CanonicalFirstPassageEndpoint", "Erdos1135.Tao.Renewal.HoldStoppedTail", "Erdos1135.Tao.Renewal.SeparatedWindowSum", "Erdos1135.Tao.Renewal.Lemma710KernelWindow", "Erdos1135.Tao.Renewal.Prop78Case3Event", "Erdos1135.Tao.Renewal.Prop78Case3TriangleExit", "Erdos1135.Tao.Renewal.GeometryBridge", "Erdos1135.Tao.Renewal.PathGrowth", "Erdos1135.Tao.Renewal.SourcePathData", "Erdos1135.Tao.Renewal.Prop78Case3ActiveTriangle", "Erdos1135.Tao.Renewal.Prop78Case3CutoffAlignment", "Erdos1135.Tao.Renewal.Prop78Case3Stopping", "Erdos1135.Tao.Renewal.Lemma710PostStoppedKernel", "Erdos1135.Tao.Renewal.Lemma77HighJ", "Erdos1135.Tao.Renewal.Lemma710EprimeProbability", "Erdos1135.Tao.Renewal.Lemma710Complementary", "Erdos1135.Tao.Section6.Corollary63", "Erdos1135.Tao.Renewal.Lemma77KernelTail", "Erdos1135.Tao.Renewal.Lemma77SourceFiber", "Erdos1135.Tao.Renewal.Lemma77HorizontalMarginal", "Erdos1135.Tao.Renewal.Lemma77LocalLimit", "Erdos1135.Tao.Renewal.Lemma77FirstPassageEndpoint", "Erdos1135.Tao.Renewal.Lemma77EndpointAssembly", "Erdos1135.Tao.Renewal.CanonicalFirstPassageTerminal", "Erdos1135.Tao.Renewal.Lemma77PascalPotential", "Erdos1135.Tao.Renewal.Lemma77PascalComposition", "Erdos1135.Tao.Renewal.Lemma77PascalFormula", "Erdos1135.Tao.Renewal.Lemma77PascalGaussian", "Erdos1135.Tao.Probability.HoldMass", "Erdos1135.Tao.Probability.HoldExpWeight", "Erdos1135.Tao.Renewal.Lemma77TerminalHoldMoment", "Erdos1135.Tao.Renewal.CanonicalFirstPassagePointwise", "Erdos1135.Tao.Renewal.CanonicalFirstPassageHorizontal", "Erdos1135.Tao.Renewal.CanonicalFirstPassageTails", "Erdos1135.Tao.Renewal.CanonicalFirstPassageLocalizedMass", "Erdos1135.Tao.Renewal.Prop78Boundary", "Erdos1135.Tao.Renewal.Prop78Threshold", "Erdos1135.Tao.Renewal.Prop78CaseAssembly", "Erdos1135.Tao.Fourier.Lemma74ThetaArithmetic", "Erdos1135.Tao.Fourier.Lemma74SoutheastTransport", "Erdos1135.Tao.Fourier.Lemma74PrimitiveStrip", "Erdos1135.Tao.Fourier.Lemma74ClaimStarScalars", "Erdos1135.Tao.Fourier.Lemma74CanonicalRaw", "Erdos1135.Tao.Fourier.Lemma74ClaimStarMetric", "Erdos1135.Tao.Fourier.Lemma74ClaimStarPropagation", "Erdos1135.Tao.Fourier.Lemma74CanonicalClaimStar", "Erdos1135.Tao.Fourier.Lemma74CanonicalSourceMem", "Erdos1135.Tao.Fourier.Lemma74CanonicalCoherence", "Erdos1135.Tao.Fourier.Lemma74CanonicalFamily", "Erdos1135.Tao.Renewal.Prop78ActiveCover", "Erdos1135.Tao.Renewal.Prop78Case2Geometry", "Erdos1135.Tao.Renewal.Prop78Case3EStarSupportProducer", "Erdos1135.Tao.Renewal.Prop78Case3BaseKcutFiniteSum", "Erdos1135.Tao.Renewal.Prop78Case3BaseKcutScheduleExistence", "Erdos1135.Tao.Renewal.Prop78Case2Discount", "Erdos1135.Tao.Renewal.Lemma79TailExpectationCore", "Erdos1135.Tao.Renewal.QPrefixFactor", "Erdos1135.Tao.Renewal.QStoppedApprox", "Erdos1135.Tao.Renewal.PMFExpectationThreeRegion", "Erdos1135.Tao.Renewal.Outer754HorizontalFactor", "Erdos1135.Tao.Renewal.Outer754SourceWeight", "Erdos1135.Tao.Renewal.Lemma79InclusiveTrace", "Erdos1135.Tao.Renewal.Lemma79CutoffLocality", "Erdos1135.Tao.Renewal.Lemma79FirstEntryCylinder", "Erdos1135.Tao.Renewal.Lemma79FirstEntryFiberLaw", "Erdos1135.Tao.Renewal.HoldListHorizontalMoment", "Erdos1135.Tao.Renewal.CanonicalFirstPassageExpMoment", "Erdos1135.Tao.Renewal.Lemma79FirstEntryEndpointLaw", "Erdos1135.Tao.Renewal.Lemma79CutoffStatistic", "Erdos1135.Tao.Renewal.Lemma79Restart", "Erdos1135.Tao.Renewal.Lemma79FirstExit", "Erdos1135.Tao.Renewal.Lemma79FirstEntryCount", "Erdos1135.Tao.Renewal.Lemma79Recurrence", "Erdos1135.Tao.Renewal.Lemma79R2Pointwise", "Erdos1135.Tao.Renewal.Lemma79ClockDeath", "Erdos1135.Tao.Renewal.Lemma79R2MasterAtom", "Erdos1135.Tao.Renewal.Lemma79R2Aggregation", "Erdos1135.Tao.Renewal.Lemma79PostExitFreshTail", "Erdos1135.Tao.Renewal.Lemma79R3MasterAtom", "Erdos1135.Tao.Renewal.Lemma79CanonicalExitWhite", "Erdos1135.Tao.Renewal.Lemma79R2Scalar", "Erdos1135.Tao.Renewal.Lemma79R2EndpointContraction", "Erdos1135.Tao.Renewal.Lemma79R2EndpointExpectation", "Erdos1135.Tao.Renewal.Lemma79R3Prefix", "Erdos1135.Tao.Renewal.Lemma79R2MasterTransport", "Erdos1135.Tao.Renewal.Lemma79R3Pointwise", "Erdos1135.Tao.Renewal.Lemma79R2PositiveKey", "Erdos1135.Tao.Renewal.Lemma79R3AtomBound", "Erdos1135.Tao.Renewal.Lemma79R2PositiveKeyBound", "Erdos1135.Tao.Renewal.Lemma79OneStepBound", "Erdos1135.Tao.Renewal.Lemma79AllRBound", "Erdos1135.Tao.Renewal.Lemma79EndpointFreshCoordinates", "Erdos1135.Tao.Renewal.Lemma79EndpointFreshLaw", "Erdos1135.Tao.Renewal.Prop78Case1White", "Erdos1135.Tao.Renewal.QmHorizontalNormalization", "Erdos1135.Tao.Renewal.QEndpointFreshDomain", "Erdos1135.Tao.Renewal.QEndpointFreshCount", "Erdos1135.Tao.Renewal.QStoppedEndpoint", "Erdos1135.Tao.Renewal.QFiniteIteration", "Erdos1135.Tao.Renewal.SourceActualQIteration", "Erdos1135.Tao.Renewal.QEndpointFreshTower", "Erdos1135.Tao.Renewal.QEndpointFreshCloseout", "Erdos1135.Tao.Renewal.QEndpointFreshPriorityPartition", "Erdos1135.Tao.Renewal.QEndpointFreshSupport", "Erdos1135.Tao.Renewal.Lemma79CanonicalTraceProjection", "Erdos1135.Tao.Renewal.Lemma79NativeMarkov", "Erdos1135.Tao.Renewal.Lemma79Case3EventAdapter", "Erdos1135.Tao.Renewal.QEndpointFreshSurvival", "Erdos1135.Tao.Renewal.Prop78Case3FixedParameters", "Erdos1135.Tao.Renewal.QEndpointFreshEStarMass", "Erdos1135.Tao.Renewal.QEndpointFreshEStarFiber", "Erdos1135.Tao.Renewal.QEndpointFreshEStarEprime", "Erdos1135.Tao.Renewal.QEndpointFreshMarginals", "Erdos1135.Tao.Renewal.QEndpointFreshEprimeFourTail", "Erdos1135.Tao.Renewal.HoldListVerticalTail", "Erdos1135.Tao.Renewal.Prop78Case2MomentScalar", "Erdos1135.Tao.Renewal.HoldListHorizontalTail", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeNearSigma", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeFiber", "Erdos1135.Tao.Renewal.PMFIntWindowUnion", "Erdos1135.Tao.Renewal.CanonicalFirstPassageSignedSparse", "Erdos1135.Tao.Renewal.SeparatedWindowGeometry", "Erdos1135.Tao.Renewal.CanonicalFirstPassageSignedAverage", "Erdos1135.Tao.Renewal.CanonicalFirstPassageSignedTotal", "Erdos1135.Tao.Renewal.SeparatedWindowFlattening", "Erdos1135.Tao.Renewal.CanonicalFirstPassageSignedCenterSum", "Erdos1135.Tao.Renewal.CanonicalFirstPassageSigmaCenters", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeWindow", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeHorizontal", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeMass", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeScalar", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeWidth", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeSourceWidth", "Erdos1135.Tao.Renewal.QEndpointFreshEprimeMasterWidth", "Erdos1135.Tao.Renewal.QEndpointFreshEprimeHorizontalTail", "Erdos1135.Tao.Renewal.QEndpointFreshEprimeMarginalMass", "Erdos1135.Tao.Renewal.QEndpointFreshEprimeLargeBranch", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeSourceMargin", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeSourceMarginCap", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeBudget", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeNative", "Erdos1135.Tao.Renewal.QEndpointFreshEStarFixedOffset", "Erdos1135.Tao.Renewal.QEndpointFreshEStarCountable", "Erdos1135.Tao.Renewal.QEndpointFreshEStarUniform", "Erdos1135.Tao.Renewal.Prop78AbsolutePacket", "Erdos1135.Tao.Renewal.Prop78Case2EndpointSplit", "Erdos1135.Tao.Renewal.Prop78Case2Pointwise", "Erdos1135.Tao.Renewal.Prop78Case2Expectation", "Erdos1135.Tao.Renewal.Prop78Case3EventualScale", "Erdos1135.Tao.Renewal.Prop78Case3PriorityScalar", "Erdos1135.Tao.Renewal.QEndpointFreshPairFSlack", "Erdos1135.Tao.Renewal.QEndpointFreshMiddleMass", "Erdos1135.Tao.Renewal.QEndpointFreshOuterBadJ", "Erdos1135.Tao.Renewal.QEndpointFreshOuterBadJAbsorption", "Erdos1135.Tao.Renewal.Prop78Case3ActiveCoverStopping", "Erdos1135.Tao.Renewal.QEndpointFreshOuterBadJBoundary", "Erdos1135.Tao.Renewal.QEndpointFreshOutsideEprimeBoundary", "Erdos1135.Tao.Renewal.Prop78Case3CanonicalFarBelow", "Erdos1135.Tao.Renewal.Prop78CanonicalAssembly", "Erdos1135.Tao.Renewal.Prop78Pointwise737", "Erdos1135.Tao.Fourier.Prop71CanonicalAssembly", "UnitSourcePrimitiveFourier", "Erdos1135.Tao.Section6.ConductorDFT", "Erdos1135.Tao.Section6.ConductorIndex", "Erdos1135.Tao.Section6.ConductorFrequency", "Erdos1135.Tao.Section6.AmbientTailDFT", "Erdos1135.Tao.Section6.AmbientOffsetAppend", "UnitSourceProjection", "Erdos1135.Tao.Section6.AmbientTailDecay", "UnitSourceTailDecay", "UnitSourceAppend", "Erdos1135.Tao.Probability.GatedSubmass", "Erdos1135.Tao.Section6.FiniteFourierConvolution", "Erdos1135.Tao.Section6.OptionHeadTailConvolution", "Erdos1135.Tao.Section6.HeadGate", "Erdos1135.Tao.Section6.HeadGateLocalization", "Erdos1135.Tao.Section6.HeadSubmass", "Erdos1135.Tao.Section6.Cor63HeadPrefix", "Erdos1135.Tao.Fourier.MixingStatement", "Erdos1135.Tao.Section6.GatedSourceConvolution", "UnitSourceGatedConvolution", "Erdos1135.Tao.Section6.FiberAverageDFT", "Erdos1135.Tao.Section6.FiniteFourierParseval", "Erdos1135.Tao.Section6.FiniteFourierCollision", "Erdos1135.Tao.Section6.FixedSliceCollision", "Erdos1135.Tao.Section6.HeadGateIndex", "Erdos1135.Tao.Section6.FixedSliceSource", "Erdos1135.Tao.Section6.HeadEntropyScalar", "Erdos1135.Tao.Section6.FixedSlicePolynomial", "UnitSourceFixedSlice", "Erdos1135.Tao.Probability.GatedSubmassPartition", "Erdos1135.Tao.Probability.GatedSubmassComplement", "Erdos1135.Tao.Fourier.OscillationAlgebra", "Erdos1135.Tao.Section6.GlobalTypicalEvent", "Erdos1135.Tao.Section6.FirstCrossingPartition", "Erdos1135.Tao.Section6.FixedAmbientSlice", "Erdos1135.Tao.Section6.GatePartition", "Erdos1135.Tao.Section6.EventAggregation", "UnitSourceMappedAggregation", "Erdos1135.Tao.Probability.CountableMarkov", "Erdos1135.Tao.Probability.Geom2CenteredMoment", "Erdos1135.Tao.Probability.Geom2ListProjectivity", "Erdos1135.Tao.Section6.Geom2IntervalConcentration", "Erdos1135.Tao.Section6.HighRegimeMixing", "UnitSourceHighRegimeMixing", "Erdos1135.Tao.Section6.UniformLift", "Erdos1135.Tao.Section6.AdjacentOneStep", "UnitSourceNativeLawComparison", "UnitSourceAffineForward", "UnitSourceForwardDensity", "UnitSourceDensityComparison", "CanonicalSyracLawBridge", "UnitSourcePadicDensityComparison", "Erdos1135.Tao.Section6.AdjacentTelescope", "Erdos1135.Tao.Section6.InversePowerTail", "Erdos1135.Tao.Section6.HighRegimeAllScale", "Erdos1135.Tao.Section6.GlobalOscillationBound", "Erdos1135.Tao.Section6.Prop117ToProp114", "Erdos1135.Tao.Section6.Prop114Assembly", "Erdos1135.Tao.Fourier.Prop114CanonicalAssembly", "CanonicalHaarTwoScale", "CanonicalHaarDensity", "CanonicalHaarLimitIdentification", "CanonicalHaarLp", "PadicAffineBranch", "PadicAffineHaar", "PadicHaarLift", "CanonicalHaarStationarity", "StationarySupportOverlap", "CanonicalHaarNotL2"]
  for i in [:env.header.modules.size] do
    let mod := env.header.modules[i]!.module
    if wanted.contains mod.toString then
      unless env.header.modules[i]!.importAll do
        throwError m!"Missing import-all visibility for {mod}"
      let constants := env.header.moduleData[i]!.constNames
      logInfo m!"AUDIT_MODULE|{mod.toString}|{constants.size}"
      for name in constants do
        unless (env.checked.get.find? name).isSome do
          throwError m!"Missing checked constant {name} in {mod}"
        let axioms ← collectAxioms name
        let visibility := if isPrivateName name then "private" else "public"
        let names := String.intercalate "," (axioms.toList.map Name.toString)
        logInfo m!"AUDIT_AXIOMS|{mod.toString}|{name.toString}|{visibility}|{names}"
  let owned := env.checked.get.constants.fold (init := #[]) fun names name _ =>
    match env.getModuleIdxFor? name with
    | none => names
    | some i =>
      if wanted.contains env.header.modules[i.toNat]!.module.toString then
        names.push (i.toNat, name)
      else names
  for (i, name) in owned do
    let mod := env.header.modules[i]!.module
    unless env.header.moduleData[i]!.constNames.contains name do
      throwError m!"Owned constant absent from module header: {mod} / {name}"
    logInfo m!"AUDIT_OWNER|{mod.toString}|{name.toString}"
