import Erdos1135.Tao.Fourier.Section7ProductPenalty
import Erdos1135.Tao.Probability.Finite
import Erdos1135.Tao.Probability.Geom
import Erdos1135.Tao.Probability.Pascal
import Erdos1135.Tao.Probability.PascalPrime
import Erdos1135.Tao.Fourier.Section7WhiteHitSplit
import Erdos1135.Tao.Renewal.HoldPoint
import Erdos1135.Tao.Renewal.QFinite
import Erdos1135.Tao.Renewal.SourceListBridge
import FormalConjectures.Util.ProblemImports
import FormalConjectures.Wikipedia.CollatzConjecture
import Erdos1135.Basic
import Erdos1135.CollatzStep
import Erdos1135.Parity
import Erdos1135.Division
import Erdos1135.Terras.Core.Defs
import Erdos1135.Tao.Syracuse.Defs
import Erdos1135.Tao.Syracuse.Basic
import Erdos1135.Tao.Syracuse.Affine
import Erdos1135.Tao.Probability.Truncation
import Erdos1135.Terras.Parity.Word
import Erdos1135.Tao.Syracuse.ParityBridge
import Erdos1135.Residues
import Erdos1135.TwoAdic
import Erdos1135.Terras.Parity.Residue
import Erdos1135.Tao.Syracuse.Residue
import Erdos1135.Tao.Syracuse.ValuationCylinder
import Erdos1135.Tao.Syracuse.ValuationCylinderResidue
import Erdos1135.Tao.Syracuse.CylinderMass
import Erdos1135.Tao.Syracuse.ValuationDistribution
import Erdos1135.Tao.Syracuse.Syrac
import Erdos1135.Tao.Fourier.Basic
import Erdos1135.Tao.Fourier.TV
import Erdos1135.Tao.Fourier.DecayStatement
import Erdos1135.Tao.Fourier.Section7Character
import Erdos1135.Tao.Fourier.Section7Cancellation
import Erdos1135.Tao.Fourier.Section7SourceFThreeQFinite
import Erdos1135.Tao.Fourier.Section7SourceLaw
import Erdos1135.Tao.Fourier.Section7SourcePairing
import Erdos1135.Tao.Fourier.Section7PairFiber
import Erdos1135.Tao.Fourier.Section7PairExpansion
import Erdos1135.Tao.Fourier.Section7PairExpectation
import UnitSourceTerminalPhase
import UnitSourcePairExpectation
import UnitSourceAffinePMF
import TrapMicrocanonicalSource
import TrapConcentrationScales
import TrapConcentrationChoice
import Erdos1135.Tao.Probability.PascalPrimeList
import Erdos1135.Tao.Renewal.HoldPMF
import Erdos1135.Tao.Renewal.HoldIID
import Erdos1135.Tao.Renewal.SourceRegeneration
import TrapHoldSourceSupport
import TrapBoundedPMFExpectation
import Erdos1135.Tao.Fourier.Section7Geometry
import Erdos1135.Tao.Fourier.Section7SourcePredicates
import Erdos1135.Tao.Fourier.Section7SourceDomain
import TrapNativeShortLaplace
import TrapLaplaceEventBounds
import Erdos1135.Tao.Fourier.Lemma74ThetaArithmetic
import Erdos1135.Tao.Fourier.Lemma74PrimitiveStrip
import TrapReducedModulus
import TrapPrefixTransport
import TrapProductTransport
import TrapPascalPrefixLaw
import TrapNativeEnvelopeRecursion
import TrapDeficitBootstrap
import TrapNativeEnvelopeBootstrap
import TrapNativeQualitativeReduction
import TrapFewWhitePositiveStops
import Erdos1135.Tao.Renewal.RenewalPathBasic
import TrapHoldPathCount
import Erdos1135.Tao.Renewal.HoldExpectation
import Erdos1135.Tao.Renewal.QFiniteApprox
import Erdos1135.Tao.Renewal.HoldStoppedTail
import Erdos1135.Tao.Renewal.SeparatedWindowSum
import Erdos1135.Tao.Renewal.Lemma710KernelWindow
import Erdos1135.Tao.Renewal.Prop78Case3Event
import Erdos1135.Tao.Renewal.Prop78Case3TriangleExit
import Erdos1135.Tao.Renewal.GeometryBridge
import Erdos1135.Tao.Renewal.VerticalFirstPassageBasic
import Erdos1135.Tao.Renewal.PathGrowth
import Erdos1135.Tao.Renewal.SourcePathData
import Erdos1135.Tao.Renewal.Prop78Case3ActiveTriangle
import Erdos1135.Tao.Renewal.QExpectation
import Erdos1135.Tao.Renewal.QActualRecursion
import Erdos1135.Tao.Renewal.QActualLimit
import Erdos1135.Tao.Renewal.SourceActualQ
import Erdos1135.Tao.Renewal.Prop78Case3CutoffAlignment
import Erdos1135.Tao.Renewal.Prop78Case3Stopping
import Erdos1135.Tao.Renewal.Lemma710PostStoppedKernel
import Erdos1135.Tao.Renewal.Lemma77PotentialCore
import Erdos1135.Tao.Renewal.Lemma77HighJ
import Erdos1135.Tao.Renewal.Lemma710EprimeProbability
import Erdos1135.Tao.Renewal.Lemma710Complementary
import Erdos1135.Tao.Syracuse.OffsetInjectivity
import Erdos1135.Tao.Syracuse.AffineReverse
import Erdos1135.Tao.Section6.Corollary63
import Erdos1135.Tao.Renewal.Lemma77KernelTail
import Erdos1135.Tao.Renewal.Lemma77SourceFiber
import Erdos1135.Tao.Renewal.Lemma77HorizontalMarginal
import Erdos1135.Tao.Renewal.Lemma77FirstPassageEndpoint
import Erdos1135.Tao.Renewal.HoldFirstPassagePMF
import Erdos1135.Tao.Renewal.Lemma79TailExpectationCore
import Erdos1135.Tao.Renewal.Lemma79InclusiveTrace
import TrapWhiteGapExtraction
import TrapNativeWhiteGapExtraction
import TrapMicroscopicElimination
import TrapFiniteErrors
import TrapBoundedSpan
import TrapBlockSubsequence
import TrapBoundedCompression
import Erdos1135.Tao.Fourier.Lemma74SoutheastTransport
import TrapBlackCriterion
import TrapCarryIdentities
import TrapTriangleArithmetic
import TrapSlopeAsymptotics
import TrapCarryGrowth
import TrapCoordinateHeight
import DiophantineApproximation.Nonarchimedean
import DiophantineApproximation.PlacesOverFinite
import DiophantineApproximation.PlacesOverInfinite
import DiophantineApproximation.PlacesOver
import DiophantineApproximation.LogComparison
import ArithmeticHeights.Arakelov
import ArithmeticHeights.Extension
import ArithmeticHeights.Absolute
import ArithmeticHeights.Plucker
import ArithmeticHeights.Subspace
import ArithmeticHeights.Affine
import ArithmeticHeights.LinearForm
import ArithmeticHeights.Matrix
import ArithmeticHeights.RowSpace
import ArithmeticHeights.Duality
import ArithmeticHeights.Extraction
import ArithmeticHeights.AdaptedBasis
import ArithmeticHeights.QuotientFubini
import ArithmeticHeights.SuccessiveMinima
import ArithmeticHeights.MinkowskiSecond
import ArithmeticHeights.GaussMeasure
import ArithmeticHeights.PrekopaLeindler
import ArithmeticHeights.LogConcave
import ArithmeticHeights.SliceBound
import ArithmeticHeights.ProductOfBalls
import ArithmeticHeights.CubeSlicing
import ArithmeticHeights.CauchyBinet
import ArithmeticHeights.NormProd
import ArithmeticHeights.MixedLattice
import ArithmeticHeights.PseudoBasis
import ArithmeticHeights.FinitePlaceIdeal
import ArithmeticHeights.GramCovolume
import ArithmeticHeights.NumberFieldLattice
import ArithmeticHeights.MixedBall
import ArithmeticHeights.MixedCube
import ArithmeticHeights.BombieriVaalerMaxNorm
import ArithmeticHeights.Hadamard
import ArithmeticHeights.Nonarchimedean
import ArithmeticHeights.RowEntryHeight
import ArithmeticHeights.BombieriVaalerEntries
import ArithmeticHeights.RestrictScalars
import ArithmeticHeights.BombieriVaalerRelative
import ArithmeticHeights.Polynomial
import DiophantineApproximation.MvHasseDeriv
import DiophantineApproximation.BoxMonomial
import DiophantineApproximation.CountingVolume
import DiophantineApproximation.MvHasseDerivTaylor
import DiophantineApproximation.WeightedOrder
import DiophantineApproximation.PolynomialIndex
import DiophantineApproximation.IndexConditions
import DiophantineApproximation.MvHasseDerivHeight
import DiophantineApproximation.MonomialHeight
import DiophantineApproximation.AuxiliaryPolynomial
import DiophantineApproximation.HeightTransport
import DiophantineApproximation.MvPolynomialEvalBound
import DiophantineApproximation.DisjointVariables
import ArithmeticHeights.GaussLemma
import ArithmeticHeights.Gelfond
import DiophantineApproximation.IndexRename
import DiophantineApproximation.RothBaseCase
import DiophantineApproximation.Wronskian
import DiophantineApproximation.GeneralizedWronskian
import DiophantineApproximation.RothDecomposition
import DiophantineApproximation.PolynomialDeterminantHeight
import DiophantineApproximation.RothDeterminant
import DiophantineApproximation.RothEstimates
import DiophantineApproximation.RothLemma
import DiophantineApproximation.RothAuxiliary
import DiophantineApproximation.ApproximationClass
import DiophantineApproximation.IndependentHeights
import DiophantineApproximation.RothClass
import DiophantineApproximation.FundamentalInequality
import ArithmeticHeights.UnitHeight
import ArithmeticHeights.SUnit
import ArithmeticHeights.SUnitTheorem
import ArithmeticHeights.SRegulator
import DiophantineApproximation.SIntegerLocalization
import DiophantineApproximation.SAdicHeight
import DiophantineApproximation.GlobalBound
import DiophantineApproximation.RothLocalBound
import DiophantineApproximation.RothKeyInequality
import DiophantineApproximation.RothTheorem
import DiophantineApproximation.RothInfinity
import DiophantineApproximation.ProjectiveTarget
import DiophantineApproximation.ApproxProd
import DiophantineApproximation.AffineProd
import DiophantineApproximation.FormBaseChange
import DiophantineApproximation.ConjugatePlaces
import DiophantineApproximation.LocalExtension
import DiophantineApproximation.PlaceConjugation
import DiophantineApproximation.ExtensionApproxProd
import DiophantineApproximation.FinitePlaceValues
import DiophantineApproximation.ModuleCovolume
import DiophantineApproximation.ApproximationDomain
import DiophantineApproximation.RationalPlaces
import DiophantineApproximation.UnitNormalization
import DiophantineApproximation.SubspaceReduction
import DiophantineApproximation.ApproximationVolume
import DiophantineApproximation.FieldMinima
import DiophantineApproximation.FieldMinkowski
import DiophantineApproximation.ApproximationRank
import DiophantineApproximation.WedgeForm
import DiophantineApproximation.SIntegerApproximation
import DiophantineApproximation.EvertseLemma
import DiophantineApproximation.WedgeDomain
import DiophantineApproximation.SubspaceNormal
import DiophantineApproximation.LinearFormValue
import DiophantineApproximation.SubspaceHeightBounds
import DiophantineApproximation.MinimaBounds
import DiophantineApproximation.WedgeExponentBound
import DiophantineApproximation.WedgeRecovery
import DiophantineApproximation.ExponentGrid
import ArithmeticHeights.Northcott
import ArithmeticHeights.NorthcottSubspace
import DiophantineApproximation.ExceptionalSubspace
import DiophantineApproximation.MultiHomogeneous
import DiophantineApproximation.FormIndex
import DiophantineApproximation.PolynomialGrid
import DiophantineApproximation.SmallPoint
import DiophantineApproximation.FormIndexSubspace
import DiophantineApproximation.FormSpecialization
import DiophantineApproximation.GeneralizedRothLemma
import DiophantineApproximation.MonomialDeviation
import DiophantineApproximation.SubspaceAuxiliary
import DiophantineApproximation.SubspaceValueBound
import DiophantineApproximation.SubspaceKeyInequality
import DiophantineApproximation.PenultimateMinimum
import DiophantineApproximation.ParametricSubspace
import DiophantineApproximation.SubspaceTheorem
import DiophantineApproximation.SubspaceAlgebraic
import DiophantineApproximation.SubspaceAffine
import RationalSubspaceBridge
import AsymptoticSubspaceEscape
import TrapCoordinateShear
import RationalSubspaceObstruction
import TrapLocalProduct
import TrapSubspaceForms
import TrapExponentialBounds
import TrapEntropyObstruction
import TrapPatternSelection
import TrapVariableSupportObstruction
import TrapMacroscopicChain
import TrapMacroscopicNative
import TrapBoundedNative
import TrapBoundedUniform
import TrapPathExtraction
import TrapFewWhiteFamily
import TrapCanonicalEntries
import TrapCanonicalTruncation
import TrapCanonicalFewWhite
import Erdos1135.Tao.Renewal.Lemma77LocalLimit
import Erdos1135.Tao.Renewal.Lemma79CutoffLocality
import Erdos1135.Tao.Renewal.Lemma79CutoffStatistic
import Erdos1135.Tao.Renewal.Lemma79CanonicalTraceProjection
import TrapHoldCrossing
import TrapGoodPathForcesStops
import TrapGoodPathFromTube
import TrapNativeStoppedWhiteTail
import TrapOriginalStartTail
import TrapFewWhiteEventReduction
import Erdos1135.Tao.Renewal.Lemma79FirstEntryCylinder
import Erdos1135.Tao.Renewal.Lemma79FirstEntryFiberLaw
import Erdos1135.Tao.Renewal.CanonicalFirstPassageEndpoint
import Erdos1135.Tao.Renewal.Prop78Case1Scalar
import Erdos1135.Tao.Renewal.HoldListHorizontalMoment
import Erdos1135.Tao.Probability.HoldMass
import Erdos1135.Tao.Probability.HoldExpWeight
import Erdos1135.Tao.Renewal.Lemma77EndpointAssembly
import Erdos1135.Tao.Renewal.Lemma77TerminalHoldMoment
import Erdos1135.Tao.Renewal.CanonicalFirstPassageExpMoment
import Erdos1135.Tao.Renewal.Lemma79FirstEntryEndpointLaw
import Erdos1135.Tao.Renewal.Lemma79Restart
import Erdos1135.Tao.Renewal.Lemma79FirstExit
import Erdos1135.Tao.Renewal.Lemma79FirstEntryCount
import Erdos1135.Tao.Renewal.Lemma79Recurrence
import Erdos1135.Tao.Renewal.Lemma79R2Pointwise
import Erdos1135.Tao.Renewal.Lemma79ClockDeath
import Erdos1135.Tao.Renewal.Lemma79R2MasterAtom
import Erdos1135.Tao.Renewal.Lemma79R2Aggregation
import Erdos1135.Tao.Renewal.Lemma79PostExitFreshTail
import Erdos1135.Tao.Renewal.Lemma79R3MasterAtom
import Erdos1135.Tao.Renewal.CanonicalFirstPassageTerminal
import Erdos1135.Tao.Renewal.Lemma77PascalPotential
import Erdos1135.Tao.Renewal.Lemma77PascalComposition
import Erdos1135.Tao.Renewal.Lemma77PascalFormula
import Erdos1135.Tao.Renewal.Lemma77PascalGaussian
import Erdos1135.Tao.Renewal.CanonicalFirstPassagePointwise
import Erdos1135.Tao.Renewal.CanonicalFirstPassageHorizontal
import Erdos1135.Tao.Renewal.CanonicalFirstPassageTails
import Erdos1135.Tao.Renewal.CanonicalFirstPassageLocalizedMass
import Erdos1135.Tao.Renewal.QmStatement
import Erdos1135.Tao.Renewal.Prop78Boundary
import Erdos1135.Tao.Renewal.Prop78Threshold
import Erdos1135.Tao.Renewal.Prop78CaseAssembly
import Erdos1135.Tao.Fourier.Lemma74ClaimStarScalars
import Erdos1135.Tao.Fourier.Lemma74CanonicalRaw
import Erdos1135.Tao.Fourier.Lemma74ClaimStarMetric
import Erdos1135.Tao.Fourier.Lemma74ClaimStarPropagation
import Erdos1135.Tao.Fourier.Lemma74CanonicalClaimStar
import Erdos1135.Tao.Fourier.Lemma74CanonicalSourceMem
import Erdos1135.Tao.Fourier.Lemma74CanonicalCoherence
import Erdos1135.Tao.Fourier.Lemma74CanonicalFamily
import Erdos1135.Tao.Renewal.Prop78ActiveCover
import Erdos1135.Tao.Renewal.Prop78Case2Geometry
import Erdos1135.Tao.Renewal.Lemma79CanonicalExitWhite
import Erdos1135.Tao.Renewal.Lemma79R2Scalar
import Erdos1135.Tao.Renewal.Lemma79R2EndpointContraction
import Erdos1135.Tao.Renewal.Lemma79R2EndpointExpectation
import Erdos1135.Tao.Renewal.Lemma79R3Prefix
import Erdos1135.Tao.Renewal.Lemma79R2MasterTransport
import Erdos1135.Tao.Renewal.Lemma79R3Pointwise
import Erdos1135.Tao.Renewal.Lemma79R2PositiveKey
import Erdos1135.Tao.Renewal.Lemma79R3AtomBound
import Erdos1135.Tao.Renewal.Lemma79R2PositiveKeyBound
import Erdos1135.Tao.Renewal.Lemma79OneStepBound
import Erdos1135.Tao.Renewal.Lemma79AllRBound
import TrapCanonicalStoppedWhiteTail
import TrapGoodPathProbabilityReduction
import TrapPMFEventTransport
import Erdos1135.Tao.Probability.CountableMarkov
import Erdos1135.Tao.Probability.Geom2CenteredMoment
import Erdos1135.Tao.Probability.Geom2ListProjectivity
import Erdos1135.Tao.Probability.Geom2PrefixTypical
import TrapPascalPrefixProbability
import TrapRawPrefixProbability
import TrapHoldIncrementBounds
import TrapHoldIncrementPath
import TrapHoldGoodFromEvents
import TrapSupportedHoldTube
import TrapHoldGoodProbability
import TrapNativeQualitativeDecay
import TrapSeededDeficit
import TrapUnconditionalDeficit
import TrapMicrocanonicalDeficit
import TrapMicrocanonicalMassFloor
import TrapCentralBinomial
import TrapExactExponentMass
import TrapCentralMicrocanonical
import Lean

set_option maxRecDepth 100000
set_option maxHeartbeats 0

open Lean Elab Command in
run_cmd do
  let env ← getEnv
  for i in [:env.header.modules.size] do
    let mod := env.header.modules[i]!.module
    if ["Erdos1135.Tao.Fourier.Section7ProductPenalty", "Erdos1135.Tao.Probability.Finite", "Erdos1135.Tao.Probability.Geom", "Erdos1135.Tao.Probability.Pascal", "Erdos1135.Tao.Probability.PascalPrime", "Erdos1135.Tao.Fourier.Section7WhiteHitSplit", "Erdos1135.Tao.Renewal.HoldPoint", "Erdos1135.Tao.Renewal.QFinite", "Erdos1135.Tao.Renewal.SourceListBridge", "FormalConjectures.Util.ProblemImports", "FormalConjectures.Wikipedia.CollatzConjecture", "Erdos1135.Basic", "Erdos1135.CollatzStep", "Erdos1135.Parity", "Erdos1135.Division", "Erdos1135.Terras.Core.Defs", "Erdos1135.Tao.Syracuse.Defs", "Erdos1135.Tao.Syracuse.Basic", "Erdos1135.Tao.Syracuse.Affine", "Erdos1135.Tao.Probability.Truncation", "Erdos1135.Terras.Parity.Word", "Erdos1135.Tao.Syracuse.ParityBridge", "Erdos1135.Residues", "Erdos1135.TwoAdic", "Erdos1135.Terras.Parity.Residue", "Erdos1135.Tao.Syracuse.Residue", "Erdos1135.Tao.Syracuse.ValuationCylinder", "Erdos1135.Tao.Syracuse.ValuationCylinderResidue", "Erdos1135.Tao.Syracuse.CylinderMass", "Erdos1135.Tao.Syracuse.ValuationDistribution", "Erdos1135.Tao.Syracuse.Syrac", "Erdos1135.Tao.Fourier.Basic", "Erdos1135.Tao.Fourier.TV", "Erdos1135.Tao.Fourier.DecayStatement", "Erdos1135.Tao.Fourier.Section7Character", "Erdos1135.Tao.Fourier.Section7Cancellation", "Erdos1135.Tao.Fourier.Section7SourceFThreeQFinite", "Erdos1135.Tao.Fourier.Section7SourceLaw", "Erdos1135.Tao.Fourier.Section7SourcePairing", "Erdos1135.Tao.Fourier.Section7PairFiber", "Erdos1135.Tao.Fourier.Section7PairExpansion", "Erdos1135.Tao.Fourier.Section7PairExpectation", "UnitSourceTerminalPhase", "UnitSourcePairExpectation", "UnitSourceAffinePMF", "TrapMicrocanonicalSource", "TrapConcentrationScales", "TrapConcentrationChoice", "Erdos1135.Tao.Probability.PascalPrimeList", "Erdos1135.Tao.Renewal.HoldPMF", "Erdos1135.Tao.Renewal.HoldIID", "Erdos1135.Tao.Renewal.SourceRegeneration", "TrapHoldSourceSupport", "TrapBoundedPMFExpectation", "Erdos1135.Tao.Fourier.Section7Geometry", "Erdos1135.Tao.Fourier.Section7SourcePredicates", "Erdos1135.Tao.Fourier.Section7SourceDomain", "TrapNativeShortLaplace", "TrapLaplaceEventBounds", "Erdos1135.Tao.Fourier.Lemma74ThetaArithmetic", "Erdos1135.Tao.Fourier.Lemma74PrimitiveStrip", "TrapReducedModulus", "TrapPrefixTransport", "TrapProductTransport", "TrapPascalPrefixLaw", "TrapNativeEnvelopeRecursion", "TrapDeficitBootstrap", "TrapNativeEnvelopeBootstrap", "TrapNativeQualitativeReduction", "TrapFewWhitePositiveStops", "Erdos1135.Tao.Renewal.RenewalPathBasic", "TrapHoldPathCount", "Erdos1135.Tao.Renewal.HoldExpectation", "Erdos1135.Tao.Renewal.QFiniteApprox", "Erdos1135.Tao.Renewal.HoldStoppedTail", "Erdos1135.Tao.Renewal.SeparatedWindowSum", "Erdos1135.Tao.Renewal.Lemma710KernelWindow", "Erdos1135.Tao.Renewal.Prop78Case3Event", "Erdos1135.Tao.Renewal.Prop78Case3TriangleExit", "Erdos1135.Tao.Renewal.GeometryBridge", "Erdos1135.Tao.Renewal.VerticalFirstPassageBasic", "Erdos1135.Tao.Renewal.PathGrowth", "Erdos1135.Tao.Renewal.SourcePathData", "Erdos1135.Tao.Renewal.Prop78Case3ActiveTriangle", "Erdos1135.Tao.Renewal.QExpectation", "Erdos1135.Tao.Renewal.QActualRecursion", "Erdos1135.Tao.Renewal.QActualLimit", "Erdos1135.Tao.Renewal.SourceActualQ", "Erdos1135.Tao.Renewal.Prop78Case3CutoffAlignment", "Erdos1135.Tao.Renewal.Prop78Case3Stopping", "Erdos1135.Tao.Renewal.Lemma710PostStoppedKernel", "Erdos1135.Tao.Renewal.Lemma77PotentialCore", "Erdos1135.Tao.Renewal.Lemma77HighJ", "Erdos1135.Tao.Renewal.Lemma710EprimeProbability", "Erdos1135.Tao.Renewal.Lemma710Complementary", "Erdos1135.Tao.Syracuse.OffsetInjectivity", "Erdos1135.Tao.Syracuse.AffineReverse", "Erdos1135.Tao.Section6.Corollary63", "Erdos1135.Tao.Renewal.Lemma77KernelTail", "Erdos1135.Tao.Renewal.Lemma77SourceFiber", "Erdos1135.Tao.Renewal.Lemma77HorizontalMarginal", "Erdos1135.Tao.Renewal.Lemma77FirstPassageEndpoint", "Erdos1135.Tao.Renewal.HoldFirstPassagePMF", "Erdos1135.Tao.Renewal.Lemma79TailExpectationCore", "Erdos1135.Tao.Renewal.Lemma79InclusiveTrace", "TrapWhiteGapExtraction", "TrapNativeWhiteGapExtraction", "TrapMicroscopicElimination", "TrapFiniteErrors", "TrapBoundedSpan", "TrapBlockSubsequence", "TrapBoundedCompression", "Erdos1135.Tao.Fourier.Lemma74SoutheastTransport", "TrapBlackCriterion", "TrapCarryIdentities", "TrapTriangleArithmetic", "TrapSlopeAsymptotics", "TrapCarryGrowth", "TrapCoordinateHeight", "DiophantineApproximation.Nonarchimedean", "DiophantineApproximation.PlacesOverFinite", "DiophantineApproximation.PlacesOverInfinite", "DiophantineApproximation.PlacesOver", "DiophantineApproximation.LogComparison", "ArithmeticHeights.Arakelov", "ArithmeticHeights.Extension", "ArithmeticHeights.Absolute", "ArithmeticHeights.Plucker", "ArithmeticHeights.Subspace", "ArithmeticHeights.Affine", "ArithmeticHeights.LinearForm", "ArithmeticHeights.Matrix", "ArithmeticHeights.RowSpace", "ArithmeticHeights.Duality", "ArithmeticHeights.Extraction", "ArithmeticHeights.AdaptedBasis", "ArithmeticHeights.QuotientFubini", "ArithmeticHeights.SuccessiveMinima", "ArithmeticHeights.MinkowskiSecond", "ArithmeticHeights.GaussMeasure", "ArithmeticHeights.PrekopaLeindler", "ArithmeticHeights.LogConcave", "ArithmeticHeights.SliceBound", "ArithmeticHeights.ProductOfBalls", "ArithmeticHeights.CubeSlicing", "ArithmeticHeights.CauchyBinet", "ArithmeticHeights.NormProd", "ArithmeticHeights.MixedLattice", "ArithmeticHeights.PseudoBasis", "ArithmeticHeights.FinitePlaceIdeal", "ArithmeticHeights.GramCovolume", "ArithmeticHeights.NumberFieldLattice", "ArithmeticHeights.MixedBall", "ArithmeticHeights.MixedCube", "ArithmeticHeights.BombieriVaalerMaxNorm", "ArithmeticHeights.Hadamard", "ArithmeticHeights.Nonarchimedean", "ArithmeticHeights.RowEntryHeight", "ArithmeticHeights.BombieriVaalerEntries", "ArithmeticHeights.RestrictScalars", "ArithmeticHeights.BombieriVaalerRelative", "ArithmeticHeights.Polynomial", "DiophantineApproximation.MvHasseDeriv", "DiophantineApproximation.BoxMonomial", "DiophantineApproximation.CountingVolume", "DiophantineApproximation.MvHasseDerivTaylor", "DiophantineApproximation.WeightedOrder", "DiophantineApproximation.PolynomialIndex", "DiophantineApproximation.IndexConditions", "DiophantineApproximation.MvHasseDerivHeight", "DiophantineApproximation.MonomialHeight", "DiophantineApproximation.AuxiliaryPolynomial", "DiophantineApproximation.HeightTransport", "DiophantineApproximation.MvPolynomialEvalBound", "DiophantineApproximation.DisjointVariables", "ArithmeticHeights.GaussLemma", "ArithmeticHeights.Gelfond", "DiophantineApproximation.IndexRename", "DiophantineApproximation.RothBaseCase", "DiophantineApproximation.Wronskian", "DiophantineApproximation.GeneralizedWronskian", "DiophantineApproximation.RothDecomposition", "DiophantineApproximation.PolynomialDeterminantHeight", "DiophantineApproximation.RothDeterminant", "DiophantineApproximation.RothEstimates", "DiophantineApproximation.RothLemma", "DiophantineApproximation.RothAuxiliary", "DiophantineApproximation.ApproximationClass", "DiophantineApproximation.IndependentHeights", "DiophantineApproximation.RothClass", "DiophantineApproximation.FundamentalInequality", "ArithmeticHeights.UnitHeight", "ArithmeticHeights.SUnit", "ArithmeticHeights.SUnitTheorem", "ArithmeticHeights.SRegulator", "DiophantineApproximation.SIntegerLocalization", "DiophantineApproximation.SAdicHeight", "DiophantineApproximation.GlobalBound", "DiophantineApproximation.RothLocalBound", "DiophantineApproximation.RothKeyInequality", "DiophantineApproximation.RothTheorem", "DiophantineApproximation.RothInfinity", "DiophantineApproximation.ProjectiveTarget", "DiophantineApproximation.ApproxProd", "DiophantineApproximation.AffineProd", "DiophantineApproximation.FormBaseChange", "DiophantineApproximation.ConjugatePlaces", "DiophantineApproximation.LocalExtension", "DiophantineApproximation.PlaceConjugation", "DiophantineApproximation.ExtensionApproxProd", "DiophantineApproximation.FinitePlaceValues", "DiophantineApproximation.ModuleCovolume", "DiophantineApproximation.ApproximationDomain", "DiophantineApproximation.RationalPlaces", "DiophantineApproximation.UnitNormalization", "DiophantineApproximation.SubspaceReduction", "DiophantineApproximation.ApproximationVolume", "DiophantineApproximation.FieldMinima", "DiophantineApproximation.FieldMinkowski", "DiophantineApproximation.ApproximationRank", "DiophantineApproximation.WedgeForm", "DiophantineApproximation.SIntegerApproximation", "DiophantineApproximation.EvertseLemma", "DiophantineApproximation.WedgeDomain", "DiophantineApproximation.SubspaceNormal", "DiophantineApproximation.LinearFormValue", "DiophantineApproximation.SubspaceHeightBounds", "DiophantineApproximation.MinimaBounds", "DiophantineApproximation.WedgeExponentBound", "DiophantineApproximation.WedgeRecovery", "DiophantineApproximation.ExponentGrid", "ArithmeticHeights.Northcott", "ArithmeticHeights.NorthcottSubspace", "DiophantineApproximation.ExceptionalSubspace", "DiophantineApproximation.MultiHomogeneous", "DiophantineApproximation.FormIndex", "DiophantineApproximation.PolynomialGrid", "DiophantineApproximation.SmallPoint", "DiophantineApproximation.FormIndexSubspace", "DiophantineApproximation.FormSpecialization", "DiophantineApproximation.GeneralizedRothLemma", "DiophantineApproximation.MonomialDeviation", "DiophantineApproximation.SubspaceAuxiliary", "DiophantineApproximation.SubspaceValueBound", "DiophantineApproximation.SubspaceKeyInequality", "DiophantineApproximation.PenultimateMinimum", "DiophantineApproximation.ParametricSubspace", "DiophantineApproximation.SubspaceTheorem", "DiophantineApproximation.SubspaceAlgebraic", "DiophantineApproximation.SubspaceAffine", "RationalSubspaceBridge", "AsymptoticSubspaceEscape", "TrapCoordinateShear", "RationalSubspaceObstruction", "TrapLocalProduct", "TrapSubspaceForms", "TrapExponentialBounds", "TrapEntropyObstruction", "TrapPatternSelection", "TrapVariableSupportObstruction", "TrapMacroscopicChain", "TrapMacroscopicNative", "TrapBoundedNative", "TrapBoundedUniform", "TrapPathExtraction", "TrapFewWhiteFamily", "TrapCanonicalEntries", "TrapCanonicalTruncation", "TrapCanonicalFewWhite", "Erdos1135.Tao.Renewal.Lemma77LocalLimit", "Erdos1135.Tao.Renewal.Lemma79CutoffLocality", "Erdos1135.Tao.Renewal.Lemma79CutoffStatistic", "Erdos1135.Tao.Renewal.Lemma79CanonicalTraceProjection", "TrapHoldCrossing", "TrapGoodPathForcesStops", "TrapGoodPathFromTube", "TrapNativeStoppedWhiteTail", "TrapOriginalStartTail", "TrapFewWhiteEventReduction", "Erdos1135.Tao.Renewal.Lemma79FirstEntryCylinder", "Erdos1135.Tao.Renewal.Lemma79FirstEntryFiberLaw", "Erdos1135.Tao.Renewal.CanonicalFirstPassageEndpoint", "Erdos1135.Tao.Renewal.Prop78Case1Scalar", "Erdos1135.Tao.Renewal.HoldListHorizontalMoment", "Erdos1135.Tao.Probability.HoldMass", "Erdos1135.Tao.Probability.HoldExpWeight", "Erdos1135.Tao.Renewal.Lemma77EndpointAssembly", "Erdos1135.Tao.Renewal.Lemma77TerminalHoldMoment", "Erdos1135.Tao.Renewal.CanonicalFirstPassageExpMoment", "Erdos1135.Tao.Renewal.Lemma79FirstEntryEndpointLaw", "Erdos1135.Tao.Renewal.Lemma79Restart", "Erdos1135.Tao.Renewal.Lemma79FirstExit", "Erdos1135.Tao.Renewal.Lemma79FirstEntryCount", "Erdos1135.Tao.Renewal.Lemma79Recurrence", "Erdos1135.Tao.Renewal.Lemma79R2Pointwise", "Erdos1135.Tao.Renewal.Lemma79ClockDeath", "Erdos1135.Tao.Renewal.Lemma79R2MasterAtom", "Erdos1135.Tao.Renewal.Lemma79R2Aggregation", "Erdos1135.Tao.Renewal.Lemma79PostExitFreshTail", "Erdos1135.Tao.Renewal.Lemma79R3MasterAtom", "Erdos1135.Tao.Renewal.CanonicalFirstPassageTerminal", "Erdos1135.Tao.Renewal.Lemma77PascalPotential", "Erdos1135.Tao.Renewal.Lemma77PascalComposition", "Erdos1135.Tao.Renewal.Lemma77PascalFormula", "Erdos1135.Tao.Renewal.Lemma77PascalGaussian", "Erdos1135.Tao.Renewal.CanonicalFirstPassagePointwise", "Erdos1135.Tao.Renewal.CanonicalFirstPassageHorizontal", "Erdos1135.Tao.Renewal.CanonicalFirstPassageTails", "Erdos1135.Tao.Renewal.CanonicalFirstPassageLocalizedMass", "Erdos1135.Tao.Renewal.QmStatement", "Erdos1135.Tao.Renewal.Prop78Boundary", "Erdos1135.Tao.Renewal.Prop78Threshold", "Erdos1135.Tao.Renewal.Prop78CaseAssembly", "Erdos1135.Tao.Fourier.Lemma74ClaimStarScalars", "Erdos1135.Tao.Fourier.Lemma74CanonicalRaw", "Erdos1135.Tao.Fourier.Lemma74ClaimStarMetric", "Erdos1135.Tao.Fourier.Lemma74ClaimStarPropagation", "Erdos1135.Tao.Fourier.Lemma74CanonicalClaimStar", "Erdos1135.Tao.Fourier.Lemma74CanonicalSourceMem", "Erdos1135.Tao.Fourier.Lemma74CanonicalCoherence", "Erdos1135.Tao.Fourier.Lemma74CanonicalFamily", "Erdos1135.Tao.Renewal.Prop78ActiveCover", "Erdos1135.Tao.Renewal.Prop78Case2Geometry", "Erdos1135.Tao.Renewal.Lemma79CanonicalExitWhite", "Erdos1135.Tao.Renewal.Lemma79R2Scalar", "Erdos1135.Tao.Renewal.Lemma79R2EndpointContraction", "Erdos1135.Tao.Renewal.Lemma79R2EndpointExpectation", "Erdos1135.Tao.Renewal.Lemma79R3Prefix", "Erdos1135.Tao.Renewal.Lemma79R2MasterTransport", "Erdos1135.Tao.Renewal.Lemma79R3Pointwise", "Erdos1135.Tao.Renewal.Lemma79R2PositiveKey", "Erdos1135.Tao.Renewal.Lemma79R3AtomBound", "Erdos1135.Tao.Renewal.Lemma79R2PositiveKeyBound", "Erdos1135.Tao.Renewal.Lemma79OneStepBound", "Erdos1135.Tao.Renewal.Lemma79AllRBound", "TrapCanonicalStoppedWhiteTail", "TrapGoodPathProbabilityReduction", "TrapPMFEventTransport", "Erdos1135.Tao.Probability.CountableMarkov", "Erdos1135.Tao.Probability.Geom2CenteredMoment", "Erdos1135.Tao.Probability.Geom2ListProjectivity", "Erdos1135.Tao.Probability.Geom2PrefixTypical", "TrapPascalPrefixProbability", "TrapRawPrefixProbability", "TrapHoldIncrementBounds", "TrapHoldIncrementPath", "TrapHoldGoodFromEvents", "TrapSupportedHoldTube", "TrapHoldGoodProbability", "TrapNativeQualitativeDecay", "TrapSeededDeficit", "TrapUnconditionalDeficit", "TrapMicrocanonicalDeficit", "TrapMicrocanonicalMassFloor", "TrapCentralBinomial", "TrapExactExponentMass", "TrapCentralMicrocanonical"].contains mod.toString then
      unless env.header.modules[i]!.importAll do
        throwError m!"Missing import-all visibility for {mod}"
      let constants := env.header.moduleData[i]!.constNames
      logInfo m!"AUDIT_MODULE|{mod.toString}|{constants.size}"
      for name in constants do
        unless ((env.setExporting false).checked.get.find? name).isSome do
          throwError m!"Missing checked constant {name} in {mod}"
        let axioms ← collectAxioms name
        let visibility := if isPrivateName name then "private" else "public"
        let names := String.intercalate "," (axioms.toList.map Name.toString)
        logInfo m!"AUDIT_AXIOMS|{mod.toString}|{name.toString}|{visibility}|{names}"
