import CanonicalEnvelopeTraceConsequences
import CanonicalEnvelopeArithmeticRegularity
import CanonicalSyracuseMinimumUnitMass
import CanonicalEnvelopeDenseInfinity

set_option autoImplicit false

#print axioms CollatzCanonical.IntegerStationaryEnvelope.canonicalIntegerEnvelope_withDensity
#print axioms CollatzCanonical.IntegerStationaryEnvelope.canonicalIntegerEnvelope_lintegral_eq_one
#print axioms CollatzCanonical.IntegerStationaryEnvelope.canonicalIntegerEnvelope_uniform_unit_floor
#print axioms CollatzCanonical.IntegerStationaryEnvelope.canonicalIntegerEnvelope_natCast_eq
#print axioms CollatzCanonical.IntegerStationaryEnvelope.canonicalIntegerEnvelope_greatest
#print axioms CollatzCanonical.IntegerStationaryEnvelope.canonicalMinimumUnitMass_uniform_bounds
#print axioms CollatzCanonical.IntegerStationaryEnvelope.canonicalMinimumUnitMass_base_three_rate
#print axioms CollatzCanonical.IntegerStationaryEnvelope.canonicalRho_mean_abs_native_trace
#print axioms CollatzCanonical.IntegerStationaryEnvelope.actual_trace_residue_lower
#print axioms CollatzCanonical.IntegerStationaryEnvelope.canonicalIntegerEnvelope_infinity_closure
#print axioms CollatzCanonical.IntegerStationaryEnvelope.canonicalIntegerEnvelope_infinity_isGDelta
#print axioms CollatzCanonical.IntegerStationaryEnvelope.canonicalIntegerEnvelope_infinity_haar_null
#print axioms CollatzCanonical.IntegerStationaryEnvelope.actual_trace_unbounded_in_unit_cylinder
#print axioms CollatzCanonical.IntegerStationaryEnvelope.canonicalIntegerEnvelope_not_continuousAt_positive_unit
