/-
Copyright (c) 2026 Ralf Stephan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ralf Stephan
-/
module

public import DiophantineApproximation.MultiHomogeneous
public import DiophantineApproximation.PolynomialIndex
public import Mathlib.Algebra.MvPolynomial.NoZeroDivisors
public import Mathlib.RingTheory.Ideal.Span

/-!
# The index of a polynomial along a family of linear forms

Bombieri–Gubler's Definition 7.5.17. For `m` blocks of variables `X h : ι → K`, nonzero linear
forms `M h` on the `h`-th block and weights `d h`, the ideal `I(t; d; M)` is generated by the
products `∏ h, M h (X h) ^ (j h)` with `∑ h, j h / d h ≥ t`, and the **index of `P` along `M`**
is the supremum of the `t` for which `P` lies in `I(t; d; M)`.

The file is short because the index is not a new construction. Choose in each block a coordinate
`i₀ h` at which `M h` does not vanish and solve `M h = X (h, i₀ h)` for that one variable: the
ideal becomes a **monomial** ideal, and membership in a monomial ideal is a condition on each
monomial separately. So the index along the forms is the weighted order of
`DiophantineApproximation/WeightedOrder.lean` in the transformed coordinates, for the weights
that see only the coordinates `i₀ h`, and every property below is a property of that order.

## Main definitions

* `MvPolynomial.blockForm`: the linear form `M h` evaluated on the `h`-th block of variables.
* `MvPolynomial.substForm` and `MvPolynomial.substFormInv`: the change of coordinates that puts
  `M h` in place of `X (h, i₀ h)`, and its inverse.
* `MvPolynomial.formIdeal`: the ideal `I(t; d; M)` of Definition 7.5.17, and
  `MvPolynomial.monIdeal` the monomial ideal it becomes in the transformed coordinates.
* `MvPolynomial.formIndex`: **the index along the forms**.
* `MvPolynomial.formWeight`: the weights that read off the exponent of `X (h, i₀ h)`.

## Main results

* `MvPolynomial.mem_monIdeal_iff`: a polynomial lies in the monomial ideal exactly when its
  weighted order is at least `t`; `MvPolynomial.orderIdeal` is the ideal that makes this a
  statement about two ideals.
* `MvPolynomial.mem_formIdeal_iff`: the change of coordinates carries one ideal to the other.
* `MvPolynomial.formIndex_eq_weightedOrder`: **the index along the forms is the weighted order
  in the transformed coordinates**, the identity the rest of the file runs on.
* `MvPolynomial.formIndex_eq_top_iff`, `MvPolynomial.le_formIndex_add` and
  `MvPolynomial.formIndex_mul`: **the index is a valuation**, as in Layer 2.3.
* `MvPolynomial.formIndex_smul`: rescaling the forms changes nothing, which is what lets the
  consumers normalize `M h (i₀ h)` to `1`.
* `MvPolynomial.IsMultiHomogeneous.substForm` and `MvPolynomial.IsMultiHomogeneous.substFormInv`:
  the change of coordinates is linear in each block, so it preserves multihomogeneity.

## Implementation notes

⚠ **The change of coordinates is a row replacement, not a matrix.** Layer 5.2's
`MvPolynomial.blockSubst` applies one matrix to every block, which is what the Subspace Theorem's
linear forms need; here the forms differ from block to block and only one row of each block is
touched. Writing `substForm` and `substFormInv` directly as substitutions makes their mutual
inverseness four lines on the generators — no family of matrices, no determinant and no matrix
inverse anywhere.

⚠ **A weight of `0` is what makes the dictionary work.** `formWeight` gives the weight
`(d h)⁻¹` to `X (h, i₀ h)` and `0` to every other variable, so the weighted order counts only
the exponents of the transformed forms. This is legitimate because
`MvPolynomial.weightedOrder` allows a zero weight and makes the variable invisible to the order,
which is exactly the intended behaviour here and the opposite of what an infinite weight would
do.

⚠ **The ideal is mentioned twice and then never again.** `mem_formIdeal_iff` and
`mem_monIdeal_iff` are the only places where an ideal appears; after
`formIndex_eq_weightedOrder` everything is about supports. The ideal is kept in the *definition*
because it is the book's, and because it is what makes the index visibly independent of the
choice of `i₀`: the definition never mentions `i₀`, only the theorem that computes it does.

⚠ **The valuation properties ask that the forms be nonzero, and only for that reason.**
`formIndex_eq_top_iff`, `le_formIndex_add` and `formIndex_mul` all carry `∀ h, M h ≠ 0`, which
is used exactly once, to produce a coordinate `i₀ h` where `M h` survives
(`MvPolynomial.exists_forall_apply_ne_zero`). With a zero form the ideal `I(t; d; M)` is the
zero ideal for every `t > 0` and the index of every nonzero polynomial is `0`, so the statements
are false as they stand and true after replacing the index by `0`; none of that is needed.

## References

E. Bombieri and W. Gubler, *Heights in Diophantine Geometry*, Cambridge University Press (2006),
Definition 7.5.17 and 7.5.18.

This is Layer 5.3 of the `DiophantineApproximation` roadmap.
-/

@[expose] public section

noncomputable section

open Finset

open scoped ENNReal

namespace MvPolynomial

/-! ### The ideal of high weighted order -/

/-- A `Finset`-indexed product of powers of variables is a monomial. -/
theorem prod_X_pow_eq_monomial_finset_sum {σ α R : Type*} [CommSemiring R] (s : Finset α)
    (f : α → σ) (j : α → ℕ) :
    ∏ a ∈ s, (X (f a) : MvPolynomial σ R) ^ j a
      = monomial (∑ a ∈ s, Finsupp.single (f a) (j a)) 1 := by
  classical
  induction s using Finset.induction with
  | empty => simp
  | insert a s ha ih =>
      rw [Finset.prod_insert ha, Finset.sum_insert ha, ih, X_pow_eq_monomial,
        monomial_mul_monomial, one_mul]

/-- **The ideal of polynomials of weighted order at least `c`.** It is an ideal because the
weighted order is superadditive on products and ultrametric on sums. -/
def orderIdeal (R : Type*) [CommRing R] {σ : Type*} (w : σ → ℝ≥0∞) (c : ℝ≥0∞) :
    Ideal (MvPolynomial σ R) where
  carrier := {Q | c ≤ weightedOrder w Q}
  add_mem' := fun {P Q} hP hQ ↦
    le_trans (le_min (hP : c ≤ weightedOrder w P) (hQ : c ≤ weightedOrder w Q))
      (le_weightedOrder_add w P Q)
  zero_mem' := by simp
  smul_mem' := fun a {Q} hQ ↦ by
    have h1 : c ≤ weightedOrder w (a * Q) :=
      le_trans (hQ : c ≤ weightedOrder w Q) (le_trans le_add_self (add_le_weightedOrder_mul w a Q))
    simpa [smul_eq_mul] using h1

@[simp]
theorem mem_orderIdeal {R : Type*} [CommRing R] {σ : Type*} {w : σ → ℝ≥0∞} {c : ℝ≥0∞}
    {Q : MvPolynomial σ R} : Q ∈ orderIdeal R w c ↔ c ≤ weightedOrder w Q := Iff.rfl

variable {K : Type*} [Field K] {κ ι : Type*}

/-! ### The monomial of a block-exponent -/

section MonExp

variable [Fintype κ]

theorem prod_X_pow_blockDiag (i₀ : κ → ι) (j : κ → ℕ) :
    ∏ h, (X (h, i₀ h) : MvPolynomial (κ × ι) K) ^ j h
      = monomial (∑ h, Finsupp.single ((h, i₀ h) : κ × ι) (j h)) 1 :=
  prod_X_pow_eq_monomial_finset_sum _ _ _

variable [DecidableEq ι]

theorem blockDiag_exp_apply (i₀ : κ → ι) (j : κ → ℕ) (h : κ) (i : ι) :
    (∑ h', Finsupp.single ((h', i₀ h') : κ × ι) (j h')) (h, i) = if i = i₀ h then j h else 0 := by
  classical
  rw [Finset.sum_apply',
    Finset.sum_eq_single_of_mem h (Finset.mem_univ h)
      (fun h' _ hne ↦ by simp [Prod.mk.injEq, hne]),
    Finsupp.single_apply]
  by_cases hi : i = i₀ h
  · subst hi; simp
  · simp [Prod.mk.injEq, hi, Ne.symm hi]

end MonExp

/-! ### The weights of the index along the forms -/

section Weight

variable [Fintype κ] [DecidableEq ι]

/-- The weights that read off the exponent of `X (h, i₀ h)`, scaled by `d h`. Every other
variable has weight `0` and is invisible to the order. -/
def formWeight (i₀ : κ → ι) (d : κ → ℝ) : κ × ι → ℝ≥0∞ :=
  fun p ↦ if p.2 = i₀ p.1 then ENNReal.ofReal (d p.1)⁻¹ else 0

variable [Finite ι]

theorem weight_formWeight {d : κ → ℝ} (hd : ∀ h, 0 ≤ d h) (i₀ : κ → ι) (ν : κ × ι →₀ ℕ) :
    Finsupp.weight (formWeight i₀ d) ν
      = ENNReal.ofReal (∑ h, (ν (h, i₀ h) : ℝ) / d h) := by
  classical
  have : Fintype ι := Fintype.ofFinite ι
  rw [Finsupp.weight_apply, Finsupp.sum_fintype _ _ (by simp), Fintype.sum_prod_type,
    ENNReal.ofReal_sum_of_nonneg fun h _ ↦ div_nonneg (Nat.cast_nonneg _) (hd h)]
  refine Finset.sum_congr rfl fun h _ ↦ ?_
  rw [Finset.sum_eq_single_of_mem (i₀ h) (Finset.mem_univ _)
      (fun i _ hi ↦ by simp [formWeight, hi])]
  simp only [formWeight, ite_true]
  rw [nsmul_eq_mul, ← ENNReal.ofReal_natCast, ← ENNReal.ofReal_mul (Nat.cast_nonneg _),
    div_eq_mul_inv]

theorem weight_blockDiag_exp {d : κ → ℝ} (hd : ∀ h, 0 ≤ d h) (i₀ : κ → ι) (j : κ → ℕ) :
    Finsupp.weight (formWeight i₀ d) (∑ h, Finsupp.single ((h, i₀ h) : κ × ι) (j h))
      = ENNReal.ofReal (∑ h, (j h : ℝ) / d h) := by
  rw [weight_formWeight hd]
  refine congrArg _ (Finset.sum_congr rfl fun h _ ↦ ?_)
  rw [blockDiag_exp_apply]
  simp

end Weight

/-! ### The two ideals of Definition 7.5.17 -/

section Ideals

variable [Fintype κ] [DecidableEq ι]

/-- The ideal generated by the monomials `∏ h, X (h, i₀ h) ^ j h` with `∑ h, j h / d h ≥ t`. -/
def monIdeal (t : ℝ) (d : κ → ℝ) (i₀ : κ → ι) : Ideal (MvPolynomial (κ × ι) K) :=
  Ideal.span {p | ∃ j : κ → ℕ, t ≤ ∑ h, (j h : ℝ) / d h ∧
    p = ∏ h, (X (h, i₀ h) : MvPolynomial (κ × ι) K) ^ j h}

variable [Finite ι]

/-- **The monomial ideal is exactly the polynomials of high weighted order.** -/
theorem mem_monIdeal_iff {d : κ → ℝ} (hd : ∀ h, 0 ≤ d h) (i₀ : κ → ι) (t : ℝ)
    (Q : MvPolynomial (κ × ι) K) :
    Q ∈ monIdeal t d i₀ ↔ ENNReal.ofReal t ≤ weightedOrder (formWeight i₀ d) Q := by
  classical
  constructor
  · intro hQ
    refine (Ideal.span_le.mpr ?_ : monIdeal t d i₀ ≤ orderIdeal K (formWeight i₀ d) _) hQ
    rintro p ⟨j, hj, rfl⟩
    rw [SetLike.mem_coe, mem_orderIdeal, prod_X_pow_blockDiag,
      weightedOrder_monomial (one_ne_zero), weight_blockDiag_exp hd]
    exact ENNReal.ofReal_le_ofReal hj
  · intro hQ
    rw [Q.as_sum]
    refine Ideal.sum_mem _ fun ν hν ↦ ?_
    have hle : (∑ h, Finsupp.single ((h, i₀ h) : κ × ι) (ν (h, i₀ h))) ≤ ν := by
      intro p
      obtain ⟨h, i⟩ := p
      rw [blockDiag_exp_apply]
      by_cases hi : i = i₀ h
      · subst hi; simp
      · simp [hi]
    have hsplit : monomial ν (Q.coeff ν)
        = monomial (ν - ∑ h, Finsupp.single ((h, i₀ h) : κ × ι) (ν (h, i₀ h))) (Q.coeff ν)
          * ∏ h, (X (h, i₀ h) : MvPolynomial (κ × ι) K) ^ ν (h, i₀ h) := by
      rw [prod_X_pow_blockDiag, monomial_mul_monomial, mul_one, tsub_add_cancel_of_le hle]
    rw [hsplit]
    refine Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨fun h ↦ ν (h, i₀ h), ?_, rfl⟩)
    have hw := le_trans hQ (weightedOrder_le_of_coeff_ne_zero
      (w := formWeight i₀ d) (mem_support_iff.mp hν))
    rw [weight_formWeight hd] at hw
    exact (ENNReal.ofReal_le_ofReal_iff
      (Finset.sum_nonneg fun h _ ↦ div_nonneg (Nat.cast_nonneg _) (hd h))).mp hw

end Ideals

/-! ### The forms and the change of coordinates -/

section Subst

variable [Fintype ι] [DecidableEq ι]

/-- The linear form `M h` evaluated on the `h`-th block of variables. -/
def blockForm (M : κ → ι → K) (h : κ) : MvPolynomial (κ × ι) K :=
  ∑ i, C (M h i) * X (h, i)

variable (i₀ : κ → ι) (M : κ → ι → K)

/-- The substitution that puts the form `M h` in place of the variable `X (h, i₀ h)` and leaves
every other variable alone. -/
def substForm : MvPolynomial (κ × ι) K →ₐ[K] MvPolynomial (κ × ι) K :=
  aeval fun p : κ × ι ↦ if p.2 = i₀ p.1 then blockForm M p.1 else X p

/-- The inverse of `MvPolynomial.substForm`: it solves `M h = X (h, i₀ h)` for the variable
`X (h, i₀ h)`. -/
def substFormInv : MvPolynomial (κ × ι) K →ₐ[K] MvPolynomial (κ × ι) K :=
  aeval fun p : κ × ι ↦ if p.2 = i₀ p.1 then
      C (M p.1 (i₀ p.1))⁻¹ *
        (X p - ∑ i ∈ univ.erase (i₀ p.1), C (M p.1 i) * X ((p.1, i) : κ × ι))
    else X p

@[simp]
theorem substForm_X_self (h : κ) : substForm i₀ M (X (h, i₀ h)) = blockForm M h := by
  simp [substForm]

theorem substForm_X_of_ne {h : κ} {i : ι} (hi : i ≠ i₀ h) :
    substForm i₀ M (X (h, i)) = X (h, i) := by
  simp [substForm, hi]

@[simp]
theorem substFormInv_X_self (h : κ) :
    substFormInv i₀ M (X (h, i₀ h))
      = C (M h (i₀ h))⁻¹ *
        (X (h, i₀ h) - ∑ i ∈ univ.erase (i₀ h), C (M h i) * X ((h, i) : κ × ι)) := by
  simp [substFormInv]

theorem substFormInv_X_of_ne {h : κ} {i : ι} (hi : i ≠ i₀ h) :
    substFormInv i₀ M (X (h, i)) = X (h, i) := by
  simp [substFormInv, hi]

variable {i₀ M}

theorem substForm_substFormInv (hM : ∀ h, M h (i₀ h) ≠ 0) (P : MvPolynomial (κ × ι) K) :
    substForm i₀ M (substFormInv i₀ M P) = P := by
  have key : (substForm i₀ M).comp (substFormInv i₀ M)
      = AlgHom.id K (MvPolynomial (κ × ι) K) := by
    refine MvPolynomial.algHom_ext fun p ↦ ?_
    obtain ⟨h, i⟩ := p
    rcases eq_or_ne i (i₀ h) with rfl | hi
    · rw [AlgHom.comp_apply, substFormInv_X_self, map_mul, MvPolynomial.algHom_C, map_sub,
        substForm_X_self, map_sum, AlgHom.id_apply]
      have hrest : ∑ i ∈ univ.erase (i₀ h), substForm i₀ M (C (M h i) * X ((h, i) : κ × ι))
          = ∑ i ∈ univ.erase (i₀ h), C (M h i) * X ((h, i) : κ × ι) := by
        refine Finset.sum_congr rfl fun i hi ↦ ?_
        rw [map_mul, MvPolynomial.algHom_C, MvPolynomial.algebraMap_eq,
          substForm_X_of_ne i₀ M (Finset.mem_erase.mp hi).1]
      rw [MvPolynomial.algebraMap_eq, hrest, blockForm,
        ← Finset.sum_erase_add _ _ (Finset.mem_univ (i₀ h)), add_sub_cancel_left,
        ← mul_assoc, ← map_mul, inv_mul_cancel₀ (hM h), map_one, one_mul]
    · rw [AlgHom.comp_apply, substFormInv_X_of_ne i₀ M hi, substForm_X_of_ne i₀ M hi,
        AlgHom.id_apply]
  exact congrArg (fun f ↦ f P) key

theorem substFormInv_substForm (hM : ∀ h, M h (i₀ h) ≠ 0) (P : MvPolynomial (κ × ι) K) :
    substFormInv i₀ M (substForm i₀ M P) = P := by
  have key : (substFormInv i₀ M).comp (substForm i₀ M)
      = AlgHom.id K (MvPolynomial (κ × ι) K) := by
    refine MvPolynomial.algHom_ext fun p ↦ ?_
    obtain ⟨h, i⟩ := p
    rcases eq_or_ne i (i₀ h) with rfl | hi
    · rw [AlgHom.comp_apply, substForm_X_self, blockForm, map_sum, AlgHom.id_apply,
        ← Finset.sum_erase_add _ _ (Finset.mem_univ (i₀ h))]
      have hrest : ∑ i ∈ univ.erase (i₀ h), substFormInv i₀ M (C (M h i) * X ((h, i) : κ × ι))
          = ∑ i ∈ univ.erase (i₀ h), C (M h i) * X ((h, i) : κ × ι) := by
        refine Finset.sum_congr rfl fun i hi ↦ ?_
        rw [map_mul, MvPolynomial.algHom_C, MvPolynomial.algebraMap_eq,
          substFormInv_X_of_ne i₀ M (Finset.mem_erase.mp hi).1]
      rw [hrest, map_mul, MvPolynomial.algHom_C, MvPolynomial.algebraMap_eq,
        substFormInv_X_self, ← mul_assoc, ← map_mul,
        mul_inv_cancel₀ (hM h), map_one, one_mul]
      ring
    · rw [AlgHom.comp_apply, substForm_X_of_ne i₀ M hi, substFormInv_X_of_ne i₀ M hi,
        AlgHom.id_apply]
  exact congrArg (fun f ↦ f P) key

theorem substForm_injective (hM : ∀ h, M h (i₀ h) ≠ 0) :
    Function.Injective (substForm i₀ M) :=
  Function.LeftInverse.injective (substFormInv_substForm hM)

theorem substFormInv_injective (hM : ∀ h, M h (i₀ h) ≠ 0) :
    Function.Injective (substFormInv i₀ M) :=
  Function.LeftInverse.injective (substForm_substFormInv hM)

variable [Fintype κ] in
/-- **The ideal `I(t; d; M)` of Definition 7.5.17**: the ideal generated by the products
`∏ h, M h (X h) ^ j h` whose weighted order `∑ h, j h / d h` is at least `t`. -/
def formIdeal (t : ℝ) (d : κ → ℝ) (M : κ → ι → K) : Ideal (MvPolynomial (κ × ι) K) :=
  Ideal.span {p | ∃ j : κ → ℕ, t ≤ ∑ h, (j h : ℝ) / d h ∧ p = ∏ h, blockForm M h ^ j h}

end Subst

/-! ### The index along the forms -/

section Index

variable [Fintype ι] [DecidableEq ι] [Fintype κ]

omit [Fintype κ] in
theorem substFormInv_blockForm {i₀ : κ → ι} {M : κ → ι → K} (hM : ∀ h, M h (i₀ h) ≠ 0) (h : κ) :
    substFormInv i₀ M (blockForm M h) = X (h, i₀ h) := by
  have := substFormInv_substForm hM (X ((h, i₀ h) : κ × ι))
  rwa [substForm_X_self] at this

/-- **The change of coordinates carries the monomial ideal to the ideal of Definition
7.5.17.** -/
theorem mem_formIdeal_iff {i₀ : κ → ι} {M : κ → ι → K} (hM : ∀ h, M h (i₀ h) ≠ 0) (t : ℝ)
    (d : κ → ℝ) (P : MvPolynomial (κ × ι) K) :
    P ∈ formIdeal t d M ↔ substFormInv i₀ M P ∈ monIdeal t d i₀ := by
  have hfwd : formIdeal t d M ≤ Ideal.comap (substFormInv i₀ M).toRingHom (monIdeal t d i₀) := by
    refine Ideal.span_le.mpr ?_
    rintro p ⟨j, hj, rfl⟩
    refine Ideal.mem_comap.mpr (Ideal.subset_span ⟨j, hj, ?_⟩)
    simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, map_prod]
    exact Finset.prod_congr rfl fun h _ ↦ by rw [map_pow, substFormInv_blockForm hM]
  have hbwd : monIdeal t d i₀ ≤ Ideal.comap (substForm i₀ M).toRingHom (formIdeal t d M) := by
    refine Ideal.span_le.mpr ?_
    rintro p ⟨j, hj, rfl⟩
    refine Ideal.mem_comap.mpr (Ideal.subset_span ⟨j, hj, ?_⟩)
    simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, map_prod]
    exact Finset.prod_congr rfl fun h _ ↦ by rw [map_pow, substForm_X_self]
  refine ⟨fun hP ↦ hfwd hP, fun hP ↦ ?_⟩
  have := hbwd hP
  rwa [Ideal.mem_comap, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
    substForm_substFormInv hM] at this

/-- **Layer 5.3. The index of `P` along the forms `M`** (Bombieri–Gubler, Definition 7.5.17):
the supremum of the `t` for which `P` lies in the ideal `I(t; d; M)`. -/
def formIndex (d : κ → ℝ) (M : κ → ι → K) (P : MvPolynomial (κ × ι) K) : ℝ≥0∞ :=
  ⨆ t : ℝ, ⨆ _ : P ∈ formIdeal t d M, ENNReal.ofReal t

/-- **The index along the forms is the weighted order in the transformed coordinates.**
Everything below is this identity and a theorem of
`DiophantineApproximation/WeightedOrder.lean`. -/
theorem formIndex_eq_weightedOrder {d : κ → ℝ} (hd : ∀ h, 0 ≤ d h) {i₀ : κ → ι} {M : κ → ι → K}
    (hM : ∀ h, M h (i₀ h) ≠ 0) (P : MvPolynomial (κ × ι) K) :
    formIndex d M P = weightedOrder (formWeight i₀ d) (substFormInv i₀ M P) := by
  have hmem : ∀ t : ℝ, P ∈ formIdeal t d M ↔
      ENNReal.ofReal t ≤ weightedOrder (formWeight i₀ d) (substFormInv i₀ M P) := fun t ↦ by
    rw [mem_formIdeal_iff hM, mem_monIdeal_iff hd]
  refine le_antisymm (iSup_le fun t ↦ iSup_le fun ht ↦ (hmem t).mp ht) (le_of_forall_lt ?_)
  intro c hc
  obtain ⟨c', hcc', hc'ω⟩ := exists_between hc
  have hc'top : c' ≠ ⊤ := ne_top_of_lt hc'ω
  have hc'eq : ENNReal.ofReal c'.toReal = c' := ENNReal.ofReal_toReal hc'top
  refine lt_of_lt_of_le hcc' ?_
  rw [← hc'eq]
  exact le_iSup_of_le c'.toReal
    (le_iSup_of_le ((hmem c'.toReal).mpr (by rw [hc'eq]; exact hc'ω.le)) le_rfl)

end Index

/-! ### Multihomogeneity -/

section MultiHom

variable [Fintype ι] [DecidableEq ι] [Finite κ] [DecidableEq κ]

omit [DecidableEq ι] [Finite κ] in
theorem isWeightedHomogeneous_blockForm (M : κ → ι → K) (h : κ) (i : ι) :
    IsWeightedHomogeneous (blockWeight κ ι) (blockForm M h) (blockWeight κ ι (h, i)) := by
  refine IsWeightedHomogeneous.sum _ _ _ fun i' _ ↦ ?_
  have hX := isWeightedHomogeneous_X K (blockWeight κ ι) ((h, i') : κ × ι)
  simpa [blockWeight] using hX.C_mul (M h i')

omit [DecidableEq ι] in
theorem isMultiHomogeneous_aeval {d : κ → ℕ} {g : κ × ι → MvPolynomial (κ × ι) K}
    (hg : ∀ p, IsWeightedHomogeneous (blockWeight κ ι) (g p) (blockWeight κ ι p))
    {P : MvPolynomial (κ × ι) K} (hP : IsMultiHomogeneous d P) :
    IsMultiHomogeneous d (aeval g P) := by
  rw [isMultiHomogeneous_iff] at hP ⊢
  exact IsWeightedHomogeneous.aeval hg hP

omit [DecidableEq κ] in
/-- **The change of coordinates preserves multihomogeneity**: it is linear in each block. -/
theorem IsMultiHomogeneous.substForm {d : κ → ℕ} {P : MvPolynomial (κ × ι) K}
    (hP : IsMultiHomogeneous d P) (i₀ : κ → ι) (M : κ → ι → K) :
    IsMultiHomogeneous d (MvPolynomial.substForm i₀ M P) := by
  classical
  refine isMultiHomogeneous_aeval (fun p ↦ ?_) hP
  obtain ⟨h, i⟩ := p
  by_cases hi : i = i₀ h
  · simpa [hi] using isWeightedHomogeneous_blockForm M h i
  · simpa [hi] using isWeightedHomogeneous_X K (blockWeight κ ι) ((h, i) : κ × ι)

omit [DecidableEq κ] in
/-- **The inverse change of coordinates preserves multihomogeneity.** -/
theorem IsMultiHomogeneous.substFormInv {d : κ → ℕ} {P : MvPolynomial (κ × ι) K}
    (hP : IsMultiHomogeneous d P) (i₀ : κ → ι) (M : κ → ι → K) :
    IsMultiHomogeneous d (MvPolynomial.substFormInv i₀ M P) := by
  classical
  refine isMultiHomogeneous_aeval (fun p ↦ ?_) hP
  obtain ⟨h, i⟩ := p
  by_cases hi : i = i₀ h
  · have hsum : IsWeightedHomogeneous (blockWeight κ ι)
        (∑ i' ∈ univ.erase (i₀ h), C (M h i') * X ((h, i') : κ × ι))
        (blockWeight κ ι ((h, i) : κ × ι)) := by
      refine IsWeightedHomogeneous.sum _ _ _ fun i' _ ↦ ?_
      have hX := isWeightedHomogeneous_X K (blockWeight κ ι) ((h, i') : κ × ι)
      simpa [blockWeight] using hX.C_mul (M h i')
    have hX := isWeightedHomogeneous_X K (blockWeight κ ι) ((h, i) : κ × ι)
    have hsub := (hX.sub hsum).C_mul (M h (i₀ h))⁻¹
    simpa [hi] using hsub
  · simpa [hi] using isWeightedHomogeneous_X K (blockWeight κ ι) ((h, i) : κ × ι)

end MultiHom

/-! ### The valuation properties -/

section Valuation

variable [Fintype ι] [DecidableEq ι] [Fintype κ] {d : κ → ℝ} {M : κ → ι → K}

omit [Fintype ι] [DecidableEq ι] [Fintype κ] in
theorem exists_forall_apply_ne_zero (hM : ∀ h, M h ≠ 0) : ∃ i₀ : κ → ι, ∀ h, M h (i₀ h) ≠ 0 := by
  have hex : ∀ h, ∃ i, M h i ≠ 0 := fun h ↦ Function.ne_iff.mp (hM h)
  choose i₀ hi₀ using hex
  exact ⟨i₀, hi₀⟩

omit [Fintype ι] [Fintype κ] in
theorem formWeight_ne_top (i₀ : κ → ι) (dd : κ → ℝ) (p : κ × ι) : formWeight i₀ dd p ≠ ⊤ := by
  simp only [formWeight]
  split <;> simp

/-- A monomial of the transformed polynomial bounds the index from above. -/
theorem formIndex_le (hd : ∀ h, 0 ≤ d h) {i₀ : κ → ι} (hM : ∀ h, M h (i₀ h) ≠ 0)
    {P : MvPolynomial (κ × ι) K} {ν : κ × ι →₀ ℕ} (hν : (substFormInv i₀ M P).coeff ν ≠ 0) :
    formIndex d M P ≤ ENNReal.ofReal (∑ h, (ν (h, i₀ h) : ℝ) / d h) := by
  rw [formIndex_eq_weightedOrder hd hM, ← weight_formWeight hd i₀ ν]
  exact weightedOrder_le_of_coeff_ne_zero hν

/-- To bound the index from below, bound every monomial of the transformed polynomial. -/
theorem le_formIndex (hd : ∀ h, 0 ≤ d h) {i₀ : κ → ι} (hM : ∀ h, M h (i₀ h) ≠ 0)
    {P : MvPolynomial (κ × ι) K} {c : ℝ≥0∞}
    (h : ∀ ν : κ × ι →₀ ℕ, (substFormInv i₀ M P).coeff ν ≠ 0 →
      c ≤ ENNReal.ofReal (∑ h, (ν (h, i₀ h) : ℝ) / d h)) :
    c ≤ formIndex d M P := by
  rw [formIndex_eq_weightedOrder hd hM]
  exact le_weightedOrder fun ν hν ↦ by rw [weight_formWeight hd]; exact h ν hν

omit [DecidableEq ι] in
/-- **The index is `⊤` exactly at the zero polynomial.** -/
theorem formIndex_eq_top_iff (hd : ∀ h, 0 ≤ d h) (hM : ∀ h, M h ≠ 0)
    (P : MvPolynomial (κ × ι) K) : formIndex d M P = ⊤ ↔ P = 0 := by
  classical
  obtain ⟨i₀, hi₀⟩ := exists_forall_apply_ne_zero hM
  rw [formIndex_eq_weightedOrder hd hi₀, weightedOrder_eq_top_iff (formWeight_ne_top i₀ d),
    map_eq_zero_iff _ (substFormInv_injective hi₀)]

omit [DecidableEq ι] in
/-- **The ultrametric inequality.** -/
theorem le_formIndex_add (hd : ∀ h, 0 ≤ d h) (hM : ∀ h, M h ≠ 0)
    (P Q : MvPolynomial (κ × ι) K) :
    min (formIndex d M P) (formIndex d M Q) ≤ formIndex d M (P + Q) := by
  classical
  obtain ⟨i₀, hi₀⟩ := exists_forall_apply_ne_zero hM
  rw [formIndex_eq_weightedOrder hd hi₀ P, formIndex_eq_weightedOrder hd hi₀ Q,
    formIndex_eq_weightedOrder hd hi₀ (P + Q), map_add]
  exact le_weightedOrder_add _ _ _

omit [DecidableEq ι] in
/-- **The index is additive on products.** -/
theorem formIndex_mul (hd : ∀ h, 0 ≤ d h) (hM : ∀ h, M h ≠ 0) (P Q : MvPolynomial (κ × ι) K) :
    formIndex d M (P * Q) = formIndex d M P + formIndex d M Q := by
  classical
  obtain ⟨i₀, hi₀⟩ := exists_forall_apply_ne_zero hM
  rw [formIndex_eq_weightedOrder hd hi₀ P, formIndex_eq_weightedOrder hd hi₀ Q,
    formIndex_eq_weightedOrder hd hi₀ (P * Q), map_mul]
  exact weightedOrder_mul (formWeight_ne_top i₀ d) _ _

omit [DecidableEq ι] in
@[simp]
theorem formIndex_zero :
    formIndex d M (0 : MvPolynomial (κ × ι) K) = ⊤ := by
  refine eq_top_iff.mpr (le_of_forall_lt fun c hc ↦ ?_)
  have hctop : c ≠ ⊤ := hc.ne
  refine lt_of_lt_of_le (ENNReal.lt_add_right hctop one_ne_zero) ?_
  refine le_iSup_of_le (c + 1).toReal (le_iSup_of_le (Submodule.zero_mem _) ?_)
  exact le_of_eq (ENNReal.ofReal_toReal (by simp [hctop])).symm

omit [DecidableEq ι] in
/-- **The index does not change when the forms are rescaled**: the ideal they generate does
not. -/
theorem formIndex_smul {a : κ → K} (ha : ∀ h, a h ≠ 0) (P : MvPolynomial (κ × ι) K) :
    formIndex d (fun h i ↦ a h * M h i) P = formIndex d M P := by
  have hform : ∀ h, blockForm (fun h i ↦ a h * M h i) h = C (a h) * blockForm M h := by
    intro h
    rw [blockForm, blockForm, Finset.mul_sum]
    exact Finset.sum_congr rfl fun i _ ↦ by rw [map_mul, mul_assoc]
  have hexp : ∀ j : κ → ℕ, ∏ h, blockForm (fun h i ↦ a h * M h i) h ^ j h
      = C (∏ h, a h ^ j h) * ∏ h, blockForm M h ^ j h := by
    intro j
    rw [map_prod, ← Finset.prod_mul_distrib]
    exact Finset.prod_congr rfl fun h _ ↦ by rw [hform, mul_pow, map_pow]
  have hideal : ∀ t : ℝ, formIdeal t d (fun h i ↦ a h * M h i) = formIdeal t d M := by
    intro t
    refine le_antisymm (Ideal.span_le.mpr ?_) (Ideal.span_le.mpr ?_)
    · rintro p ⟨j, hj, rfl⟩
      rw [SetLike.mem_coe, hexp j]
      exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨j, hj, rfl⟩)
    · rintro p ⟨j, hj, rfl⟩
      have hane : (∏ h, a h ^ j h) ≠ 0 :=
        Finset.prod_ne_zero_iff.mpr fun h _ ↦ pow_ne_zero _ (ha h)
      have hback : ∏ h, blockForm M h ^ j h
          = C (∏ h, a h ^ j h)⁻¹ * ∏ h, blockForm (fun h i ↦ a h * M h i) h ^ j h := by
        rw [hexp j, ← mul_assoc, ← map_mul, inv_mul_cancel₀ hane, map_one, one_mul]
      rw [SetLike.mem_coe, hback]
      exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨j, hj, rfl⟩)
  simp only [formIndex, hideal]

end Valuation

end MvPolynomial
