import PeriodicSourceMean
import TerminalFanEnvelope
import TerminalFanCensus
import FrozenSeedPeriodicPrefix
import GaoShortcutBridge
import BasinAdjacentVariation
import OddTerminalFanMean
import ActualBasinPeriodicMean
import ActualBasinPolynomialFloor
import CanonicalTracePolynomialFloor

#print axioms CollatzCanonical.GaoShortcut.basin_adjacent_difference_le_one
#print axioms CollatzCanonical.GaoShortcut.basin_adjacent_variation_bound
#print axioms CollatzCanonical.GaoShortcut.basin_adjacent_variation_bound._proof_1_1
#print axioms CollatzCanonical.GaoShortcut.basin_adjacent_variation_tendsto_zero
#print axioms CollatzCanonical.GaoShortcut.basin_adjacent_variation_tendsto_zero._proof_1_1
#print axioms CollatzCanonical.GaoShortcut.basin_eq_of_good
#print axioms CollatzCanonical.GaoShortcut.basin_eq_of_good._proof_1_1
#print axioms CollatzCanonical.GaoShortcut.good
#print axioms CollatzCanonical.GaoShortcut.goodProbability
#print axioms CollatzCanonical.GaoShortcut.goodProbability_bounds
#print axioms CollatzCanonical.GaoShortcut.goodProbability_eventually
#print axioms CollatzCanonical.GaoShortcut.good_card
#print axioms CollatzCanonical.GaoShortcut.good_count_lower
#print axioms CollatzCanonical.GaoShortcut.good_count_lower._simp_1_1
#print axioms CollatzCanonical.GaoShortcut.good_count_lower._simp_1_2
#print axioms CollatzCanonical.GaoShortcut.good_iff
#print axioms CollatzCanonical.GaoShortcut.good_mod
#print axioms CollatzCanonical.GaoShortcut.imp_nat
#print axioms CollatzCanonical.GaoShortcut.imp_nat._proof_1_1
#print axioms CollatzCanonical.GaoShortcut.instDecidableGood
#print axioms CollatzCanonical.GaoShortcut.pair_iterate
#print axioms CollatzCanonical.GaoShortcut.prefix_avoids_of_large
#print axioms CollatzCanonical.GaoShortcut.prefix_avoids_of_large._proof_1_1
#print axioms CollatzCanonical.GaoShortcut.tm_nat
#print axioms CollatzCanonical.GaoShortcut.tm_nat._proof_1_1
#print axioms CollatzCanonical.GaoShortcut.tm_nat._proof_1_2
#print axioms CollatzCanonical.PeriodicCensusFloor.actual_basin_adjacentVariation
#print axioms CollatzCanonical.PeriodicCensusFloor.actual_basin_oddTerminalFan_scaled_limit
#print axioms CollatzCanonical.PeriodicCensusFloor.actual_basin_oddTerminalFan_sourceMean
#print axioms CollatzCanonical.PeriodicCensusFloor.actual_basin_periodic_sourceMean
#print axioms CollatzCanonical.PeriodicCensusFloor.actual_basin_polynomial_lower_density
#print axioms CollatzCanonical.PeriodicCensusFloor.actual_basin_sourceMean
#print axioms CollatzCanonical.PeriodicCensusFloor.adjacentVariation
#print axioms CollatzCanonical.PeriodicCensusFloor.basinIndicator_abs_le_one
#print axioms CollatzCanonical.PeriodicCensusFloor.centered_weighted_mean_tendsto_zero
#print axioms CollatzCanonical.PeriodicCensusFloor.exists_frozen_seed_eventual_periodic_prefix
#print axioms CollatzCanonical.PeriodicCensusFloor.exists_frozen_seed_eventual_periodic_prefix._proof_1_1
#print axioms CollatzCanonical.PeriodicCensusFloor.exists_frozen_seed_eventual_periodic_prefix._proof_1_2
#print axioms CollatzCanonical.PeriodicCensusFloor.exists_frozen_seed_eventual_periodic_prefix._proof_1_3
#print axioms CollatzCanonical.PeriodicCensusFloor.exists_frozen_seed_eventual_periodic_prefix._proof_1_4
#print axioms CollatzCanonical.PeriodicCensusFloor.exists_frozen_seed_eventual_periodic_prefix._proof_1_5
#print axioms CollatzCanonical.PeriodicCensusFloor.exists_frozen_seed_eventual_periodic_prefix._proof_1_6
#print axioms CollatzCanonical.PeriodicCensusFloor.exists_frozen_seed_eventual_periodic_prefix._proof_1_7
#print axioms CollatzCanonical.PeriodicCensusFloor.exists_frozen_seed_eventual_periodic_prefix._proof_1_8
#print axioms CollatzCanonical.PeriodicCensusFloor.exists_uniform_firstHit_reciprocal_floor
#print axioms CollatzCanonical.PeriodicCensusFloor.exists_uniform_unit_canonical_trace_floor
#print axioms CollatzCanonical.PeriodicCensusFloor.forwardGoodDepthShiftUnitMass_le_envelope_sources
#print axioms CollatzCanonical.PeriodicCensusFloor.frozen_seed_periodic_density_bound
#print axioms CollatzCanonical.PeriodicCensusFloor.fullTerminal_fan_le_envelope
#print axioms CollatzCanonical.PeriodicCensusFloor.greenCycleFactor_one_ge_one
#print axioms CollatzCanonical.PeriodicCensusFloor.greenCycleFactor_one_ge_one._simp_1_1
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan.eq_1
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan_le
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan_mean
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan_nonneg
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan_paired
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan_paired._proof_1_1
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan_periodic
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan_periodic._proof_1_1
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan_scaled_source_limit
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan_scaled_source_limit._proof_1_1
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan_sum
#print axioms CollatzCanonical.PeriodicCensusFloor.oddTerminalFan_weighted_mean
#print axioms CollatzCanonical.PeriodicCensusFloor.periodic_weighted_mean
#print axioms CollatzCanonical.PeriodicCensusFloor.periodic_weighted_mean._simp_1_2
#print axioms CollatzCanonical.PeriodicCensusFloor.periodic_zero_sum_prefix_bound
#print axioms CollatzCanonical.PeriodicCensusFloor.periodic_zero_sum_prefix_bound._proof_1_1
#print axioms CollatzCanonical.PeriodicCensusFloor.sourceMean
#print axioms CollatzCanonical.PeriodicCensusFloor.sourceMean.eq_1
#print axioms CollatzCanonical.PeriodicCensusFloor.sourceMean_of_shift
#print axioms CollatzCanonical.PeriodicCensusFloor.sourceMean_shift_sub
#print axioms CollatzCanonical.PeriodicCensusFloor.terminalEnvelope_source_sum_le_basin_prefix
#print axioms CollatzCanonical.PeriodicCensusFloor.terminalFanEnvelope
#print axioms CollatzCanonical.PeriodicCensusFloor.terminalFanEnvelope._proof_1
#print axioms CollatzCanonical.PeriodicCensusFloor.terminalFanEnvelope_dominates
#print axioms CollatzCanonical.PeriodicCensusFloor.terminalFanEnvelope_fullMean
#print axioms CollatzCanonical.PeriodicCensusFloor.terminalFanEnvelope_le
#print axioms CollatzCanonical.PeriodicCensusFloor.terminalFanEnvelope_nat_sum
#print axioms CollatzCanonical.PeriodicCensusFloor.terminalFanEnvelope_nonneg
#print axioms CollatzCanonical.PeriodicCensusFloor.terminalFanEnvelope_summable
#print axioms CollatzCanonical.PeriodicCensusFloor.weighted_centered_sum_bound
